### ISSUE TITLE
Show full history for a bill (i.e., board report)

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#114]
Here's an example.

[2016-1006](https://boardagendas.metro.net/board-report/2016-1006/) - [here](http://ocd.datamade.us/ocd-bill/ca0fa229-5e03-4d0c-b9c8-f7e8aacd0beb/) for ocd api - shows actions taken by the Board of Directors.

However, the Executive Management Committee [adopted revisions in January](https://boardagendas.metro.net/event/executive-management-committee-5e05eda69254/). http://ocd.datamade.us/ocd-event/a134fd0a-78db-4ff3-a694-5e05eda69254/

It would be nice if the "related entities" for an event were also "actions" for a bill. Is this possible? Or is there a reason we do not do this in the first place?

**Comment by reginafcompton** [comment]
Same example from the legistar webapi:

Shows the Full Board meeting, but not the Executive Management Committee: http://webapi.legistar.com/v1/metro/Matters/3802/Histories?AgendaNote=1&MinutesNote=1 
 
Executive Management Committee: http://webapi.legistar.com/v1/metro/Events/1180/EventItems?AgendaNote=1&MinutesNote=1
Full Board Meeting: http://webapi.legistar.com/v1/metro/Events/1184/EventItems?AgendaNote=1&MinutesNote=1

**Comment by fgregg** [comment]
This looks like something that that the metro board need to fix upstream.  Why do you think otherwise?
