### ISSUE TITLE
Add definitions of Board Report "Status" on About page

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#123]
Omar and Shelly will provide definitions for Approved, Active, Withdrawn, and Adopted.

**Comment by shrayshray** [comment]
Here are the report actions definitions! [Report Action Definitions.xlsx](https://github.com/datamade/la-metro-councilmatic/files/3556750/Report.Action.Definitions.xlsx)

**Comment by hancush** [comment]
Also update Board Box to Board Correspondence.

**Comment by hancush** [comment]
Start with the content we have (https://github.com/datamade/la-metro-councilmatic/issues/123#issuecomment-526289354) and then add board correspondence when it arrives.

**Comment by fatima3558** [comment]
@shrayshray this has been merged into staging! could you confirm that this looks good on your end? 

https://lametro-upgrade.datamade.us/about/

**Comment by shrayshray** [comment]
@fatima3558 this looks great!
