### ISSUE TITLE
Events page: show a link to relevant board reports

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#132]
The agenda (event document) for any given event contains links to board reports. However, these urls do not direct the user to the Metro Councilmatic board report page.

Example event:
https://boardagendas.metro.net/event/construction-committee-7e7006e0afe8/

To solve this, we will add links to these board reports, in a section on the event detail page.

**Comment by reginafcompton** [comment]
The link should not redirect to the board report, but instead download the Board Report packet. (Put the **board report name** not just the identifier.)

**Comment by reginafcompton** [comment]
For order:
(1) Look at the agenda item number to determine the order of the board reports;
(2) Alphabetical (by board name)
(3) Ascending numerical

**Comment by shrayshray** [comment]
Mock-up of Reports on Agenda page.
![v5](https://cloud.githubusercontent.com/assets/28063988/26225821/edc47e18-3bdd-11e7-9986-d07596999091.png)

**Comment by shrayshray** [comment]
@reginafcompton We're going with option 3 for ordering Board Reports -- by File ID in ascending order.
