### ISSUE TITLE
Home page: agenda for the next meeting lists items in wrong order

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#134]
The agenda items, listed below download option, do not map exactly with the order in the PDF. Look into this. 

![image001](https://cloud.githubusercontent.com/assets/13078679/25451404/aef441a8-2a87-11e7-9878-853b29aaa7bb.png)

**Comment by shrayshray** [comment]
@reginafcompton Correct, we do not want the text view - even on mobile, we just want the "Get Agenda" button.
