### ISSUE TITLE
Home: Current and Next Meeting both showing

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#136]
During the board meeting this morning, both the current meeting and the next Regular Board meeting (5/20/2017) were displayed on the home page. See screenshot, taken at 10:34am.
  @@![nextandcurrentmeeting-1035](https://cloud.githubusercontent.com/assets/28063988/25496484/05eb7432-2b36-11e7-91c1-dadc454d0eab.png)

**Comment by reginafcompton** [comment]
This is the intended behavior. Do we want to do something different @shrayshray ?

**Comment by shrayshray** [comment]
We thought these would toggle so Current would replace Next when there is a meeting in session @reginafcompton . Is this possible?

**Comment by reginafcompton** [comment]
Also: when it's current, have the current meeting show up five minutes before it starts.

**Comment by reginafcompton** [comment]
For audio: Metro will try to add the link 15 minutes ahead, if not show the general link.
