### ISSUE TITLE
Home: Link to listen to current meeting missing.

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#137]
During this morning's Board Meeting, the link to "Listen" to the current meeting was not showing.

**Comment by reginafcompton** [comment]
The link had not been made available on Legistar. Screen shot from 1:15 CST.

<img width="1267" alt="screen shot 2017-04-27 at 1 13 24 pm" src="https://cloud.githubusercontent.com/assets/13078679/25497854/7d82974a-2b4b-11e7-8924-a70a2c178082.png">

**Comment by reginafcompton** [comment]
@shrayshray Do you know when that link appears?

**Comment by shrayshray** [comment]
@reginafcompton So, I think the reason I didn't see the link earlier is because the meeting had already ended. The link appears when the meeting begins, and disappears after the meeting ends. Once the recording has been approved, the link appears again and links to the recording.

**Comment by reginafcompton** [comment]
Show link to general link to player.

**Comment by reginafcompton** [comment]
I looked into the possibility of showing a general player link, and it looks like Granicus does not have that option.

@shrayshray Do we have more information about the timing of the link activation, so that we can try to coordinate the scrapper?

**Comment by shrayshray** [comment]
@reginafcompton It's not possible to just use this link? http://metro.granicus.com/MediaPlayer.php?camera_id=2

**Comment by reginafcompton** [comment]
@shrayshray Ah, okay. That will work.

**Comment by reginafcompton** [comment]
Generic link has been added. Closing.
