### ISSUE TITLE
Event: Missing Embedded PDF of Meeting Agenda

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#139]
@reginafcompton This meeting agenda is showing as text instead of embedded PDF: https://boardagendas.metro.net/event/ad-hoc-transit-policing-oversight-committee-771a3b70243f/

**Comment by reginafcompton** [comment]
Thanks, @shrayshray. I'll take a look at this and the other issues shortly.

**Comment by reginafcompton** [comment]
@shrayshray It looks like this meeting does not exist on Legistar. The API returns a 404: http://webapi.legistar.com/v1/metro/events/1224

Did this meeting not take place?

**Comment by shrayshray** [comment]
@reginafcompton You're right, I can't find evidence of it anywhere. The only thing I can think of is it might be the test meeting the Office of the Board Secretary created when we tested the general link to listen live. However, that test meeting was never made public, so I'm kinda at a loss. Are you able to remove it from the site?

**Comment by reginafcompton** [comment]
@shrayshray Yes, I can delete it from our OCD API and the Metro database....I'll also see if this is something we can address with the forthcoming scraper enhancements.

**Comment by reginafcompton** [comment]
Closing this, since this specific problem has been resolved and future related issues will be resolved by the scraper enhancements.
