### ISSUE TITLE
Event: Disable display of Draft agendas

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#143]
Meeting Agendas should only display once they have been published aka status changed to "Final" and marked "Public".

**Comment by reginafcompton** [comment]
On mobile view, we might just show the text only.

We will wait for final word from LA Metro on this issue.

**Comment by shrayshray** [comment]
@reginafcompton just want to confirm this issue is ready to be closed?

**Comment by reginafcompton** [comment]
Yes! Closing.
