### ISSUE TITLE
Home: Background Map image orientation

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#149]
@reginafcompton The text for the link to "Search the Metro Board Archive (1952-2015)" is obscured by the text on the image behind it. Is it possible to crop or adjust the image so the text appears in either of the areas highlighted in the image attached? 
I'm also seeing the link kind of obscured on mobile (see attached screenshot from iPhone 6s Plus). Maybe once the text is moved to a location with less interference on the desktop site, it's possible to reduce the font size slightly and avoid the text wrap? I'm open to to other ideas you have for how to approach this, 

![mapreorientation](https://cloud.githubusercontent.com/assets/28063988/26179063/26b79d54-3b16-11e7-9bf6-09bde9dbbd03.png)
![linktextmobile](https://cloud.githubusercontent.com/assets/28063988/26179065/28f06b00-3b16-11e7-9c89-e7be23cac81b.png)

**Comment by reginafcompton** [comment]
@shrayshray This change appears on the staging site.

I cropped the image and also lightened the bottom. If it looks okay, then you can close this issue!

**Comment by shrayshray** [comment]
@reginafcompton Looks good, thanks!
