### ISSUE TITLE
Board Reports: Tags on Reports not working

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#150]
On the Board Reports page, clicking on a tag on a Report returns zero results.

**Comment by shrayshray** [comment]
Also, the copy on the page which shows zero results, e.g.,:
should read, "This site has Board Reports and Agendas from June 2015 to present. If you're searching for something older, you can browse the [Board Archive](http://search3.metro.net/search?access=p&output=xml_no_dtd&site=Board_Archives&ie=UTF-8&client=BoardArchive&proxystylesheet=BoardArchive&proxycustom=%3CHOME/%3E).
We'd be happy to help you find what you're looking for - contact us at boardreport@metro,net!"

**Comment by reginafcompton** [comment]
Both these issues are resolved.

**Comment by shrayshray** [comment]
@reginafcompton There are still issues with tags ... Executive Management Committee, for example. Clicking on either the tag or the filter (which shows 42 reports are available) returns 0 results.
![tagerror](https://user-images.githubusercontent.com/28063988/26844959-f7f2fee8-4aa9-11e7-999e-72f3d15f8651.PNG)

**Comment by reginafcompton** [comment]
This seems to be an issue unique to the Executive Management Committee. Odd. 

Moving it to July issues.

**Comment by reginafcompton** [comment]
@fgregg - The Executive Management Committee does not return results, because the organization name has trailing white space - Haystack cleans this space with "strip" when running a query. This issue can be fixed with a change on the scraper side. 

We could make the change at the LA Metro scraper level:
https://github.com/datamade/scrapers-us-municipal/blob/master/lametro/people.py#L86

Or at the pupa level:
https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/popolo.py#L176

Either would entail calling strip on the organization name....do we want to do this within the organization model? or just when creating an instance of the organization in the LA Metro scraper?

**Comment by fgregg** [comment]
the scraper.

**Comment by camachoo** [comment]
Would it help to change anything on our side?

—

Omar Camacho
Metro Los Angeles
Sr. Manager, Systems Projects, Research & Records Information Management

213.922.2335
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro provides excellence in service and support.

**Comment by camachoo** [comment]
I would like to fix the trailing white space in the database on our side.  That is why I asked.

—

Omar Camacho
Metro Los Angeles
Sr. Manager, Systems Projects, Research & Records Information Management

213.922.2335
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro provides excellence in service and support.

From: Camacho, Omar
Sent: Wednesday, August 16, 2017 1:57 PM
To: 'datamade/la-metro-councilmatic' <reply@reply.github.com>; datamade/la-metro-councilmatic <la-metro-councilmatic@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [datamade/la-metro-councilmatic] Board Reports: Tags on Reports not working (#150)

Would it help to change anything on our side?

—

Omar Camacho
Metro Los Angeles
Sr. Manager, Systems Projects, Research & Records Information Management

213.922.2335
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro provides excellence in service and support.

**Comment by reginafcompton** [comment]
@camachoo, nope. We've got a solution in the works.

**Comment by reginafcompton** [comment]
@camachoo - that's fine, but wait until we get things sorted out in our database. Otherwise, we'll have duplicate entries of the Executive Management Committee.

**Comment by reginafcompton** [comment]
@shrayshray and @camachoo - we've fixed this problem, on our end. You can filter by "Executive Management Committee" on the Board Reports page.

Closing!
