### ISSUE TITLE
Home and Events: Tag when Metro makes a change to an event

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#154]
We will look at the "updated_at" (also "created_at") field for an event. If Metro updates the event within, say, two weeks of the meeting, then the event will get a tag or bold font or something to indicate that the event has been modified. 

@shrayshray Can you let us know the time boundaries for this, e.g., two weeks before an event? or keep the tag for 72 hours after an event gets updated?

**Comment by shrayshray** [comment]
After an agenda is final (i.e., the PDF is available), if there are any changes to it, it should be highlighted in some way and display the text "Updated" next to the date/time.

**Comment by reginafcompton** [comment]
@shrayshray 

Did we reach a consensus on when an event should be highlighted (e.g., if a change is made one, two, three weeks before a meeting)? 

Also: Moving this to June issues.

**Comment by shrayshray** [comment]
@reginafcompton Yes -- it should be highlighted if there is a change to the date or time, or if the meeting is cancelled, after the Agenda is final/PDF is available.

**Comment by reginafcompton** [comment]
To accomplish this we need to do the following:

* add an "updated_at" field in the EventDocument in django-councilmatic: https://github.com/datamade/django-councilmatic
* in the event detail view, add a comparison between the EventDocument updated_at and the Event updated_at

**Comment by reginafcompton** [comment]
@shrayshray - we are wrapping up this issue, today. Here's a screenshot of what to expect, when an event gets updated, after the agenda has been added. 

<img width="936" alt="screen shot 2017-08-16 at 11 57 18 am" src="https://user-images.githubusercontent.com/13078679/29375418-8b3604e0-827a-11e7-9f2b-fa777aa2c362.png">


Quick clarification: This updated tag will only appear for _upcoming events_, not past events. Is that right?

**Comment by shrayshray** [comment]
Perfect, thank you!
