### ISSUE TITLE
Board Report: Enhancement -- Show related files

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#158]
Show list of Related Files on Board Report pages.
![relatedfiles](https://cloud.githubusercontent.com/assets/28063988/26424315/a4172a5c-4085-11e7-855a-89f11c9edd18.png)

**Comment by reginafcompton** [comment]
@shrayshray - it appears that the above related files (2016-0387, 2017-0116) do not exist. 

Can you give us another example of a Board Report with related files?

**Comment by shrayshray** [comment]
@reginafcompton Ah, okay. The related files on that file are not Agenda Ready. The files on 2017-0280 are Agenda Ready, so it would be a good example.
![image](https://user-images.githubusercontent.com/28063988/29590699-f31eef3e-874f-11e7-924b-3f26ed9aa4f2.png)

**Comment by camachoo** [comment]
Found this one.

http://webapi.legistar.com/v1/metro/Matters/4089/Relations

—

Omar Camacho
Metro Los Angeles
Sr. Manager, Systems Projects, Research & Records Information Management

**Comment by reginafcompton** [comment]
@shrayshray - I pushed a solution to the staging site. At the bottom, you can find a table of related board reports, for example (2017-0280): https://lametro.datamade.us/board-report/2017-0280/

Two questions:
Do you want to display this information elsewhere? would you like to see more content in the table (in addition to the board report identifier and title)?

**Comment by shrayshray** [comment]
@reginafcompton This looks great!! As far as other content, I think it would be helpful to show the date and status for the related reports. @camachoo is there anything else you would want to see?

**Comment by reginafcompton** [comment]
@shrayshray - I added the status (shows directly next to the report title) and last action date (given its own column). I also moved the table to the right-hand side, which addresses this issue: https://github.com/datamade/la-metro-councilmatic/issues/209

I pushed these changes to the staging site. One example: https://lametro.datamade.us/board-report/2016-0442/

Let me know, when you'd like to see this deployed on production!

**Comment by shrayshray** [comment]
@reginafcompton Looks great! I did notice one of the related files, 2016-0451, doesn't have a title. Is this a data entry issue on our side?

**Comment by reginafcompton** [comment]
@shrayshray - a small collection of the reports do not have titles, per our discussion in this past issue: https://github.com/datamade/la-metro-councilmatic/issues/128 We can prioritize the mentioned scraper fix for October, if you like.
