### ISSUE TITLE
Home: Permanent solution for concurrent events

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#162]
We implemented a solution to handle three "simultaneously occurring" meetings, i.e., the same body of people meet in the same space, but for three distinct meetings that unfold one-after-the-other.

Related to #153 

We need to find a more effective solution. 

One option: Think about how to re-invent the event scraper, so that it runs every 2-3 minutes during these concurrent sessions; the scraping would determine the current meeting based on if the audio link is active.

**Comment by reginafcompton** [comment]
@shrayshray I just noticed that the concurrent meetings on June 22 include a committee and board meeting. I have the logic set-up to only handle cases, in which you have concurrent **committee** meetings. How do you want to handle a concurrent board and committee meeting? The same as above, or should we favor the board meeting?

**Comment by camachoo** [comment]
Yes, the same.

—

Omar Camacho
Metro Los Angeles
Sr. Manager, Systems Projects, Research & Records Information Management

213.922.2335
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro provides excellence in service and support.

**Comment by camachoo** [comment]
Actually to be more specific.  Show both meetings but make sure that the Regular Board Meeting is on top.

—

Omar Camacho
Metro Los Angeles
Sr. Manager, Systems Projects, Research & Records Information Management

213.922.2335
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro provides excellence in service and support.

**Comment by reginafcompton** [comment]
This will be the display on Thursday. @shrayshray does this look as expected?

<img width="1254" alt="screen shot 2017-06-20 at 5 42 10 pm" src="https://user-images.githubusercontent.com/13078679/27359585-2bd00fa6-55e2-11e7-94c7-918edacc72df.png">

**Comment by shrayshray** [comment]
@reginafcompton Looks great, thank you!!
