### ISSUE TITLE
Increase frequency of scraping and updates

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#163]
Recent changes to our scrapers allow us to scrape la metro and chicago much more frequently without hammering granicus's servers.

So, let's do it for 

the ocd scrapers I recommend doing a daily scrape like 

```bash 
pupa update lametro
```
and 

15 minutes scrapes like

```bash
pupa update lametro events window=0.05
pupa update lametro bills window=0.05
```

This will grab any events and bills that have been update in the past 1/20th of an day (or roughly an hour).

**Comment by hancush** [comment]
I updated the crontab on the server for lametro but not for chicago because it's commented out & @evz mentioned they updated everything so it'll be a monumental scrape when we run it again.

**Comment by reginafcompton** [comment]
We need to do a full scrape for events. I've opened a related issue #165 to account for that.
