### ISSUE TITLE
Board Reports: Filter by Fiscal Year not working

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#181]
On the Board Reports page, "Filter by Fiscal Year" is returning reports which are not from the selected fiscal year.
![image](https://user-images.githubusercontent.com/28063988/28130578-0c325a26-66ec-11e7-93ac-053cd363e699.png)

**Comment by reginafcompton** [comment]
The filters are working as expected. Here's what's going on:

(1) Each bill receives a "legislative session," based on the `MatterIntroDate`, given in the Legistar API. 

For example, [Board Report 2016-0499](https://boardagendas.metro.net/board-report/2016-0499/) has a MatterIntroDate of "2016-06-06": http://webapi.legistar.com/v1/metro/matters/3016. Thus, this board report occurs in the 7/1/2015 to 6/30/2016 fiscal year (i.e., legislative session). 

(2) The date displayed in the search results represents the most recent action item. Again, with Board Report 2016-0499, the most recent action date was in April of 2017.

I think we can do a few things to clarify the search results:

* add explanatory text next to the date saying something, like, "most recent action"
* add a line for "Fiscal year" below or above the last action date - it may look redundant when adding a filter, but I think it could clarify the results.
* show the "Matter Intro Date" in the results and on the bill detail (N.B. This fix would require making updates to the scraper and our data import functionality – so, it's a much more involved change.)

<img width="806" alt="screen shot 2017-09-12 at 11 38 25 am" src="https://user-images.githubusercontent.com/13078679/30337772-f8faaece-97ae-11e7-86f4-7fe9e486dccc.png">

@shrayshray - what would you prefer?

**Comment by shrayshray** [comment]
@reginafcompton let's go with the first option:
•	add explanatory text next to the Board Report date saying "most recent action" similar to mock-up below.
![image](https://user-images.githubusercontent.com/28063988/30876018-222b5b6c-a2aa-11e7-864a-48e49ff7cdca.png)

**Comment by reginafcompton** [comment]
@shrayshray - explanatory text on staging site! https://lametro.datamade.us/search/

**Comment by shrayshray** [comment]
@reginafcompton good to go!
