### ISSUE TITLE
Committees: Adhoc Customer Experience Committee Not Showing

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#183]
The Adhoc Customer Experience Committee is not listed on the committees page: https://boardagendas.metro.net/committees/

The committee was created several weeks ago, but members were just added this morning (just over an hour ago). The committee and members are both showing up on the InSite page: https://metro.legistar.com/DepartmentDetail.aspx?ID=35681&GUID=53802F39-0795-4054-802B-2C237865884B&Search=

**Comment by fgregg** [comment]
We only show committees that have members. Since people and committees change so infrequently, we only update these once a day.

**Comment by shrayshray** [comment]
Got it, thank you. Any idea when the update will go through, or should we just estimate for some time tomorrow?
________________________________

**Comment by fgregg** [comment]
It's up now. The full scrape runs once a day in the evening right now.
