### ISSUE TITLE
Board of Directors: Remove Board member

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#185]
Please remove Phil Washington’s name from the list of board members on the Board of Directors page: https://boardagendas.metro.net/board-members/

**Comment by reginafcompton** [comment]
@shrayshray We can do this. However, I'd like to clarify one detail: it looks like P. Washington is listed on Legistar, but with the title of "Chief Executive Officer": https://metro.legistar.com/DepartmentDetail.aspx?ID=28529&GUID=44319A1A-B2B7-48CC-B857-ADCE9064573B&Mode=MainBody

Is there something particular about the title of "Chief Executive Officer" that we should look out for, i.e., will someone (not just P. Washington) with that title not be considered an official member of the Board?

**Comment by shrayshray** [comment]
Thanks for checking! No, CEO shouldn’t be a flag.
There are a handful of people who serve on committees who are not appointed members of the Board of Directors. Phil Washington is a unique case, as he is the CEO of Metro and is included in all board meetings – Regular, Special and Committees – but he is also not technically a member of the Board of Directors.
So, while I don’t see any future instance of someone with the title of CEO being appointed to the Board of Directors, I also don’t think it’s necessary to make a rule to exclude anyone with that title from being included on the list on the Board page.
