### ISSUE TITLE
Home: Always Display link to Upcoming Meetings

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#186]
Display the link to “View All Upcoming”, even when there are no meetings scheduled within 30 days-60 days to display in the "Upcoming Meetings" section on the home page.

When there are no meetings to display in the "Upcoming Meetings” section on the Home Page, please continue to show the link to “View All Upcoming” on the Events page.

**Comment by reginafcompton** [comment]
_When there are no meetings to display in the "Upcoming Meetings” section on the Home Page, please continue to show the link to “View All Upcoming” on the Events page._

<img width="945" alt="screen shot 2017-08-21 at 2 20 17 pm" src="https://user-images.githubusercontent.com/13078679/29534524-f03e7340-867b-11e7-9db2-fd7636bb69e3.png">

**Comment by reginafcompton** [comment]
@shrayshray - can you confirm that the above interface is what you expected?

**Comment by shrayshray** [comment]
@reginafcompton, yes, exactly!
