### ISSUE TITLE
Missing some previous events

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#187]
The events listing is missing the meeting of 6/22/2017: https://boardagendas.metro.net/events/

The data appears to be in the database. When I run [this code from the django shell](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/views.py#L254-L261) I get what I expect.

(on the server
```bash 
cd /home/datamade/lametro
workon lametro
python manage.py shell
```
```python
>>> from councilmatic_core.models import Event
>>> import datetime
>>> day_grouper = lambda x: (x.start_time.year, x.start_time.month, x.start_time.day)
>>>  past_events = Event.objects.filter(start_time__lt=datetime.datetime.now()).order_by('-start_time')
>>> [(datetime.date(*a),sorted(b, key=lambda x: x.start_time)) for a,b in itertools.groupby(past_events, key=day_grouper)]
[(datetime.date(2017, 7, 20), [<Event: Event object>, <Event: Event object>, <Event: Event object>, <Event: Event object>]), 
 (datetime.date(2017, 7, 19), [<Event: Event object>, <Event: Event object>, <Event: Event object>]), 
 (datetime.date(2017, 6, 22), [<Event: Event object>, <Event: Event object>]), 
... ]
```

I don't see anything in the template code that would filter out the 6/22 event:

https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templates/lametro/events.html#L82-L86

and https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templates/partials/past_event_day.html

**Comment by reginafcompton** [comment]
The Legistar API contains two documents that approve minutes for the 6/22 event: 

http://webapi.legistar.com/v1/metro/matters/4281/texts/5258/
http://webapi.legistar.com/v1/metro/matters/4281/texts/5310

The first version of this document contains an ocr_full_text, while the second version does not. 

Thus, in the later version, ocr_full_text was None, causing in a regular expression within the `get_minutes` filter to crash: https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templatetags/lametro_extras.py#L115

**Comment by reginafcompton** [comment]
@shrayshray - see above for explanation of the problem. This fix is now deployed!
