### ISSUE TITLE
Board Reports: Logic for Status

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#192]
Please review logic for show status tags are applied to Board Reports.
![statustags](https://user-images.githubusercontent.com/28063988/28851697-3f779020-76d9-11e7-8cba-7f8f4e9e54df.png)

**Comment by reginafcompton** [comment]
Next step: DataMade will summarize current logic

**Comment by reginafcompton** [comment]
Current logic:

Each **board report action** has a "description." The description comes from the `MatterHistoryActionName` in the Legistar API. 

For example, we get the action and its description for [Board Report 2017-0298](https://boardagendas.metro.net/board-report/2017-0298/) from this page in Legistar (you can see that the MatterHistoryActionName for this action is "APPROVED": http://webapi.legistar.com/v1/metro/matters/4107/histories

In Councilmatic, we look at the description of the most recent action of a board report to determine its status tag, as follows:
'APPROVED' => 'Approved'
'ADOPTED' => 'Adopted'
'RECOMMENDED', 'DISCUSSED', 'REFERRED', 'FORWARDED' => 'Active'
'WITHDRAWN => 'Withdrawn'

We do not assign status tags to board reports that have one of the following "types":
* 'informational report'
* 'public hearing'
* 'appointment'
* 'oral report / presentation'

**Comment by shrayshray** [comment]
@reginafcompton we do want to modify the logic slightly, but are still reviewing statuses/actions in the system ... will follow up soon.

**Comment by reginafcompton** [comment]
Thanks for the update, @shrayshray

**Comment by shrayshray** [comment]
@reginafcompton Below are updates on how we would like Actions relate to status tags.

Status tag: 'Approved'
Action/s: 'APPROVED', ‘APPROVED AS AMENDED’, ‘APPROVED THE CONSENT CALENDAR’
Tag color: Green

Status tag: 'Adopted'
Action/s: 'ADOPTED', ‘ADOPTED AS AMENDED’
Tag color: Green

Status tag: 'Active'
Action/s: 'RECOMMENDED FOR APPROVAL’, ‘RECOMMENDED FOR APPROVAL AS AMENDED’, 'REFERRED', 'FORWARDED DUE TO ABSENCES AND CONFLICTS’, ‘FORWARDED WITHOUT RECOMMENDATION', ‘NO ACTION TAKEN’, ‘NOT DISCUSSED’
Tag color: Yellow

Status tag: 'Received'
Action/s: 'RECEIVED', ‘RECEIVED AND FILED’
Tag color: Green

Status tag: 'Failed' 
Action/s: 'FAILED'
Tag color: Red

Status tag: 'Withdrawn'
Action/s: 'WITHDRAWN'
Tag color: Red

**Comment by reginafcompton** [comment]
@shrayshray - I've implemented this new logic. You can see the changes on the staging site: https://lametro.datamade.us/search/

Let me know when you'd like this deployed to production.

**Comment by camachoo** [comment]
Status tag: 'Received' should apply to informational reports & oral report / presentation actions.

**Comment by shrayshray** [comment]
@reginafcompton it seems like there are too many items with status of “Adopted” (this should really only apply to resolutions), so we’re confirming on our side this is accurate before deploying.

**Comment by reginafcompton** [comment]
@camachoo got it! I've included those board report types, so the number of "Received" statues has increased. Let me know if this looks accurate.

**Comment by shrayshray** [comment]
@reginafcompton Good to go!
