### ISSUE TITLE
decide what kind of legislation feed (if any) to include on person detail page

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#20]
legislative items (in most cases) don't appear to be sponsored by people but rather by the board/committees. i wrote [a property in lametroperson](https://github.com/datamade/la-metro-councilmatic/blob/boardmemberpage/lametro/models.py#L126) that gathers recent activity from committees to which the person belongs, with the option to omit board-sponsored items, as they are common to all board members/not that useful (?) to include on each member page. the problem: committees don't do much, and many are ad hoc/inactive, so when you omit items sponsored by the board, recent activity is not that recent. let's chat when i get back friday about what will be most useful to users, i'll implement it (and adjust the template, too), and we can merge my branch back into master.

**Comment by reginafcompton** [comment]
I think we have a good solution for this, i.e., "legislation sponsored by committees to which {{ person.name }} belongs."
