### ISSUE TITLE
Questions for LA Metro

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#22]
List of questions for LA Metro:
- Is "Legislation" the correct word?
- Committees, but not individual board members sponsor legislation. How do we want to deal with this? Related to #20 
- Board Members seem to have overlapping administrative districts/geographies. We removed the maps. Is this the way to go? Related to #7 and #6
- Can we get some content for the About page and also descriptions of the various committees? Related to #18 and #15
- What should we use as the icon?
- What should we do for Board Member head shots? Related to #11

**Comment by reginafcompton** [comment]
@hancush: Add your questions, and @derekeder will send LA Metro an email.

**Comment by fgregg** [comment]
* What does it mean for a committe to "sponsor" a piece of legislation, do they mean it was referred by the committee to the whole board.

**Comment by fgregg** [comment]
@reginafcompton Do we have the answers for these questions anywhere?

**Comment by reginafcompton** [comment]
We have answers to all these, except "legislation" as a term. We can touch base with LA Metro folks about this.
