### ISSUE TITLE
Home/Meetings: Meeting listed twice

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#222]
@reginafcompton On the Home page and Meetings page, Ad-Hoc Customer Experience Committee meeting is showing up twice.
I noticed this because I went to check whether the meeting was showing up as cancelled yet ... It was cancelled in Legistar earlier (I don't think it's been quite an hour, but just wanted to keep an eye on it to see when the update showed). So just FYI, whichever of the two meetings is supposed to be there is also supposed to be cancelled.
 ![image](https://user-images.githubusercontent.com/28063988/31295500-9e4aa518-aa93-11e7-8284-2d80564828ae.png)

**Comment by reginafcompton** [comment]
@shrayshray it's been about an hour: I'll manually remove this extra meeting. 

This duplicate comes as a result of this issue, which we are still strategizing about: https://github.com/opencivicdata/pupa/issues/295

**Comment by reginafcompton** [comment]
It's fixed: https://boardagendas.metro.net/events/
