### ISSUE TITLE
Ad-Hoc Cust. Exp. Committee: Name mispelled

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#229]
@reginafcompton Tafarai Bayne is listed twice on this page https://boardagendas.metro.net/committee/ad-hoc-customer-experience-committee-920133c6cc7b/ In the second instance, his name is misspelled. 

Please remove the one that’s spelled wrong (Tafari Bayne).

**Comment by reginafcompton** [comment]
Duplicate removed! (I'll also move this to October to consolidate our records.)
