### ISSUE TITLE
Home: "Listen Live" button link

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#238]
On the "Listen Live" button that shows on the Home page during meetings, we currently use a general link to the media player. The Board Chair has mentioned there's an issue with this because the general media player shows video streaming suggestions instead of the meeting Agenda, and this has caused concern from the public.
Example:
![ex1](https://user-images.githubusercontent.com/28063988/32865600-a4ef0162-ca18-11e7-99ae-0edb7401207b.jpg)
Omar may have found a solution. If it sounds feasible to you to implement it, we'd like to make it a high priority. 
Possible solution:
It looks like the live meeting link from InSite uses the GUID for the meeting in the player. We can get this from the API as shown below and generate the link that would be used for each meeting.  

System and safety GUID: B0A322B8-71C3-4197-8719-E9C3E8980D95
9 AM
http://metro.granicus.com/mediaplayer.php?event_id= B0A322B8-71C3-4197-8719-E9C3E8980D95

Construction GUID: 985A2FD9-06D6-4EB0-A384-27779F62AE01
10:15 AM
http://metro.granicus.com/mediaplayer.php?event_id=985A2FD9-06D6-4EB0-A384-27779F62AE01

Executive Management GUID: 3DEE4755-B576-4BCD-93BE-39FB381BAF81
11:30 AM
http://metro.granicus.com/mediaplayer.php?event_id=3DEE4755-B576-4BCD-93BE-39FB381BAF81

Examples:
 ![ex2](https://user-images.githubusercontent.com/28063988/32865821-b4e6bea6-ca19-11e7-9119-51ca23c0edfc.png)
![ex3](https://user-images.githubusercontent.com/28063988/32865855-cb38c7f8-ca19-11e7-92ef-77ee0719a895.png)

**Comment by reginafcompton** [comment]
@shrayshray - this seems like a possible solution. We'll need to build out the functionality to scrape/import the GUID (which we currently do not do). Otherwise, adding the link itself should not be a heavy task. As you suggest, we'll make this issue top priority for November.

**Comment by reginafcompton** [comment]
@shrayshray, we have code ready to implement this enhancement. A couple questions:

(1) Is there any chance that a current event will _not_ point to one of these custom-built links? For instance, five minutes before a meeting, when the "current meeting" view shows, will those meetings have appropriate links? I am concerned that, instead, the user might see something like this: http://metro.granicus.com/mediaplayer.php?event_id=AC0C87D8-4C4C-4006-A3F1-5CC2AB7A8675 

If so, then we can show the generic link, until the custom link returns what we expect. Does that seem like a reasonable solution for you?

(2) I'd like you to see this enhancement before we deploy it to production. I can hardcode some "current events" on the staging server, and you and Omar can take a look. Is there a good day and time when we can test this? Any time on Monday should work for me.

**Comment by shrayshray** [comment]
@reginafcompton 
(1) There is always a chance for something unexpected :) -- I think it makes a lot of sense to do what you suggest, and show the generic link until the custom link returns what is expected. It makes sense to also use the generic link when there are multiple meetings scheduled for the same time slot, like there were this morning.
(2) Sounds good! How about 11am PT/1pm CT on Monday?

**Comment by reginafcompton** [comment]
@shrayshray sure, we can do 11am PT/1pm CT on Monday. Basically, I'll hardcode some current events, and then, you can see if it's what you expect. I'll have something up at 11am your time, and I'll send an email to confirm, too. 

I'll use the generic link for multiple events, as you suggest.

**Comment by reginafcompton** [comment]
Closed by #239
