### ISSUE TITLE
Customize error page

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#245]
Is it possible to customize the error page displayed when there are issues with the site? We'd like to display a custom message and link to metro.legistar.com (see mockup below).
![errorpage](https://user-images.githubusercontent.com/28063988/33459745-10fb336c-d5e0-11e7-8665-6e989b3c4c08.png)

**Comment by reginafcompton** [comment]
@shrayshray yes, this should not be a problem.
