### ISSUE TITLE
Events: Missing Listen Links

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#246]
The "Listen" links are missing from last weeks meetings (see screenshot). The recordings were added to the meetings last week, and links are showing up on metro.legistar.com. @reginafcompton could you look into this?
![missinglistenlinks](https://user-images.githubusercontent.com/28063988/33567449-153a6448-d8d8-11e7-9a30-48a1a47392d6.png)

**Comment by shrayshray** [comment]
@reginafcompton The "Listen" links are still missing from the two meetings on 11/30/2017: https://boardagendas.metro.net/events/
Could you please check to see what the issue is?

**Comment by reginafcompton** [comment]
@shrayshray, yes, I can take a look this afternoon. I'll put this issue in the December milestone, too.

**Comment by reginafcompton** [comment]
Closing - we had a blip in the data import process and missed these media links. Links are present now.
