### ISSUE TITLE
Reports: Mysterious Missing Report 2016-0571

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#253]
This report is missing from boardagendas.metro.net: https://metro.legistar.com/LegislationDetail.aspx?ID=2832704&GUID=346BF2BF-61CD-4648-9B81-4AD9CC10104A

I can't find it by searching for it's File ID, or subject text, on boardagendas. And it's not linked on the meeting pages for meetings when it appeared on the Agenda:
https://boardagendas.metro.net/event/planning-and-programming-committee-59cf4b8481ef/
https://boardagendas.metro.net/event/regular-board-meeting-35199240b6df/

Any idea why?

**Comment by reginafcompton** [comment]
The Legsitar API has an entry for this report: http://webapi.legistar.com/v1/metro/matters/3365 However, the report does not appear in the OCD API, which indicates that the scraper missed it. 

Queries to check the OCD API:
https://ocd.datamade.us/bills/?identifier=2016-0571
https://ocd.datamade.us/bills/?title__contains=a%20four-year%20firm%20fixed%20price%20Contract%20No.%20AE5999300%20to%20Parsons%20Brinckerhoff,%20Inc.

First, we'll need to determine why this bill did not get added to the OCD API database. With a solution to that, we can then add it, scrape it, and import it.

**Comment by shrayshray** [comment]
Another instance of this issue (and a few more details/questions): The missing report is 2017-0803. This was discovered when a search for "donation policy" on metro.legistar.com (1) produced different results than the same search on the Councilmatic website (2).
1. 
![1](https://user-images.githubusercontent.com/28063988/36170148-65efdc20-10b3-11e8-9576-3e687e3aff9f.jpg)
2. Reports in search results will repeat the file id many times.
![2](https://user-images.githubusercontent.com/28063988/36170195-9364cba2-10b3-11e8-8baf-17e9f01177ce.jpg)
3. Titles are still missing on some reports.
![3](https://user-images.githubusercontent.com/28063988/36170221-a339909e-10b3-11e8-9b21-ffb187ef44ba.jpg)

4. Is this what we are using to get the matter text to search from? Api call for matter text I get the following for 2017-0657 (matterID: 4462): http://webapi.legistar.com/v1/metro/matters/4462/texts/5478

**Comment by reginafcompton** [comment]
I'll start answering your questions, in turn:

(1) The report is in the Councilmatic database: https://boardagendas.metro.net/board-report/2017-0803/ I rebuilt the index for our search engine this morning, and the bill now appears in search results for "donation policy." (As a note, we power our search engine with different tools than Legistar: sometimes the results will - and should be - different.)

(2) Ah, okay! We can customize how our search engine returns results. Here, it returns all instances of the bill identifier that it finds in the index - hence all the duplicates. I think we can open a separate issue.

**Comment by reginafcompton** [comment]
I have relevant issues opened for the various bits of this conversation. (Plus, closing issue #256 will help prevent these mysterious missing bills, in the first place.) Closing this issue in favor of #258 and #237
