### ISSUE TITLE
Duplicate identifiers in search results

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#258]
This does not look so great:

<img width="701" alt="screen shot 2018-02-14 at 12 09 45 pm" src="https://user-images.githubusercontent.com/13078679/36220388-ffdc9202-117f-11e8-8ed2-6d5856d9668c.png">

Change the template partial that generates this: https://github.com/datamade/django-councilmatic/blob/93e96ecf1f411c23a31e46bf7aa814db5eda3611/councilmatic_core/templates/partials/search_result.html

**Comment by hancush** [comment]
This fix is live on the staging site and will make it to production when we next deploy (scheduled for tomorrow).
