### ISSUE TITLE
Home: Message about browser compatibility

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#264]
Metro's ITS has users on an outdated version of IE in which the search bar at the top of boardagendas.metro.net does not show up. Can we add a message when a user visits the page in  older versions of IE which reads something like "This version of Internet Explorer may limit the functionality of this website. It's recommended you update your version of Internet Explorer, or use a compatible browser, such as Google Chrome."

**Comment by hancush** [comment]
Hello, @shrayshray! Do you know offhand what version of IE they're using? Thanks!

**Comment by shrayshray** [comment]
Hi, @hancush! It’s IE 10.

**Comment by hancush** [comment]
@shrayshray We've deployed a fix that should display a warning message to users of Internet Explorer 10 and below. Is this warning visible to the users you mentioned when opening this issue?

**Comment by hancush** [comment]
Good morning, @shrayshray! Any update on this?

**Comment by shrayshray** [comment]
Hi, @hancush. Sorry for the delay! I am out of the office today but will check on this tomorrow AM.

________________________________

**Comment by shrayshray** [comment]
@hancush this looks great, thank you!!

**Comment by hancush** [comment]
Awesome, thanks for checking, @shrayshray! :-) I'll close this.
