### ISSUE TITLE
Simultaneous event scrapers running

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#268]
Today, three event scrapers were running concurrently, which caused a significant delay for importing data to Councilmatic. I killed each process and then reran the events scraper. 

`flock` should prevent this from happening. So, the questions we need to answer:

(1) why did flock not lock the designated file as expected?
(2) what time did the scrapers start (see lametro.log on ocd server)? at what point does it seem they started to overlap?

**Comment by hancush** [comment]
Note to self: Close this once #257 is switched on.
