### ISSUE TITLE
Finesse mobile view for Current Meeting

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#273]
The mobile view does not look terrific. Let's hide the text on the buttons (i.e., only show icons) and think about changing or hiding the photo.

<img width="390" alt="screen shot 2018-03-14 at 1 58 35 pm" src="https://user-images.githubusercontent.com/13078679/37425082-2747950a-2790-11e8-905e-5373170a56b2.png">

**Comment by camachoo** [comment]
In the mobile view, can we spread the button real estate to include the area under the picture? Example below:

Picture

Meeting info

Button real estate



—

Omar Camacho
Metro Los Angeles
Sr. Manager, Systems Projects, Research & Records Information Management

213.922.2335
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro provides excellence in service and support.

**Comment by reginafcompton** [comment]
That's a nice idea - I'll put something together. Should we include this in the March milestone?

**Comment by shrayshray** [comment]
@reginafcompton If you think there is time to accomplish this in March, then yes, let's add to March milestones.

**Comment by reginafcompton** [comment]
<img width="397" alt="37996920-faf6c7e2-31de-11e8-9f43-252f89085740" src="https://user-images.githubusercontent.com/13078679/38097114-1c77b83e-333a-11e8-9efc-9eee1bc6fa97.png">

Closing!
