### ISSUE TITLE
Board Reports: Markup language showing in search results

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#290]
For some search results, what looks like markup language is showing up in the subject. Could you please look into this? Below are two examples.
![boardreports-searchresults-markup](https://user-images.githubusercontent.com/28063988/39021890-ca13199e-43e7-11e8-8514-607ac379a7af.png)
![boardreports-searchresults-markup2](https://user-images.githubusercontent.com/28063988/39021893-cc413250-43e7-11e8-9439-9cc72fdd8b59.PNG)

**Comment by shrayshray** [comment]
It appears this was resolved ... I tried the same searches above and returned a clean list of results. @reginafcompton , can you confirm?

**Comment by reginafcompton** [comment]
Yes @shrayshray - achieved by [_not_ indexing the `full_text` field (i.e., the field with the RTF and HTML)](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templates/search/indexes/councilmatic_core/bill_text.txt)
