### ISSUE TITLE
align audio links horizontally, rather than stacking vertically

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#308]
<img width="1026" alt="screen shot 2018-05-25 at 3 37 39 pm" src="https://user-images.githubusercontent.com/12176173/40565300-9547ce9c-6031-11e8-94d1-6055ff1044ea.png">

**Comment by shrayshray** [comment]
Alternative: maybe just a fine line between events items on the list, to break them up visually.

**Comment by shrayshray** [comment]
@jmithani perfect, thank you! Please deploy.
