### ISSUE TITLE
Board Reports: Rank search results by relevancy

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#309]
Search results are currently ranked by date, with most recent first. We'd like them to be ranked by relevancy first, instead, and indicate this to the user like this:
![image](https://user-images.githubusercontent.com/28063988/41067420-62f93ca6-699a-11e8-8844-277bff02e7ae.png)

**Comment by reginafcompton** [comment]
@shrayshray - I implemented a change for this...here's what to expect: 
- all results (without a search term) are sorted by date. 
- after entering a search term, the results are sorted by relevancy - indicated with "Relevance" in **bold**
- the user can toggle between date (ascending, descending), title (ascending, descending), and relevance (from most to least relevant - I don't think an ascending/descending filter makes sense here).

![metro_search](https://user-images.githubusercontent.com/13078679/43145607-3f292cea-8f25-11e8-9aca-2320ba06c7cc.gif)

Let me know if you'd to deploy this change to staging or, if it seems fine, to production.

**Comment by reginafcompton** [comment]
@shrayshray - it's deployed to staging! Let me know if the change resolves this issue.

**Comment by reginafcompton** [comment]
@shrayshray - did you get a chance to look at the staging site? https://lametro.datamade.us/search/

**Comment by shrayshray** [comment]
@reginafcompton it looks like there are a couple issues ...
Sort by date -- See screenshot. It looks like a bunch of results don't have an agenda date showing in the results listing, but there is an agenda date on the report itself. 
![image](https://user-images.githubusercontent.com/28063988/43476676-03cbc5fc-94ae-11e8-8f5d-9c6de6e7c92c.png)
Sort by title - In A-Z, "10 Years ..." and other number titles shows up after a set of alphabetical results. In Z-A, "Zero emissions ..." doesn't show up until page 2.
![image](https://user-images.githubusercontent.com/28063988/43476862-80d67470-94ae-11e8-97dd-737955cf4c1c.png)

**Comment by reginafcompton** [comment]
@shrayshray - the staging site shows fixes for these issues (with some exception, discussed in issue #340). Let me know how it looks.

**Comment by shrayshray** [comment]
@reginafcompton Looks great!

**Comment by reginafcompton** [comment]
Terrific! It's deployed to production. Closing.
