### ISSUE TITLE
board of directors are vacant

### ISSUE THREAD

**Issue by derekeder** [datamade/la-metro-councilmatic#31]
No names or links to pages are on the board of directors page: https://lametro.datamade.us/board-members/

<img width="836" alt="screen shot 2016-10-21 at 4 55 02 pm" src="https://cloud.githubusercontent.com/assets/919583/19612957/3ace73e0-97af-11e6-950b-604a5cfbd6b2.png">

**Comment by hancush** [comment]
should werk now 
![screen shot 2016-10-24 at 9 53 16 am](https://cloud.githubusercontent.com/assets/12176173/19650673/b9d8d5d2-99cf-11e6-809f-c73e49368428.png)
