### ISSUE TITLE
scrape missed location change of special board meeting: June 15, 2018

### ISSUE THREAD

**Issue by derekeder** [datamade/la-metro-councilmatic#310]
from @fgregg:

The location for a special board meeting was changed by LA Metro staff at around June 15, 4:42 PM, Chicago time. Within 30 minutes, these changes were not showing up on https://boardagendas.metro.net/event/special-board-meeting-0fe4529b3dfd/

In the [Legistar API](http://webapi.legistar.com/v1/metro/events/1365), the last modified event field was June 13: `<EventLastModifiedUtc>2018-06-13T23:52:23.45</EventLastModifiedUtc>`

Every 15 minutes, a scraper checks the API for events modified in the last 72 minutes. Since the API said this event had been last changed two days previously, it did not pick up this change to the event. It would have been caught by our nightly, comprehensive scrape. 

The ideal place to fix this is the underlying data system from Granicus.

Since we cannot control system, we can mitigate these source of source system data errors by increasingly how aggressively we scrape. Perhaps on Fridays, we can do a comprehensive fast scrape of events every 20 minutes. This mitigation may reduce system performance of the Legistar system.

**Comment by fgregg** [comment]
This is needs consultation with the client.

**Comment by reginafcompton** [comment]
Handled with: https://github.com/datamade/scrapers-us-municipal/pull/22
