### ISSUE TITLE
missing board reports: June 16, 2018

### ISSUE THREAD

**Issue by derekeder** [datamade/la-metro-councilmatic#311]
From @fgregg:

For at least one meeting, not all associated board reports were showing in the Agenda view.

The underlying reasons was that the associated bills of those agenda items were missing from both OCD and the councilmatic server. When I reran the scraper with a window of 90 days, 31 bills got added, some of them introduced over a month ago.

Migitation: When the pupa scraper imports events it raises a warning if pupa is unable resolve a bill referened in an event to a bill object. These warnings could be sent to sentry, but we currently have settings to ignore these warnings. Most of these warnings are due to bad data entry in the source system, and are not indicative of a problem with scraping. However, sometimes, as in this case we are. We should turn on the logging of these messages and then suppress known warnings that are not of concern.

We have an update that we will deploy to address this.

**Comment by fgregg** [comment]
This has been resolved.
