### ISSUE TITLE
About/Board Reports - Change name of Report Type

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#312]
The Board Report type called "Ordinance" is changing to "Ordinance / Administrative Code". Can you please update the term on the About page, and make sure it will be included in the filters for Report Type?
![about-ordinance](https://user-images.githubusercontent.com/28063988/41749324-968c4316-756a-11e8-87f1-0941f4c5623c.PNG)

**Comment by reginafcompton** [comment]
Closing! https://boardagendas.metro.net/about/#about-la-metro
