### ISSUE TITLE
Committees: Committees with no current members are listed

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#314]
On the Committees page (https://boardagendas.metro.net/committees/) two committees which are no longer active are still showing up on the list, several days after being updated.
Ac Hoc Sustainability has no active members listed in Legistar, but it's showing up _twice_.
System Safety, Security and Operations also has no active members, but is still listed (and shows 7 members).
![committees](https://user-images.githubusercontent.com/28063988/42336737-6d0a65d4-8039-11e8-8b84-aabcc81be33a.PNG)

**Comment by reginafcompton** [comment]
@shrayshray - can you confirm that members _were added and later deleted_ to the System Safety, Security and Operations Committee? If so, then this issue relates to https://github.com/opencivicdata/pupa/issues/295, and DataMade will need to carefully delete the extraneous memberships from our data source (see below screenshot). 

**Screenshot of OCD API: It contains memberships for System Safety Committee dating through 2019**
<img width="674" alt="screen shot 2018-07-09 at 9 31 46 am" src="https://user-images.githubusercontent.com/13078679/42456679-1bbba0f6-835b-11e8-86e8-f04d69fa2569.png">

**Comment by reginafcompton** [comment]
For the Ad-Hoc Sustainability Committee, we have Phil Washington's membership ending in 2020 (see below screenshot). Let's determine how that happened.

<img width="557" alt="screen shot 2018-07-09 at 9 37 44 am" src="https://user-images.githubusercontent.com/13078679/42456973-cba37d7c-835b-11e8-9ded-ad07742af435.png">

**Comment by shrayshray** [comment]
@reginafcompton Phil Washington's membership was originally set to end in 2020, but because the meeting is on hiatus, I changed it to end 6/30/18. I made the change 7/3/18.

**Comment by shrayshray** [comment]
@reginafcompton re: "can you confirm that Metro added and later deleted members to the System Safety, Security and Operations Committee?"
Yes. I added new members before finding out the committee name was going to be changed, then deleted them and added them to the new committee.

**Comment by reginafcompton** [comment]
Steps used to remove the inaccurate memberships from Safety, Security and Operations Committee:
- [ ] Turn off cron

- [ ] **Delete memberships from OCD API database: Execute the following in an api.opencivicdata.org shell**
```
from opencivicdata.core.models import Membership

people = ['ocd-person/7458da90-f5da-465f-8246-00ef9b2a3527', 'ocd-person/c1be7315-f376-4092-b6ca-b1533a264870', 'ocd-person/dbc51fa2-6e20-4a00-b099-851703b7b19d', 'ocd-person/31afabe2-7e96-4394-9a32-f9f830cb255d', 'ocd-person/6b9fb5e9-b1ea-4615-b538-3d501fbcf51c', 'ocd-person/912c8ddf-8d04-4f7f-847d-2daf84e096e2', 'ocd-person/75cce355-15b7-46fd-880e-af5a8ab39aad']

memberships = Membership.objects.filter(person_id__in=people, organization_id='ocd-organization/89c32d8d-5bc1-4cd8-9316-3f0031984ba5',end_date__in=['2019-06-30', '2020-06-30'])

[membership.delete() for membership in memberships]
```

- [ ] **Delete the memberships from Councilmatic downloads on the server**

```
rm -rf downloads/people/*
```

- [ ] **Delete the memberships from Councilmatic database: Execute the following in an la-metro-councilmatic shell**

```
from councilmatic_core.models import Membership

people = ['ocd-person/7458da90-f5da-465f-8246-00ef9b2a3527', 'ocd-person/c1be7315-f376-4092-b6ca-b1533a264870', 'ocd-person/dbc51fa2-6e20-4a00-b099-851703b7b19d', 'ocd-person/31afabe2-7e96-4394-9a32-f9f830cb255d', 'ocd-person/6b9fb5e9-b1ea-4615-b538-3d501fbcf51c', 'ocd-person/912c8ddf-8d04-4f7f-847d-2daf84e096e2', 'ocd-person/75cce355-15b7-46fd-880e-af5a8ab39aad']

memberships = Membership.objects.filter(_person_id__in=people, _organization_id='ocd-organization/89c32d8d-5bc1-4cd8-9316-3f0031984ba5',end_date__in=['2019-06-30', '2020-06-30'])

[membership.delete() for membership in memberships]
```

- [ ] Turn on cron

**Comment by reginafcompton** [comment]
@shrayshray - this issue should be handled with the exception of Phil Washington's membership. I opened a separate issue for that: https://github.com/datamade/la-metro-councilmatic/issues/318 I'll take a look at it first thing tomorrow morning.

Closing this issue!
