### ISSUE TITLE
Meetings: New System Safety Committee to replace "System Safety, Security and Operations"

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#315]
As of 7/1/2018, the "System Safety, Security and Operations" committee is no longer, and is replaced by the new committee, "Operations, Safety, and Customer Experience".

"System Safety, Security and Operations" has no current members and no future events in Legistar, and is no longer listed on https://metro.legistar.com/Calendar.aspx
But it's still showing up on https://boardagendas.metro.net/events/ 

Additionally, "Operations, Safety, and Customer Experience" is scheduled to meet each month in Legistar and is listed on https://metro.legistar.com/Calendar.aspx
But it's only listed for July on https://boardagendas.metro.net/events/ and not for future months. 
![image](https://user-images.githubusercontent.com/28063988/42350565-e4245fa4-8065-11e8-9550-274bfa6d8f83.png)

**Comment by reginafcompton** [comment]
@shrayshray 
I removed the "System Safety, Security and Operations" meetings from July onward.
I also see that the "Operations, Safety, and Customer Experience Committee" meetings have populated where expected.

Can you confirm that the events page looks as you expect?

**Comment by shrayshray** [comment]
@reginafcompton Yes! Looks as expected -- Thank you!

**Comment by reginafcompton** [comment]
Great - closing!
