### ISSUE TITLE
Board Members: Add Shirley Choate 7/14

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#327]
On July 13th, Carrie Bowen's term on the Metro Board will end. On July 14th, Shirley Choate will replace her.
I made this change in Legistar, but the [Board Members webpage](https://boardagendas.metro.net/board-members/) will need to be updated to remove Carrie Bowen and add Shirley Choate. I'll post her bio as soon as I get it, but in the meantime, here is her info and photo:

Role: Non-Voting Board Member
Title: Acting Caltrans District 7 Director, Appointed by the Governor of California
![shirley-choate-8x10-300dpi](https://user-images.githubusercontent.com/28063988/42708402-0d2edc9e-8692-11e8-84d7-39f305783fbc.jpg)

**Comment by reginafcompton** [comment]
@shrayshray - I do not see Shirley listed on Legistar:

http://webapi.legistar.com/v1/metro/persons
https://metro.legistar.com/People.aspx

Can you look into this?

**Comment by shrayshray** [comment]
@reginafcompton In Legistar, she's assigned to start as a committee member 7/14/18, so she won't be listed until tomorrow. But I thought the Board Members section of the website was updated manually? 
If you have to wait til she's officially in service in Legistar, no problem.

**Comment by reginafcompton** [comment]
@shrayshray got it! We'll need to wait until she appears in Legistar. We *do* scrape person data, but add the bio and photo manually.

**Comment by shrayshray** [comment]
@reginafcompton got it, thanks! And here's her bio: 
"As Acting Caltrans District 7 Director, Shirley Choate is responsible for assisting the District Director in ensuring the sustainability and livability of the State Highway system in Los Angeles and Ventura counties. Through planning, construction, operation and maintenance, she helps facilitate the movement of people, goods and services in a safe and efficient manner. Shirley is also responsible for the oversight of internal operations which includes 2,700 employees in the divisions of Administration, Construction, Design, Environmental Planning and Engineering, External Affairs, Maintenance, Operations, Planning, Programming/Project Management and Right of Way.
Shirley is championing innovation in policies and practices for the District and its employees. She is also developing strong, collaborative partnerships with local and regional agencies that will enhance the District’s economy and livability.
Shirley has worked for Caltrans for over 35 years. She has spent 18 of those years as the Deputy District Director for Districts 2 and 7. She has also taken on the role of acting Division Chief for Transportation Planning and acting Assistant Division Chief of Construction. Her extensive civil service experience includes the planning, designing and construction of hundreds of transportation projects worth over $4 billion. She oversees more than $475 million in personnel and operating expenses.
Her performance-based approach has significantly improved the delivery of capital outlay commitments and, under her leadership, the program was awarded the 2006 Caltrans Capital Delivery Award for “Best Overall Delivery” and the 2008 Caltrans “Best Overall Project Management” award.
Shirley graduated from UC Berkeley with a BS in Civil Engineering in 1982 and received a Master’s Certificate in Project Management from The George Washington University-School of Business and Public Management in 2002. She is a registered Civil Engineer (Professional Engineer or P.E.) in the State of California as well as a certified Project Management Professional (P.M.P.)."

**Comment by reginafcompton** [comment]
@shrayshray - could you clarify Choate's role? It describes her as both "Acting Caltrans District 7 Director" and an "Appointee of the Governor of California". Is District 7 one of the districts to be represented on the map? Or should Choate follow Carrie Bowen, who did not have a geographic assignment?

**Comment by shrayshray** [comment]
@reginafcompton Choate should follow Carrie Bowen as far as representation on the map. District 7 is the entire County of Los Angeles. Her title should include both items, ""Acting Caltrans District 7 Director, Appointee of the Governor of California".

**Comment by reginafcompton** [comment]
Closing in favor of https://github.com/datamade/la-metro-councilmatic/issues/336
