### ISSUE TITLE
Edit the ABOUT page. 

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#33]
I see at least one instance of the word "Chicago" on the ABOUT page. Check for and remove "Chicago" elsewhere.

**Comment by hancush** [comment]
chicago no more (on about page, anyway) :wave: 

(i don't see it [anywhere else except in comments](https://github.com/datamade/la-metro-councilmatic/search?utf8=%E2%9C%93&q=chicago) but we should keep an eye out)
