### ISSUE TITLE
"Acting" should appear next to Shirley Choate's post

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#336]
Shirley Choate holds the Metro post "Caltrans District 7 Director, Appointee of Governor of California", though she is the "Acting Caltrans District 7 Director" (on behalf of Carrie Bowen). 

We should handle this by adding some information to the "extras" field in the scraper, and then, importing and rendering it appropriately.

**Comment by shrayshray** [comment]
Correcting Shirley Choate's title ASAP is high priority; but would it be possible to add the ability for Metro to make these type of changes via the Content Management System referenced in Issue #265 for future updates?

**Comment by reginafcompton** [comment]
Here's the plan:
1. Assign a value to the extras field when getting [Post](https://github.com/opencivicdata/pupa/blob/c0dbe820821caa66f1cb02675dfdcd3df22307b7/pupa/scrape/schemas/post.py) objects [in the scraper](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/lametro/people.py#L77) – this value might be `extras = {"title-prefix": "Acting"}`
2. Add an extras JSONfield to the [Post object](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/models.py#L599) in Councilmatic. 
3. Get the extras in [`import_data`](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L731) when importing posts
4. Filter for extras when displaying a the post of a person: committees page, committee detail pages, and person/people pages.

**Comment by reginafcompton** [comment]
@shrayshray - you can see a fix for this on the staging site. I'll deploy it to production in the morning, unless you see a reason not to.

This type of change should not be handled by the CMS. It seems very simple, I know! However, if we want to maintain the paradigm of the OpenCivicData standard, then the Councilmatic site should not change a board member's post, title, or role, without that change being accurately reflected in the OCD API. As you can see, the change for this originates pretty far upstream, i.e., by populating the `extras` field in the membership model, but that insures that the data exists consistently and correctly in all places. 

Handled by https://github.com/datamade/la-metro-councilmatic/pull/352
