### ISSUE TITLE
Board Reports do not have histories

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#340]
Several board reports do not have histories in the Legistar API. A couple examples:

https://boardagendas.metro.net/board-report/2015-1765/
http://webapi.legistar.com/v1/metro/matters/2758/histories

https://boardagendas.metro.net/board-report/2018-0251/
http://webapi.legistar.com/v1/metro/matters/4982/histories

(As opposed to: https://boardagendas.metro.net/board-report/2017-0686/ and http://webapi.legistar.com/v1/metro/matters/4491/histories) 

The [scraper creates `actions` based on the histories](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/bills.py#L290), and without actions, [the search results do not sort properly by date](https://github.com/datamade/la-metro-councilmatic/issues/309#issuecomment-409307419).

Metro staff need to investigate if these reports _should_ have histories, and if they should, _why_ the Legistar API does not include them.

**Comment by shrayshray** [comment]
These reports do not have histories assigned in Legistar. There's an effort to go back and assign histories, but I'm not sure what the timeline is for completing it. 
Would it be possible to use the Agenda date of a report for sorting, instead of the 'MatterHistoryActionDate'? Agenda date is perhaps more relevant, from an end-user perspective, and we know every report will have one.

**Comment by reginafcompton** [comment]
We could potentially do that, yes. 

However, some reports appear on more than one agenda. For example, [this report](https://boardagendas.metro.net/board-report/2017-0677/) appears on these agendas:

https://boardagendas.metro.net/event/regular-board-meeting-3b99ef2115be/
https://boardagendas.metro.net/event/system-safety-security-and-operations-348029bce7eb/

Do you want us to use the more recent event? (In the above case, the sort date would be that of the Regular Board Meeting.)

**Comment by shrayshray** [comment]
Yes, let's use the most recent.

**Comment by reginafcompton** [comment]
@shrayshray - to summarize the new approach for sorting: 

Each board report should receive a `last_action_date`. This is determined by, first, looking at the date of the last action (or "history"). If the report does not have any histories in Legistar, then we use the date of the most recent event agenda, upon which the report appears. 

In some cases, a board report has neither. For example, [2015-1513](https://boardagendas.metro.net/board-report/2015-1513/):
(1) does not have histories: http://webapi.legistar.com/v1/metro/matters/2506/histories
(2) does not appear as an agenda item for [the event](https://boardagendas.metro.net/event/regular-board-meeting-cb1097f09845/) referenced on the report: http://webapi.legistar.com/v1/metro/events/951/eventitems

For these cases, we'd need Metro to update the data in Legistar. Until then, they will appear as the "oldest" board reports when sorting by date. 

I'll put something up on the staging site shortly! And you can have a look.

**Comment by reginafcompton** [comment]
I am closing this, as no further action is required of DataMade.
