### ISSUE TITLE
pdf.js is having trouble on chrome

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#346]
i'm on chrome 69.0.3497.92, os x el capitan 10.11.6. it looks like our pdf rendering library doesn't like that.

<img width="1440" alt="screen shot 2018-09-14 at 4 48 33 pm" src="https://user-images.githubusercontent.com/12176173/45576870-b7723b00-b83e-11e8-8819-8785661fa8fc.png">

i am not encountering these issues on firefox or safari. i'm also not encountering them on chrome for browserstack.

**Comment by reginafcompton** [comment]
closing in favor of #378
