### ISSUE TITLE
Board Reports: Revise Columns on History

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#348]
In the "History" section of Board Report pages:
![image](https://user-images.githubusercontent.com/28063988/45721399-d59cab80-bb5c-11e8-90c6-4002073e8ba2.png)
1. Please change the header "Committee" to "Meeting", and
2. Add column for "Meeting Status".

No. 2 will help us provide greater clarity in cases where a meeting was cancelled but the report was routed to another meeting at a later date.

**Comment by jmithani** [comment]
Hi @shrayshray, just wanted to confirm I understand your request. For "Meeting Status," are you referring to the status of the meeting that occurred on the specified date (wherein this report was discussed)? Or do you mean something else?

Thanks!

**Comment by shrayshray** [comment]
@hancush hmm, i guess this is kind of confusing. Maybe we don't need the meeting status column. Would it be possible though to indicate when a meeting was cancelled, similar to the way it's shown on the meetings page? 
![image](https://user-images.githubusercontent.com/28063988/58656203-b3a11e80-82d0-11e9-81be-f9e182a58fc7.png)

One more thing -- Right now, the Meeting names just link to the page About the committee. Could this be changed so the link goes to the page for the actual meeting? E.g., the 9/20/17 Finance, Budget & Audit Committee meeting.
![image](https://user-images.githubusercontent.com/28063988/58656428-20b4b400-82d1-11e9-870e-323f52b95c8a.png)

**Comment by jmithani** [comment]
Sure thing, we can replace those links with ones to the specific meeting, and we can do the strike-through too for cancelled meetings.

**Comment by jmithani** [comment]
@shrayshray

@hancush and I have done some exploration of the database, and we can't find any registered actions on reports slated for cancelled meetings. (Is there an example report you had in mind you could share?) To track these actions, we would need to look at the agendas of the cancelled meetings to see if something was to be discussed then. That change is larger. Would you still like us to prioritize this?

**Comment by jmithani** [comment]
There is no current use case for this tracking bills that were on the agendas of cancelled meetings. Closing this issue until that becomes a need.

**Comment by shrayshray** [comment]
Here is an example: https://boardagendas.metro.net/board-report/2018-0606/
It was on the FINANCE, BUDGET AND AUDIT COMMITTEE agenda for OCTOBER 17, 2018 (cancelled) and the EXECUTIVE MANAGEMENT COMMITTEE agenda OCTOBER 18, 2018 (not cancelled).

Another example: https://boardagendas.metro.net/board-report/2018-0412/
On the Agenda for FINANCE, BUDGET AND AUDIT COMMITTEE meeting on
JULY 18, 2018, which was cancelled.

**Comment by shrayshray** [comment]
I'd like to revive this as a priority. To summarize, change the header from "Committee" to "Meeting", and mimic how meetings are listed on the "Meetings" page:
1. Link to the specific meeting (E.g., the 9/20/17 Finance, Budget & Audit Committee meeting) rather than the BOD or Committee page. 
2. Show meetings as cancelled if they were cancelled
(new item) 3. Add links to Recap and Minutes

**Comment by hancush** [comment]
@fatima3558, this will be a fun first issue! 

Right now, the `legislation.html` template iterates over an array of [`BillAction`](https://github.com/opencivicdata/python-opencivicdata/blob/ad30a91a243fd8784955b2440e79f23ba6fe7512/opencivicdata/legislative/models/bill.py#L90) objects to display the history of a board report.

https://github.com/datamade/la-metro-councilmatic/blob/da21a1e6ee8113ac8aa3222e8891588320c4f96c/lametro/templates/lametro/legislation.html#L86-L126

Jasmine started a PR, https://github.com/datamade/la-metro-councilmatic/pull/450, in which she updated the column name. and added a template tag to get the meeting at which each action took place, as Shelly requested. (N.b., the above code excerpt is from her PR, not master.)

The challenge here is that, if a meeting is cancelled, there are no associated actions (because the meeting never happened). We want to treat appearing on a meeting agenda as an action in itself. So, your objective is to create a list that includes normal actions, as well as "pseudo" actions each time the board report is scheduled to appear on a meeting's agenda. I would suggest building a list of dictionaries with the attributes we display in the `legislation.html` template. 

Add a property, `actions_and_agendas`, to the `LAMetroEvent` class that generates and returns this list. Then let's check in on next steps!

**Comment by fatima3558** [comment]
@hancush the first piece of this is complete! You can check it out in #450 , where I've added to the branch Jasmine created.

**Comment by hancush** [comment]
Darn it, I made a pretty significant typo in the prompt: I wanted you to add the property to the `LAMetroBill` class. To recoup some time, here is the scaffolding for the property:

```python
@property
def actions_and_agendas(self):
    '''
    Return list of dictionaries, each representing an action or an agenda on
    which the given bill appears, in the format:

    {
        'date': <datetime>,
        'description': <str>,
        'event': <LAMetroEvent>,
    }
    '''
    actions = self.actions.all()
    events = LAMetroEvent.objects.filter(agenda__related_entities__bill=self)

    data = {}

    for action in actions:
        # Get the event associated with the action – that is, the event where
        # the date and organization of the action match the action, and the bill
        # appears on the agenda. See Jasmine's `get_action_event` template tag
        # to get started!
        #
        # Build the dict
        #
        # Append it to data

    for event in events:
        # Build the dict (Use a description of "SCHEDULED")
        #
        # Append it to the data

    # Sort data by date

    return data
```

You will need to update Jasmine's method, as it was written prior to the upgrade to the OCD models. Some helpful hints:

- See `EventParticipant` and `RelatedEntityBase` in [`python-opencivicdata`](https://github.com/opencivicdata/python-opencivicdata) to figure out how to query for events involving the organization associated with an action.
- [We add a `date_dt` property to the `BillAction` object](https://github.com/datamade/django-councilmatic/blob/7957156785f5054ef18c4e06d0c43b49b13ecfd7/councilmatic_core/models.py#L631-L635) in `django-councilmatic`, so you can get at the date as a Python datetime object like `action.date_dt.date()`.
- You can access the bill related to an action very simply: `action.bill`.

I scheduled some time Friday morning to chat – let's go through any questions then! Also, if an example is helpful, here's what actions and agendas for [this board report](https://boardagendas.metro.net/board-report/2020-0483/) look like in a Python shell:

```python
>>> from lametro.models import LAMetroBill, LAMetroEvent
>>> b = LAMetroBill.objects.get(identifier='2020-0483')
>>> actions = b.actions.all()
>>> agendas = LAMetroEvent.objects.filter(agenda__related_entities__bill=b)
>>> actions
<QuerySet [<BillAction: 2020-0483 action on 2020-08-19>, <BillAction: 2020-0483 action on 2020-08-27>]>
>>> agendas
<QuerySet [<LAMetroEvent: Regular Board Meeting (2020-08-27T17:00:00+00:00)>, <LAMetroEvent: Finance, Budget and Audit Committee (2020-08-19T20:30:00+00:00)>]>
```

With the change you're making, the actions table will also include rows for "SCHEDULED" (in addition to the rows for each action):

![Screen Shot 2020-09-09 at 2 19 45 PM](https://user-images.githubusercontent.com/12176173/92643520-87cc6100-f2a7-11ea-80ad-18b6944c2a51.png)

**Comment by hancush** [comment]
Once you get the `actions_and_agendas` property in place, update the `legislation.html` template to iterate over its results instead of `actions`. 

https://github.com/datamade/la-metro-councilmatic/blob/08205430acce3ef0aa76d72c67958fcba734540f/lametro/templates/lametro/legislation.html#L89-L129

N.b., you will be able to access the relevant event directly from your dictionaries instead using the `get_action_event` template tag. You can actually remove that tag altogether before you request review!

**Comment by fatima3558** [comment]
@hancush Second attempt complete! Here's the link to the PR again: #450 

I went ahead and added `organization` to the dictionaries created by the `actions_and_agendas` property. Let me know if there's something in those queries that needs to be tweaked!

**Comment by fatima3558** [comment]
@hancush PR ready for your review! #656

**Comment by hancush** [comment]
Hey, @shrayshray, Fatima has finished up this change, and it's live on the staging site. You should now see all meetings at which a board report is scheduled for consideration included in that board report's history, e.g.,

Board report considered at past meetings: https://lametro-upgrade.datamade.us/board-report/2020-0540/

![Screen Shot 2020-10-19 at 3 15 16 PM](https://user-images.githubusercontent.com/12176173/96506873-ffce6500-121d-11eb-97aa-e45af8c90a81.png)

Board report scheduled for cancelled meeting: https://lametro-upgrade.datamade.us/board-report/2020-0440/

![Screen Shot 2020-10-19 at 3 10 58 PM](https://user-images.githubusercontent.com/12176173/96506498-4ff8f780-121d-11eb-8d8c-d20a38d5ac7b.png)

The meeting links go to the specific event page. Take a look and let us know what you think!

(Note that the staging site is a bit behind the live site on data, so some board reports may not appear on staging.)

**Comment by shrayshray** [comment]
@hancush this looks awesome! @fatima3558 great work, thank you!
I'm wondering if we need to keep "SCHEDULED" on this list after there is an action on the item. I can see it being useful when it's scheduled, then the meeting is cancelled, then it's approved/received/recommended for approval/etc. at a later meeting. But otherwise it might be superfluous. I don't have a problem with leaving it as is for now and going live, unless @camachoo sees an issue.

**Comment by hancush** [comment]
Hey, @shrayshray – Thoughts on deploying this?

**Comment by shrayshray** [comment]
@hancush let's do it.

**Comment by hancush** [comment]
This is live!
