### ISSUE TITLE
Overlapping text in mobile view

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#350]
Text on the homepage is overlapping in mobile browsers. I think this has to do with the addition of the attachment search buttons! Here's a screenshot from Omar's phone (Android). I'm having the same issue on iOS/Safari.
![screenshot_20180921-141942](https://user-images.githubusercontent.com/28063988/45910019-a71c0c00-bdba-11e8-9a8b-ffa0dc77f3ee.png)

**Comment by jmithani** [comment]
Closed via #404

**Comment by jmithani** [comment]
@shrayshray I deployed a fix for this. When you get a chance, can you let us know what you think?

**Comment by shrayshray** [comment]
@jmithani looks great to me, thank you!!
