### ISSUE TITLE
Meetings: List English video link first

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#354]
The meeting video links listed on the [Events page](https://boardagendas.metro.net/events/) should always list "Watch in English" before  "Ver en Espanol."
![image](https://user-images.githubusercontent.com/28063988/46701815-d82b7780-cbd5-11e8-9139-e7934635f2f7.png)

**Comment by jmithani** [comment]
i'm having some issues with this on the model level.

in theory, this should work:`LAMetroEventMedia.objects.filter(event_id=self.ocd_id).order_by('-label')` but i'm getting an error that `label` isn't an option. 

going into the shell, `LAMetroEvent.objects.filter(media__isnull=False)` gives me the error that `media` does not exist, though `dir(LAMetroEvent.objects.first())` shows `media` as a property and calling `LAMetroEvent.objects.first().media` returns a value (of `[]`).

let's look at it together tomorrow! writing this so i can remember my steps, heh
