### ISSUE TITLE
Board Members: Update Bios

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#358]
Metro's Board Members have given us updated bios. Please replace the current bios with those below: 

**Paul Krekorian**
Born and raised in the San Fernando Valley, Paul Krekorian has spent more than a decade in public service. Since 2010, he has served on the Los Angeles City Council where his leadership as Chairman of the Budget and Finance Committee helped guide the City through the Great Recession and toward greater economic promise. Paul is also Chairman of the Ad Hoc Committee on Job Creation, the Vice Chair of the Housing Committee, and sits on the Energy, Climate Change and Environmental Justice Committee; the Trade Travel and Tourism Committee; the Ad Hoc Committee on the 2028 Olympics; the Executive Employee Relations Committee and the Board of Referred Powers.  

In addition to serving on the Metro Board of Directors, Paul also serves on the boards of Metrolink, and the San Fernando Valley Council of Governments.

Paul graduated from Reseda’s Cleveland High School before earning his B.A. in Political Science from the University of Southern California and a law degree from UC Berkeley. Upon graduating, he spent two decades practicing business, entertainment, and property litigation. 

In 2006, after three years on the Burbank Board of Education, Paul won election to the California State Assembly, representing the 43rd District. Paul is the first Armenian-American to be elected to public office in the City of Los Angeles.

**Hilda L. Solis**
Supervisor Hilda L. Solis was sworn in as  Los Angeles County Supervisor for the First District of Los Angeles County on December 1, 2014.

Prior to becoming Supervisor she served as Secretary of Labor.  Supervisor Solis was confirmed on February 24, 2009, becoming the first Latina to serve in the United States Cabinet. Before that, Supervisor Solis represented the 32nd Congressional District in California, a position she held from 2001 to 2009.
In the Congress, Supervisor Solis’ priorities included expanding access to affordable health care, protecting the environment, and improving the lives of working families. A recognized leader on clean energy jobs, she authored the Green Jobs Act which provided funding for “green” collar job training for veterans, displaced workers, at risk youth, and individuals in families under 200 percent of the federal poverty line.
In 2007, Supervisor Solis was appointed to the Commission on Security and Cooperation in Europe (the Helsinki Commission), as well as the Mexico — United States Interparliamentary Group. In June 2007, Solis was elected Vice Chair of the Helsinki Commission’s General Committee on Democracy, Human Rights and Humanitarian Questions. She was the only U.S. elected official to serve on this Committee.
A nationally recognized leader on the environment, Supervisor Solis became the first woman to receive the John F. Kennedy Profile in Courage Award in 2000 for her pioneering work on environmental justice issues. Her California environmental justice legislation, enacted in 1999, was the first of its kind in the nation to become law.

Supervisor Solis graduated from California State Polytechnic University, Pomona, and earned a Master of Public Administration from the University of Southern California. A former federal employee, she worked in the Carter White House Office of Hispanic Affairs and was later appointed as a management analyst with the Office of Management and Budget in the Civil Rights Division.

**Janice Hahn**
Janice Hahn was elected to the Los Angeles County Board of Supervisors in November 2016. She represents the 4th district which stretches from Marina del Rey through the beach cities, the Palos Verdes Peninsula, the Harbor Area, Long Beach, through the Gateway Cities and east to Diamond Bar.

In her short time on the Board, Supervisor Hahn has already established herself as a leader in the struggle to end the current homelessness crisis, a champion for communities plagued by pollution and health problems, and a dynamic new voice on the Metro Board of Directors.

Supervisor Janice Hahn inherited a passion for public service from her late father, Supervisor Kenneth Hahn, who held public office in Los Angeles County for fifty years and who left behind an incredible legacy of service. Before being elected to the Board of Supervisors, Janice Hahn served for ten years on the Los Angeles City Council and for five and a half years in Congress.

While in Washington, she served on the House Homeland Security Committee, Committee on Small Business, and the Committee on Transportation and Infrastructure. She earned nationwide recognition for founding the PORTS Caucus and recruited over 100 of her fellow House colleagues to advocate for ports issues and infrastructure.  She has been a leader on efforts to rebuild our national freight infrastructure system, level the playing field for small business owners, and reducing gang violence in our communities. During her time in Congress, Hahn had a reputation for working to find common ground across the political aisle on behalf of the American people.

**John Fasana**
John Fasana is the Mayor of the City of Duarte, and is one of four City Selection Committee representatives elected to the 13-member Metro Board of Directors.  He has served on the Metro Board since its inception in 1993, and previously served as Metro Board Chair from 2001 to 2002.  He currently serves as Chairperson of the Ad hoc Congestion, Highways and Roads Committee, and is a member of the Finance and Budget Committee, System Safety and Operations Committee and the Executive Management Committee.  During his tenure on the Metro Board, he has tirelessly worked with his colleagues in Sacramento and Washington DC to obtain several billion dollars for LA County residents for critically needed multimodal congestion relief projects.
Mr. Fasana was first elected to the Duarte City Council in November 1987, and reelected in 1991, 1995, 1999, 2003, 2007 and 2011, and reappointed in 2015.  He served as Mayor in 1990, 1997, 2003 and 2009.  As a Councilmember he has promoted Duarte’s interests in transportation, community services and environmental protection.
Mr. Fasana has also served on the Board of the San Gabriel Valley Council of Governments (COG) since its inception, representing 31 cities and over 2 million residents working together to solve regional issues; and in the past, served on Foothill Transit’s Board.  In 2015 he retired from his 35-year career with Southern California Edison.  John is a graduate of Whittier College.  He and his wife, Kris, have three adult children, all of whom were educated in Duarte’s public schools, and two sons-in-law.

**Mark Ridley-Thomas**
Since he was overwhelmingly elected to the Los Angeles County Board of Supervisors in 2008, and reelected in 2012 and 2016, Mark Ridley-Thomas has distinguished himself as an effective leader for more than two million Second District residents, tackling such critical issues as homelessness, voting rights, affordable quality education, living wage, police accountability, healthcare for all, and more. First elected to public office in 1991, he served with distinction on the Los Angeles City Council for nearly a dozen years, departing as Council President pro Tempore. He later served in the California State Assembly, where he chaired the Jobs, Economic Development and Economy Committee, and in the California State Senate, where he chaired its Committee on Business, Professions and Economic Development. 

**Mike Bonin**
Mike Bonin was elected to represent the 11th District on the Los Angeles City Council in 2013, and three weeks later was appointed to the Metro Board of Directors by Mayor Eric Garcetti. Bonin is the Chair of the Council’s Transportation Committee and the Vice Chair of the Trade, Travel, and Tourism Committee, which oversees LAX International Airport and the Port of Los Angeles. In addition to his transportation portfolio, he also serves on the Council’s Homelessness and Poverty Committee and Budget and Finance Committee. A former newspaper reporter, Mike graduated from Harvard University in 1989 with a B.A. in United States History.

**Robert Garcia**
Dr. Robert Garcia, 40, is an educator and the 28th Mayor of Long Beach. He is one the youngest mayors of any large city in America and has taken a leadership role in shaping the City of Long Beach into an innovative, sustainable hub for economic development, technology, and education. 

Mayor Garcia is a Board Member on the Los Angeles County Metropolitan Transportation Authority (Metro) representing the Gateway City Council of Governments. He is a first-generation college graduate, holding a Master’s Degree from the University of Southern California, a Doctorate in Higher Education from Cal State Long Beach (where he also earned his Bachelor’s in Communication), and is an accomplished educator. 

He was born in Lima, Peru, and immigrated to the United States at age 5 with his family and became a citizen at age 21. Mayor Garcia is fluent in both Spanish and English.

**Sheila Kuehl**
Supervisor Sheila James Kuehl, representing Los Angeles County’s Third District, was elected on November 4, 2014, assumed office on December 1, 2014 and is currently the Chair of the Board of Supervisors.
In her first three years on the Board, she has undertaken or collaborated in a number of initiatives and motions to improve the quality of life and reform systems in the County, including increasing the minimum wage, creating a Sheriff’s Oversight Commission, providing unprecedented funding and services for our homeless population and those trying to find and keep affordable housing, increasing services and support for relative caregivers for our foster children, supporting the creation of the Office of Child Protection, creating oversight of the Probation Department, innovating on issues of water conservation and recycling, creating a County-led Community Choice Aggregation (CCA) JPA to bring green power choices to County residents, protecting our arts venues and productions, spurring the construction and re-opening of the John Anson Ford Theatres, reforming both our adult and juvenile justice systems to emphasize and enhance “second chance” and anti-recidivism programs, including the opening of Campus Kilpatrick, a state-of-the-art juvenile justice facility that emphasizes rehabilitation and preparation for a constructive future, protection of the Santa Monica Mountains, as well as the Coast, kicking off a Women and Girls Initiative to build toward a County-wide collaboration on needed changes and programs in all County departments and services, bringing together three County health departments into a new Agency model to break down barriers to service for those who need physical health, mental health and substance abuse treatment, bringing a focus in County Departments on better serving and supporting our LGBTQ youth who comprise almost 20% of our foster kids, and much more.
She is also Chair of the Board of Commissioners of First 5, LA, First Vice Chair of the Board of Directors of Metro, Vice Chair of the Board of the new CCA and Chair of the Countywide Criminal Justice Coordination Committee.
Supervisor Kuehl served eight years in the State Senate and six years in the State Assembly. She was the Founding Director of the Public Policy Institute at Santa Monica College and, in 2012, was Regents’ Professor in Public Policy at UCLA.
She was the first woman in California history to be named Speaker Pro Tempore of the Assembly, and the first openly gay or lesbian person to be elected to the California Legislature. She served as chair of the Senate Health and Human Services Committee, Natural Resources and Water Committee, and Budget Subcommittee on Water, Energy and Transportation, as well as the Assembly Judiciary Committee.
She authored 171 bills that were signed into law, including legislation to establish paid family leave, establish nurse to patient ratios in hospitals; protect the Santa Monica Mountains and prohibit discrimination on the basis of gender and disability in the workplace and sexual orientation in education. She fought to establish true universal health insurance in California.
Prior to her election to the Legislature, as a public-interest attorney Supervisor Kuehl drafted and fought to get into California law more than 40 pieces of legislation relating to children, families, women, and domestic violence. She was a law professor at Loyola, UCLA and USC Law Schools and co-founded and served as managing attorney of the California Women’s Law Center.
Supervisor Kuehl graduated from Harvard Law School in 1978. In her youth, she was known for her portrayal of the irrepressible Zelda Gilroy in the television series, “The Many Loves of Dobie Gillis.”

**Comment by reginafcompton** [comment]
Done!
