### ISSUE TITLE
Board member detail: Missing map geojson

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#361]
On the person detail, the maps do not render, for at least two members, e.g., 

https://boardagendas.metro.net/person/james-butts-dc85ae14f195/
https://boardagendas.metro.net/person/sheila-kuehl-9c9abd7a6ff8/

This seems to be because the [`person.latest_council_membership.post.shape`](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/views.py#L393) evaluates to False, i.e., the membership post does not have a `shape`.

**Comment by shrayshray** [comment]
It looks like Sheila Kuehl's area is rendering now on her page. James Butts' is still not. It's high priority to have his map area render, as he is Chair of the Board of Directors this year. Is there anything you need from Metro's side to address this?

**Comment by hancush** [comment]
The work to resolve this has been done in the upgrade: #518.

**Comment by hancush** [comment]
This change is now available on the test site! https://lametro-upgrade.datamade.us
