### ISSUE TITLE
Board Members: Replace Shirley Choate with John Bulinski

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#363]
At the October 24th Board Meeting, it was announced John Bulinski will replace Shirley Choate as the non-voting board member. His full title and bio is below, and I'll post a headshot as soon as I receive it. I made this change in Legistar, please update on the website. 
___
John Bulinski District 7 Director California Department of Transportation (Caltrans)
John Bulinski, District 7 Director, for the California Department of Transportation (Caltrans), which encompasses metropolitan Los Angeles and bucolic Ventura counties. John oversees transportation systems in a dynamic region that boasts 25% of California’s population, an annual construction program of more than $2 billion, and some of the most innovative solutions to help move people and goods through Southern California and as part of the 5th largest economy in the world, throughout the rest of the world. John places a high priority on collaboration, community, and employee engagement.
John has more than 29 years of service with Caltrans. In John’s most recent appointment, District 8 Director, John oversaw roadway activities within Riverside and San Bernardino counties. Prior to John’s service as District 8 Director, John served as the District 2 Director for Caltrans in Northern California from 2008 - 2015. In this capacity, he was responsible for overseeing projects in nine counties in the Northeastern part of California.
John is a licensed professional engineer and is a graduate of Humboldt State University with a Bachelor of Science Degree in Environmental Engineering.
John and his wife, Jan, have three children — Rachael, William, and Logan along with six grandchildren. Outside of the office John enjoys family time, woodworking, racquetball, softball, fishing, bicycling, and camping.

**Comment by shrayshray** [comment]
@reginafcompton Yes. Bulinski is not “acting” and the slight variation on the rest of the title is correct.

________________________________

**Comment by reginafcompton** [comment]
@shrayshray - I need a little more clarification on this! 

Metro has five members, nominated by five subdistricts. We show this two ways: 

(1) on the Board Members page with the "District appointee" label (https://boardagendas.metro.net/board-members/)
(2) on the person page, under their photo (e.g., https://boardagendas.metro.net/person/janice-hahn-4682bb5db3dd/ and the ). 

How does Bulinski fit into all this?

**Comment by shrayshray** [comment]
Below are mock-ups of how Bulinski's title should be treated:
(1)
![bulinski1](https://user-images.githubusercontent.com/28063988/47879337-901b0180-dddd-11e8-8e49-a3239c4ec2a9.png)
(2)
![bulinski2](https://user-images.githubusercontent.com/28063988/47879350-97420f80-dddd-11e8-8198-cce07d2544c2.png)

**Comment by reginafcompton** [comment]
@shrayshray - this issue is ready to close, after we receive a headshot.

**Comment by shrayshray** [comment]
@reginafcompton 
![john_bulinski](https://user-images.githubusercontent.com/28063988/47942976-4ef42180-deb1-11e8-89a3-0c474309cd5c.jpg)

**Comment by reginafcompton** [comment]
Headshot added!
