### ISSUE TITLE
Board Member page: John Bulinski's page is showing "Sponsored Board Actions" ...

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#366]
John Bulinski's first Board Meeting will be 11/14/18 ... but his page already shows "Sponsored Board Actions", from 2017: https://boardagendas.metro.net/person/john-bulinski-184f9b0a3cc7/
![image](https://user-images.githubusercontent.com/28063988/47879708-847c0a80-ddde-11e8-9c53-949e48a0a052.png)

**Comment by reginafcompton** [comment]
Ready to close: https://boardagendas.metro.net/person/john-bulinski-184f9b0a3cc7/
