### ISSUE TITLE
Committee: Show Name of Chairperson

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#368]
In the list of committees on the [Committees page](https://boardagendas.metro.net/committees/), is it possible to display the name of the committee chairperson, instead of just the title of "Chair"?
![image](https://user-images.githubusercontent.com/28063988/47938179-7393cd80-dea0-11e8-9eea-d62220b97f8a.png)

**Comment by jmithani** [comment]
Closed via #425!
