### ISSUE TITLE
Taxonomy project: Training

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#375]
DataMade will meet with SmartLogic experts to learn the ins-and-outs of their API. 

We will plan a mid-December or January meeting. We have 5 hours scoped for "research," which we can allocate for this session(s).

**Comment by shrayshray** [comment]
@reginafcompton and Datamade team. Smartlogic is ready to schedule this training. They're currently working on an agenda, which I will share when I receive, and expect there will be 2 four-hour training sessions. The ideal dates would be April 8th and 9th. Would those dates work for you?

**Comment by reginafcompton** [comment]
Terrific @shrayshray! April 8 and 9 look good on our end: we'll keep an eye out for the official agenda and time. (Also, looping in @hancush . . .)

**Comment by shrayshray** [comment]
@reginafcompton @hancush Below is the proposed agenda and timing for training with Smartlogic. What do you think? Do you have a preference for either one of the proposed dates, or time of day?

"Here is what I think would be a good agenda for DataMade training.

•	9:00 – Introductions
•	9:15 – Overview of Semaphore.  Search demo.
•	9:45 – Overview of Semaphore Solution for Legistar.  
•	10:00 – Semantic Enhancement Server API.
o	SES REST call overview
o	How to call SES in Cloud with Authentication
o	How to correlate results from SES API to Legistar or Matters with SES Concepts
•	10:45 – Q&A

I think we can cover the topics in this amount of time.  However, it will depend on the level of engagement we get from DataMade.  If we need a follow-up, we can do that.  I put time of day on the Agenda, but that was only to bracket out the times.  You can schedule any part of the day.  I think Shelly said April 8 and 9 were the candidate days.  Feel free to suggest other topics or if you think the time is too short, we can expand."

**Comment by hancush** [comment]
hey, @shrayshray! that agenda looks great to me. right now, we're wide open the afternoon of april 8.

**Comment by hancush** [comment]
we did the training! 

@shrayshray, it seems like there are a couple of things to do on metro's end before the smartlogic integration goes live. i've opened issues laying out the work we need to do integrate the taxonomy changes into councilmatic (#431, #432, and #433). how would you like us to prioritize them, relative to the issues in monthly milestones? (put another way, about when should we aim to have work complete on our end?)

**Comment by shrayshray** [comment]
@hancush great! Does completing this work by 5/17/19 sound doable? That would help us coordinate with some milestones on the Smartlogic side. Let me know if you think that would work for you.

**Comment by hancush** [comment]
hey, @shrayshray! 5/17 would be a little tight for us. would 5/31 work on your end?

**Comment by shrayshray** [comment]
@hancush Yes, 5/31 works.

**Comment by hancush** [comment]
great, @shrayshray! thanks for your flexibility. i've opened up [a smartlogic integration milestone](https://github.com/datamade/la-metro-councilmatic/milestone/25) to track our progress. meanwhile, i'll go ahead and close this issue.
