### ISSUE TITLE
Meetings: Remove 10/29/18 Regular Board meeting

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#376]
Please remove the Regular Board Meeting from 10/29/2018: https://boardagendas.metro.net/event/regular-board-meeting-3842ae24f7ad/ This meeting did not happen, and was deleted from Legistar (my guess is it was created by mistake, then deleted shortly after without alerting us).
![image](https://user-images.githubusercontent.com/28063988/48522526-ddf82680-e82d-11e8-96b6-8376c87ba699.png)

**Comment by reginafcompton** [comment]
@shrayshray - it's removed!
