### ISSUE TITLE
Board Reports: Most Recent Action as Future Date

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#380]
Where does the date for "Most Recent Action" on Board Reports come from?
[On the Board Reports page,](https://boardagendas.metro.net/search/) there are reports listed with "Most Recent Action" as 12/06/2018 ... these reports are on the Agenda for the Board of Directors meeting 12/06/2018, but that Agenda has not been published yet ... the meeting is next week.
The most recent action would have been at the committee meeting where these reports were first presented (in this case, likely 11/14 or 11/15, but potentially at an earlier date).
![image](https://user-images.githubusercontent.com/28063988/49186983-f468ac80-f31a-11e8-8f81-edde2e8d7111.png)

**Comment by reginafcompton** [comment]
@shrayshray - interesting discovery. 

I think we'll need to reconfigure the logic for this to account for agendas that have not been published.
https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/utils.py#L42

What is the priority level of this issue?

**Comment by shrayshray** [comment]
The sooner, the better ... it's not a huge issue, but it's confusing and inaccurate from a user-experience standpoint in the meantime.

**Comment by hancush** [comment]
update: the code change for this has been implemented in #383! 

we need to deploy the change and rebuild the search index for it to take effect on the live site.

**Comment by reginafcompton** [comment]
@shrayshray - this fix has been deployed. Can you check that this looks as expected, and close the issue when ready?

**Comment by shrayshray** [comment]
@reginafcompton I was out of the office and didn't get a chance to check this on 12/5, I'm sorry. I put a reminder in my calendar to check before next month's meetings. But it looks like this fix might have caused an issue with sorting by date ... whether I sort by ascending or descending, there are 12/6/18 reports on top.

**Comment by reginafcompton** [comment]
@shrayshray - we got this squared away by rebuilding the Solr index.

https://boardagendas.metro.net/search/?sort_by=date&order_by=asc

I'll go ahead and close this.
