### ISSUE TITLE
Board Report: "Ghost" Attachment links in sidebar

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#381]
Occasionally, after a Report is published, its attachments are removed/replaced/revised. It looks like in cases where attachments are removed, the hyperlinks remain in the sidebar and link to a 404 error page on metro.legistar.com. Here are some examples:
https://boardagendas.metro.net/board-report/2018-0509/
https://boardagendas.metro.net/board-report/2018-0214/
https://boardagendas.metro.net/board-report/2017-0554/
https://boardagendas.metro.net/board-report/2017-0413/
https://boardagendas.metro.net/board-report/2017-0023/
https://boardagendas.metro.net/board-report/2018-0690/
https://boardagendas.metro.net/board-report/2018-0410/
https://boardagendas.metro.net/board-report/2017-0736/
https://boardagendas.metro.net/board-report/2017-0289/

Is it possible to remove the hyperlink from the sidebar when an attachment is removed from a report?

And here's another oddity, potentially related -- The link to "Download Board Report and Attachments" is displayed, but no attachments are linked in sidebar and there are no attachments to the Report when it's downloaded via that link: https://boardagendas.metro.net/board-report/2017-0649/

**Comment by reginafcompton** [comment]
@shrayshray - could you say a little more about the "ghost" attachments? I do not see duplicate or out-of-date attachments in the examples you provided. (Did the issue resolve itself?)

**Comment by shrayshray** [comment]
Yes, it looks like this issue resolved itself (except for the second part, for which you opened a new issue: #422) Thanks!
