### ISSUE TITLE
check the status of requests to the pdf merger

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#382]
the pdf merger went down unexpectedly, but the logs on the councilmatic side did not indicate anything had gone wrong. there is an opportunity to verify that post requests return a 200 status code [in the `compile_pdfs` command](https://github.com/datamade/la-metro-councilmatic/blob/60277030346849c9fa3c694ec2b98f865f696ab8/lametro/management/commands/compile_pdfs.py#L42-L85). consider using that opportunity to raise exceptions, so we know something isn't working.

**Comment by reginafcompton** [comment]
Yes, @hancush - that seems like a smart place for exception handling! 

Could we also have logs further upstream? [BGA has a pattern for nginx logging](https://github.com/datamade/bga-payroll/pull/291) – could we do something similar with supervisor?

**Comment by shrayshray** [comment]
As of 5:10pm PST 11/30, the packet for this Agenda was available: https://boardagendas.metro.net/event/regular-board-meeting-52018b89a7ba/
However, today the packet link is missing. 
Only one change on our side in the meantime ... shortly after 5:10pm 11/30, Omar had to export and re-publish the Agenda. Not sure whether this would have an impact, just wanted to give you all the info we have! Can you please look into getting the packet back up?

**Comment by reginafcompton** [comment]
@shrayshray - the packet is visible now. I was doing some testing with the metro-PDF-merger, which likely caused the delay.

**Comment by shrayshray** [comment]
@reginafcompton phew, thank you!!
