### ISSUE TITLE
Report: TO BE REMOVED report is showing

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#387]
Report 2018-0747 has In Control set to "TO BE REMOVED", but it's still showing on the website: https://boardagendas.metro.net/board-report/2018-0747/

Can you make sure it's removed as soon as possible? I thought we were using "TO BE REMOVED" as a filter to hide reports, is this not the case?

**Comment by reginafcompton** [comment]
@shrayshray - I am looking into our strategies for filtering reports. However, if you need this fix ASAP, then first, I need you to delete the bill from Legistar or set its `MatterRestrictViewViaWeb` to true. Could you do that, and let me know when you do?

**Comment by shrayshray** [comment]
@reginafcompton I just set MatterRestrictViewViaWeb to true. Thanks!

**Comment by reginafcompton** [comment]
@shrayshray - great! It's no longer on the site. 

I do not have notes on hiding or skipping (in the scrape) bills with the "TO BE REMOVED" setting. [Here's the relevant code with a helpful comment about how Councilmatic filters bills.](https://github.com/datamade/la-metro-councilmatic/blob/60277030346849c9fa3c694ec2b98f865f696ab8/lametro/models.py#L82) Would you like us to filter for "TO BE REMOVED" as well?

**Comment by shrayshray** [comment]
@reginafcompton yes, please filter reports where "In Control Body" = "TO BE REMOVED" so they are not displayed on the site.

**Comment by reginafcompton** [comment]
Closing via scraper changes in https://github.com/opencivicdata/scrapers-us-municipal/pull/269/files!
