### ISSUE TITLE
delete december 2018 test events from the api and councilmatic database

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#389]
we have [tons of permutations](https://ocd.datamade.us/events/?name=Regular%20Board%20Meeting&start_date__gt=2018-12-16&start_date__lt=2018-12-18) of a test event in the ocd api and the metro database. this shows up as many, duplicate events on the staging site.

![events](https://user-images.githubusercontent.com/12176173/51266668-7f603d80-1981-11e9-8fde-54054ec23457.gif)

following [this gist](https://gist.github.com/reginafcompton/2cb4d690c0253a22305929a334753959), remove the test events (that is, events where `location__name="TEST"`) from the api and the database.

**Comment by reginafcompton** [comment]
We can close this via work done on #415 !

**Comment by hancush** [comment]
these got removed from production but not staging. @jmithani, if you ever have a couple of minutes to kill, this would be a great housekeeping task. related to #430.

**Comment by hancush** [comment]
+ multiple permutations of an executive management committee meeting in august 2019.

**Comment by hancush** [comment]
We have new databases! No longer need to do this. 🎊
