### ISSUE TITLE
Staging site loads slowly

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#396]
I noticed, the last week or so, that the staging site requires extra time to load. 

I suggest investigating this: it could be a warning signal of things-to-come on the metro-server and hence the production site. (N.b., currently, the production site loads quickly, as expected.)

**Comment by hancush** [comment]
We had two DNS entries for the staging site. One of them didn't resolve. We removed the old one, and the staging site started performing as expected!
