### ISSUE TITLE
Older private bills raise too many exceptions in the scraper

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#401]
Private bills created several years ago are raising lots of exceptions, for example: `MatterRestrictViewViaWeb` is set to False (which confuses the logic of our scraper), the bill has a date that falls outside the defined legislative sessions, the bill presents a new bill_type, etc. 

It does not seem useful to scrape these early bills, since they will very likely never be made public. (@shrayshray, can you confirm?) So, rather than finding a work around for all these cases, I propose the following:

1. for today, I am going to turn off scraper functionality for all private bills, i.e., we revert to scraping just public bills

2. moving forward, let's identify a lower boundary for when the scraper should scrape a private bill – for example, the scraper would only scrape private bills from the start of this legislative session and later (all bills created on July 1, 2018 or later). The most recently created private bills seem to be the ones that require attention, since they are the bills toggled between public and private. 

@shrayshray - can you let me know if this sounds like an appropriate solution? If so, we can get something implemented quickly.

**Comment by shrayshray** [comment]
@reginafcompton you're right, early reports which are not public are not likely to be made public.
A few months ago, I gave the Board Secratary's office a list of early reports which were clearly tests or otherwise should not be public, but I'm not sure the progress they've made on cleaning them up.
Your solution seems like a sound approach/work around.

**Comment by reginafcompton** [comment]
Closed via https://github.com/opencivicdata/scrapers-us-municipal/pull/262 and https://github.com/opencivicdata/scrapers-us-municipal/pull/263
