### ISSUE TITLE
Events page does not load fast enough

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#403]
Today, we noticed that the Events page on the staging site was raising a 502 error: this was caused by Nginx timing out, suggested by several `client closed connection while waiting for request`errors in the Nginx log (i.e., `/var/log/nginx/lametro-staging-councilmatic-error.log`).

## The particular problem
The database had nearly 300 TEST events, which dramatically slowed the load time. I cleared those, and the site runs fine now. (I did the same on the production database.)

## The more general problem
**The site should be able to handle this volume of events.** (At some point, we'll have hundreds more!) Let's dig into this issue, sooner rather than later. Two considerations:

- how are we building and returning the Events queryset, and can we do that more efficiently? [`prefetch_related`](https://docs.google.com/document/d/1giTexSmZ0hXd1sPBU8AUuT_O2VWgpXaGqDZnMzW05kE/edit) comes to mind. (We used [prefetch_related in Chicago Councilmatic](https://github.com/datamade/chi-councilmatic/blob/master/chicago/views.py#L28) for a similar issue.)

- Solr! Let's finally deal with issue https://github.com/datamade/la-metro-councilmatic/issues/233

@shrayshray I'd like to prioritize this in our February milestone? Would that be okay?

**Comment by shrayshray** [comment]
Yes, please prioritize!

**Comment by reginafcompton** [comment]
## Expensive code

**[`updates_made`](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templatetags/lametro_extras.py#L179)** 
Iterates over all EventDocuments for every instance of an Event rendered on the Event template. 

Solution? We can gather this information by annotating the main queryset, rather than gathering this data in the template. That is, do away with the `updates_made` template tag and add that logic to the view code. 

**implementation of [`media` property](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/models.py#L413)**
Queries for all media objects, sorts them, and [iterates over them for each event.](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templates/partials/past_event_day.html#L37-L44)

Solution? Again, it seems like we should annotate the main event queryset with media data, rather than in the template.

**Comment by reginafcompton** [comment]
@shrayshray - we made good progress on this issue. I see a notable difference in load time for `/events`. I think we can finish the remaining items in March (or later). I'll put this in the March milestone for now.
