### ISSUE TITLE
Bill detail: Links to (once public) now private bills visible under "Related reports"

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#409]
Example: https://boardagendas.metro.net/board-report/2017-0888/

We need a mechanism for hiding these urls. Otherwise, the site directs the user to an Internal Sever Error. 

@shrayshray - I'd like to handle this before the end of the week. Does that make sense, priority-wise?

**Comment by shrayshray** [comment]
@reginafcompton yes, absolutely.

**Comment by reginafcompton** [comment]
Closed via https://github.com/datamade/la-metro-councilmatic/pull/410
