### ISSUE TITLE
dedupe committee list on board member detail pages

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#41]
this is a recurring issue with memberships on this project bc la metro data repeats for each term in office; probably worth a second look to make sure our query sets are taking term dates into account wherever memberships are being used to populate a list or count, etc.

**Comment by hancush** [comment]
(also remove ad-hocs)

**Comment by reginafcompton** [comment]
I fixed this for the person detail view. I will close this issue, but keep an eye out for other such duplicates.
