### ISSUE TITLE
Board Report: Old Attachments linked in sidebar of Report

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#411]
The old attachment links [on the Report ](https://boardagendas.metro.net/board-report/2018-0439/)go to 404 pages. 
See below screenshot of the Councilmatic site versus the report in Legistar. ![image](https://user-images.githubusercontent.com/28063988/53607281-f2f58d00-3b72-11e9-8997-1cd09181aef5.png)
![image](https://user-images.githubusercontent.com/28063988/53607364-44058100-3b73-11e9-9443-16af27b89b05.png)

**Comment by shrayshray** [comment]
Another example:
https://boardagendas.metro.net/board-report/2019-0840/
![image](https://user-images.githubusercontent.com/28063988/74294361-78c20800-4cf2-11ea-9474-147d520b5e60.png)


In Legistar:
![image](https://user-images.githubusercontent.com/28063988/74294321-56c88580-4cf2-11ea-9944-8d9b96191d9f.png)

**Comment by shrayshray** [comment]
https://boardagendas.metro.net/board-report/2019-0853/
![image](https://user-images.githubusercontent.com/28063988/74294482-df472600-4cf2-11ea-9dbc-9f9d25a92ccf.png)

**Comment by hancush** [comment]
This looks like an issue with the intermediate data step we eliminated with the upgrade! This should be resolved on the test site. (You can check by swapping `boardagendas.metro.net` for `lametro-upgrade.datamade.us` in the URLs to the board reports with problem attachments.)
