### ISSUE TITLE
How to classify event with status "Final Revised"?

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#414]
We recently improved filtering for private bills to address issue #409.

With this fix, we only display bills that appear on events with an EventAgendaStatusName of "Canceled" or "Final." (Per the steps we agreed upon in https://github.com/datamade/la-metro-councilmatic/issues/345#issuecomment-429938651)

This brought to light something about the events data. It looks like several events have an EventAgendaStatusName of "Final Revised." I assume such events are public and should be classified as "passed" [(as our scrapers do with a status of "Final")](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/lametro/events.py#L157). Here's an example: 

http://webapi.legistar.com/v1/metro/events/1277

@shrayshray Can you please confirm? or suggest a different status? If so, we can make the change in the scraper and properly assign a status to those events.

**Comment by shrayshray** [comment]
@reginafcompton you're correct about "Final Revised". It looks like there's also a status of "Final 2nd Revised" which should also be included.

**Comment by reginafcompton** [comment]
Thanks @shrayshray ! I'll update the scraper accordingly.

**Comment by reginafcompton** [comment]
Handled via https://github.com/opencivicdata/scrapers-us-municipal/pull/268.

For example, an [event with status "Final Revised"](http://webapi.legistar.com/v1/metro/events/1277) appears as expected in [Councilmatic with all public bills visible in the sidebar](https://boardagendas.metro.net/event/regular-board-meeting-fe48b9af913c/).
