### ISSUE TITLE
Board of Directors: Mutiple links to a meeting that didn't happen

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#415]
On the [Board of Directors page](https://boardagendas.metro.net/board-members/), there are a whole bunch of links to a Regular Board Meeting on 12/17/18. The actual Board meeting was on 12/6/18. Please remove the incorrect links.
![image](https://user-images.githubusercontent.com/28063988/53838886-fe69ff00-3f4a-11e9-9442-89ffc14839fe.png)

**Comment by hancush** [comment]
Believe this is related to #389!

**Comment by reginafcompton** [comment]
@shrayshray - I went ahead and deleted the TEST events in question. We need to add a filter on the corresponding view to ensure that such events do not appear on the site.

**Comment by shrayshray** [comment]
@hancush @reginafcompton thank you!

**Comment by reginafcompton** [comment]
@shrayshray - related to this issue...it appears that Legistar has about half-a-dozen test events, if you need to clean those up!

**Comment by reginafcompton** [comment]
Closed via PR #416
