### ISSUE TITLE
Consider a less aggressive scraping strategy on Fridays

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#419]
Recently, our aggressive event scrapes failed with 104 status codes for a period of several hours. Metro uploaded agendas during this team, but they did not show up on the site due to failures in the scraper (indeed, the problem the aggressive scrapes were meant to prevent!) Consider a less aggressive schedule. @reginafcompton suggests two scrapes, one complete and one with a small window, per hour.

**Comment by reginafcompton** [comment]
For reference: [the crons themselves.](https://github.com/datamade/scrapers-us-municipal/blob/master/scripts/scrapers-us-municipal-crontask#L23)

@shrayshray, to decode the crons, we scrape _all events_ at 0, 15, 30, and 45 minutes after the hour. We implemented this solution to handle issues arising with Legistar timestamps that did not change as expected, e.g., https://github.com/datamade/la-metro-councilmatic/issues/310 and https://github.com/datamade/la-metro-councilmatic/issues/267

We also aggressively scrape bills on Friday (again, to address timestamp issues, e.g., https://github.com/datamade/la-metro-councilmatic/issues/328)

I think we should consider a multi-faceted revision of our crons: 

* Narrow the window for aggressive scraping. Currently, we scrape all bills and events, from 4:00 pm CST until 11:50 pm CST. 
* Minimize the number of times we hit Legistar by scraping all bills and events, _once an hour_, and include small windowed scrapes one or two times per hour.

@shrayshray - can you let us know how this sounds? and how we should prioritize making changes?

**Comment by shrayshray** [comment]
@reginafcompton this sounds good. This should be high priority. Do you have any concerns about implementing it right away, as there will also be an agenda posted this Friday?

**Comment by reginafcompton** [comment]
@shrayshray - I can implement this solution tomorrow. I'd rather test this with our upcoming agenda on Friday, rather than wait until we have multiple agendas posted in April (which seems higher risk to me).

**Comment by shrayshray** [comment]
@reginafcompton sounds like a plan, thank you!

**Comment by reginafcompton** [comment]
@shrayshray - we can close this issue via https://github.com/datamade/scrapers-us-municipal/pull/32!

### Summary of changes

On Fridays, from 2-10:00 pm CT –– 
* we scrape all events, on the hour, 
* we scrape recently updated events, at 30 and 45 after the hour
* we scrape all bills, at 5 after the hour
* we scrape recently updated bills, at 35 and 50 after the hour

This minimizes the load we place on Legistar, which should prevent an abundance of 104s.
