### ISSUE TITLE
Solr out-of-sync with Metro councilmatic due to passively toggling bills from private to public

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#421]
On Friday night, the Metro councilmatic database had six more bills that the Solr index.

```
'ocd-bill/320c7b0f-a411-47d6-ba8b-09fd43132794', 'ocd-bill/124fb0e8-5bec-4d20-bcf7-5544297b81c6', 'ocd-bill/9bf58499-3a23-44ec-85d0-f25de8bac406', 'ocd-bill/fe0c161d-8c4b-4baf-ab55-9998acc7edb4', 'ocd-bill/2384c653-9a55-4ede-b549-4c294735f910', 'ocd-bill/6f7b74cc-4bc0-4334-9435-de8293eff85b'
```

These bills all have the title `RECEIVE General Public Comment`, and they were created on March 4. 

### What happened?
It seems that these bills went from being restricted to non-restricted, once their respective agendas became public (i.e., set to "passed"): https://github.com/datamade/la-metro-councilmatic/blob/20ae25d15749570d02086bad4314f506a9e4ce36/lametro/models.py#L21

`update_index` only considers bills updated in the last hour. In other words, bills passively moved from private to public are not included in updating the Solr index.  

### Solution
I think we could safely increase the `age` argument for `update_index` to include more bills, or we could rebuild the index once a night. These adjustments would be made in the cron:
https://github.com/datamade/la-metro-councilmatic/blob/master/scripts/lametro-crontasks

**Comment by hancush** [comment]
@reginafcompton are there pros/cons to your proposed solutions? which would you recommend?

**Comment by reginafcompton** [comment]
[The documentation for the `age` argument](https://django-haystack.readthedocs.io/en/master/management_commands.html#update-index) indicates that, if we omit it, Haystack defaults to None, i.e., Haystack updates the entire index.

For reference, here's where the age argument comes into play: 
https://github.com/django-haystack/django-haystack/blob/4910ccb01c31d12bf22dcb000894eece6c26f74b/haystack/management/commands/update_index.py#L253
https://github.com/django-haystack/django-haystack/blob/802b0f6f4b3b99314453261876a32bac2bbec94f/haystack/indexes.py#L166

I'd suggest that we run a full update once per hour in the cron. The index for Metro is relatively small (under 2000 bills): it only takes a few minutes.

**Comment by reginafcompton** [comment]
This error occurred again, last night! https://sentry.io/organizations/datamade/issues/913978469/?project=137567&referrer=webhooks_plugin&statsPeriod=14d

I'll update the crontab today, as suggested above.

**Comment by reginafcompton** [comment]
I updated the crontab. It now runs the full data pipeline at 55 after the hour, but removes the `age` argument from `update_index`. 

According to `/var/log/syslog`, the crontask runs as expected:

```
Apr  2 18:55:01 ip-10-0-0-102 CRON[2282]: (datamade) CMD (/usr/bin/flock -n /tmp/lametro_dataload.lock -c 'cd $APPDIR && $PYTHONDIR manage.py import_data >> /var/log/councilmatic/lametro-importdata.log 2>&1 && $PYTHONDIR manage.py refresh_pic >> /var/log/councilmatic/lametro-refreshpic.log 2>&1 && $PYTHONDIR manage.py compile_pdfs >> /var/log/councilmatic/lametro-compilepdfs.log 2>&1 && $PYTHONDIR manage.py convert_attachment_text >> /var/log/councilmatic/lametro-convertattachments.log 2>&1 && $PYTHONDIR manage.py update_index --batch-size=100 >> /var/log/councilmatic/lametro-updateindex.log 2>&1 && $PYTHONDIR manage.py data_integrity >> /var/log/councilmatic/lametro-integrity.log 2>&1')
```

I close the issue and resolve the one in Semaphor! cc: @hancush
