### ISSUE TITLE
Add subject autocomplete to the search bar

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#433]
### Behavior

1. When a user enters a search term, auto-suggest topics based search bar input
2. If the user issues a plain text query, e.g., types "bus" and hits enter/clicks the magnifying glass, search functionality is unchanged
3. If the user selects a suggested topic, return results matching the selected subject facet, rather than the results of a free text search

### Implementation

- [x] Add a JavaScript event listener to the search bar that POSTs queries as they're typed to SmartLogic's `hints` endpoint, and populates a dropdown of autocomplete suggestions from the response. Each option should display the label, and have a value equal to the topic's GUID. 
- [x] Write an adapter that accepts a GUID and returns the corresponding label in the Councilmatic database. _N.b., using this adapter, rather than querying with the label from the response, hedges against unexpected behavior in the event that a label has changed in Semaphore since the last sync with Legistar/Councilmatic._
- [x] When a user selects an option, feed the GUID to the adapter to construct and issue a search on the subject facet.

**Comment by jmithani** [comment]
Adapter implementation plan:

1. Create `/topic/` endpoint to query with a GUID.
2. From given GUID, `SubjectGuid.objects.get(guid=<param>)`.
3. Return the selected `SubjectGuid` name.

**Comment by hancush** [comment]
@jmithani sometimes, there will be duplicate guids in the lookup table. if that is the case, you will want to grab the name of the subject that also appears in the main `Subject` model. can you update point two to reflect this?

**Comment by hancush** [comment]
n.b., haystack defaults to returning no results if a search is conducted without a query term. to enable topic search, we will want to override this to return all results: https://github.com/django-haystack/django-haystack/blob/802b0f6f4b3b99314453261876a32bac2bbec94f/haystack/forms.py#L41
