### ISSUE TITLE
Create an Archive Search page

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#435]
Google Search Appliance is dead. :( Which means Metro's Board Archive search, linked in the header of the website, is dead. 
![image](https://user-images.githubusercontent.com/28063988/56998645-dbca2000-6b60-11e9-946b-e26d27c1762c.png)

Omar has created a Google Custom Search of the Board Archives: https://cse.google.com/cse?cx=007602828488985387677:mhzmxh6ty20 Is it possible to create a page on boardagendas.metro.net and embed this search tool? 

The page linked above has nothing but a search box. It would be ideal to have the other content/headers from boardagendas.metro.net to give it context. Note: this would be temporary, as we plan to import all board archive documents into Legistar in the future.  

---
Search box code:
Get code for search box
Copy the following code, and paste it into a DIV element in your site's BODY section, where you want the search box to render.

Note: For the most cross-browser compatibility, it is recommended that your HTML pages use a supported doctype such as !DOCTYPE html. CSS hover effects require a supported doctype.

<script>
  (function() {
    var cx = '007602828488985387677:mhzmxh6ty20';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:searchbox></gcse:searchbox>

You can customize the Search UI even more, or add per page customization by following the full documentation on CSE element: https://developers.google.com/custom-search/docs/element

Search Results code:
Get code for search results
Copy the following code, and paste it into a <div> element in your site's <body> section, where you want the search results to render.

Note: For the most cross-browser compatibility, it is recommended that your HTML pages use a supported doctype such as <!DOCTYPE html>. CSS hover effects require a supported doctype.

<gcse:searchresults></gcse:searchresults>

You can customize the Search UI even more, or add per page customization by following the full documentation on CSE element: https://developers.google.com/custom-search/docs/element

**Comment by hancush** [comment]
hi, @shrayshray! this is definitely doable. do you want the "archive search" option you circled to lead to new custom search engine page?

**Comment by shrayshray** [comment]
@hancush Yes. If We'd like to have the "Archive Search"  navigation link to a new webpage, which has the custom search embedded.

**Comment by hancush** [comment]
@shrayshray got it! here are two screenshots of the new page. the first is how the page looks when the user lands there. the second is how it looks when a search is run. how does it look?

<img width="1440" alt="Screen Shot 2019-05-14 at 10 26 30 AM" src="https://user-images.githubusercontent.com/12176173/57710562-d07ff580-7632-11e9-94fb-fc9030aec76d.png">

<img width="1440" alt="Screen Shot 2019-05-14 at 10 26 37 AM" src="https://user-images.githubusercontent.com/12176173/57710561-d07ff580-7632-11e9-8f5e-dcb02deca53d.png">

note, there is a sidebar on the right with information about what this search is. i think it would be helpful to explain to the user how this search is different from the main search on the site. if this makes sense to you, can you provide a paragraph or two of text? many, many thanks!

**Comment by shrayshray** [comment]
@hancush this looks great, thank you!! 

Header: "Archives Search: Metro’s Board Records 1993-2015" 

Sidebar text: "Search Metro’s Board Records 1993-2015 and its Predecessors Meeting Minutes 1951-1993
Search the LACMTA Board of Directors records from 1993 to 2015. Includes Meeting Minutes for Metro predecessor public agencies: Los Angeles Metropolitan Transit Authority (LAMTA 1951-1964, incomplete), Southern California Rapid Transit District (SCRTD 1964-1993), Los Angeles County Transportation Commission (LACTC 1977-1993) and Rail Construction Corporation (RCC 1989-1993). Subcategories to refine your search will appear just below the search box after a search is initiated."

**Comment by hancush** [comment]
thanks, @shrayshray – changes are cooking in #439. i'm aiming to get them on the staging site for your review tomorrow!

**Comment by hancush** [comment]
good morning, @shrayshray! the standalone page is live on the staging site, and the links referencing the old board box search have been updated: https://lametro.datamade.us/

if this looks ok to you, i'll push it to the live site!

**Comment by hancush** [comment]
this is live at https://boardagendas.metro.net/archive-search!
