### ISSUE TITLE
Capture Subject's GUID in LA Metro data model

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#436]
**Warning:** Thinking "out loud" ahead.

Each bill subject has an associated GUID that should be captured in the Councilmatic database, in order to facilitate lookups between the Councilmatic and Semaphore systems. (Subject labels are not guaranteed to be consistent.)

That means we need to incorporate the GUID into the data model. There are a couple of options for doing this:

1. [Multi-table inheritance](https://docs.djangoproject.com/en/2.2/topics/db/models/#multi-table-inheritance). In other words, create a Metro-specific `Subject` subclass with an associated `guid`. 
2. Create a lookup table with a model like `SubjectGuid`, which has:
    - A foreign key to a `Subject` and a character field with the associated GUID.
    - ✅ Character fields for both the subject name and GUID, linkable to the core `Subject` by name.

Note that the `import_data` script deletes and re-imports subjects each time a bill is imported, in order to capture the removal of subjects, so both the multi-table inheritance and the lookup table with a foreign key would require changes upstream, or subclassing the `import_data` and removing implicated `LAMetroSubject` or `SubjectGuid` objects, so deletions can be made from the core `Subject` table, without raising an exception about orphaned references.

However, a lookup table containing the distinct subject and GUID pairings would not require additional changes and, because new topics from SmartLogic are only ported to Legistar once per day, it would only need to be updated once per day, to capture any changes and to remove any unused pairs. We could even take a blunt approach and delete and reimport all pairings from the matter indexes list. This approach would have the added benefit of removing the need to orchestrate this process with a scrape/data import. It also would be an obvious candidate for a callback to be run when SmartLogic has completed its sync with Legistar.

**Comment by hancush** [comment]
Related to #432.

**Comment by hancush** [comment]
Pre-requisite of #437.

**Comment by hancush** [comment]
N.b., the actual task here is: Write a Django model to function as a lookup table between distinct subject-GUID pairs. This model should have fields for the subject name and GUID. 

It would also be good to think about constraints that would help us ensure the data looks the way we expect. For example, subject names may be unique. (Relatedly, we might also think about constraints for the core `Subject`, too, like all subject names appear in the lookup table. This can happen a separate issue.)

**Comment by jmithani** [comment]
Closed by #438
