### ISSUE TITLE
Meetings: Add text to sidebar box

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#442]
Please add this text in the sidebar of the [Meetings page](https://boardagendas.metro.net/events/): "In addition to the Board of Directors meetings, Metro also has appointed Advisory Committees which meet. Learn more in the ["Advisory Meetings" tab here](https://www.metro.net/about/about-metro/)."
![image](https://user-images.githubusercontent.com/28063988/57815123-01435600-772b-11e9-8a8e-e1497d09848e.png)

**Comment by jmithani** [comment]
@shrayshray I made the change and it's live on the staging site: https://lametro.datamade.us/events/

If it looks good, I'll deploy it!

**Comment by shrayshray** [comment]
@jmithani looks great, please deploy!
