### ISSUE TITLE
Links on About page.

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#45]
The links to "Legislation Type" do not work. Fix this.

**Comment by hancush** [comment]
fwiw [i opened an issue in django-councilmatic](https://github.com/datamade/django-councilmatic/issues/93) for this, bc the links seem to be broken on chi and nyc councilmatic also. if i'm not just seeing the tip of the iceberg (always possible!!) it seems like a case issue/quick fix!

**Comment by hancush** [comment]
fwiw i opened [an issue](https://github.com/datamade/django-councilmatic/issues/93) in django-councilmatic for this bc it appears to be broken in chi and nyc councilmatic, too. (the query just needs to be lowercased methinks!)

**Comment by reginafcompton** [comment]
Fixed!
