### ISSUE TITLE
Improving event scraping.

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#457]
With some changes in the Legistar API, [we could improve the reliability of scraping events](https://github.com/opencivicdata/python-legistar-scraper/issues/92#issuecomment-506016631). If the video and audio links were in Legistar API we could also dramatically speed up event scraping since we would no longer need to visit the InSite website at all.

The Legistar API has a place for video links, but they are all blank for Metro. Could this be different?

**Comment by fgregg** [comment]
For example, here's the API entry for a meeting that does have an audio link http://webapi.legistar.com/v1/metro/events/1397

But there is an audio link on the InSite page https://metro.legistar.com/MeetingDetail.aspx?LEGID=1397&GID=557&G=A5FAA737-A54D-4A6C-B1E8-FF70F765FA94

Could that link be in the "EventVideoPath" entry in the API?

**Comment by jmithani** [comment]
@fgregg and I started working on this over at [branch tk].

We need to account for the following:

- cases where there isn't anything in web
     - missing url 
     - url doesn't resolve

future: make checking web contents optional, add argument to indicate
     - like after a certain date?

- might need to adjust video link keys used in LA Metro scraper
- above all, make sure the scraper still works

we anticipate that this change will cut the time for scraping in half.

**Comment by hancush** [comment]
We did this! https://github.com/opencivicdata/scrapers-us-municipal/pull/290
