### ISSUE TITLE
add ability to construct queries from autosuggested terms

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#460]
in the main search bar, if the user selects an autosuggested term, add the term to the search box with  some styling to set it apart from plain text and "reset" suggest functionality.

for example, a user types in "blue" and selects the "blue line" suggestion. add "blue line" to the search box with a visual indicator that it is a tag, e.g., a blue highlight. if the user types additional text, only that text (not "blue line") is used to gather additional hints.

**Comment by hancush** [comment]
n.b., this would involve transitioning from an input to a `contenteditable` div to allow for styling. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

**Comment by hancush** [comment]
@shrayshray I'm excited to share the first iteration of this with you! I've deployed it to the staging site: https://lametro-upgrade.datamade.us.

Let me know what you think.

**Comment by camachoo** [comment]
So.....  I was testing yesterday and wanted to continue today, but this morning I am getting:
502 Bad Gateway
________________________________
nginx/1.14.0 (Ubuntu)

________________________________

**Comment by camachoo** [comment]
It's working now.  First observations:  I am not getting the query builder functionality for some reason.  Also yesterday, from the front page, I was able to properly select the tags, but they wouldn't show in the search bar. When I completed the search, the next page showed zero results.  However, from the search results page I was able to properly select a single tag.  Unfortunately, I got pulled away at this point and didn't continue my test.  I was going to to that this morning.

This morning I am getting the following functionality.  When selecting a tag from the drop down list, a search is executed immediately with zero results on the results page. The same happens rom the results page.

Maybe you all are working on this?
________________________________

**Comment by hancush** [comment]
@camachoo You caught us in the middle of a deployment! I've put the query builder back on staging, and the search index has been populated, so you should see results when you expect them.

Also, can you send screenshots (or even better, use [LiceCap](https://www.cockos.com/licecap/) to make a GIF) and let me know what browser you are using? Thank you!

**Comment by hancush** [comment]
Howdy, @shrayshray! I pushed some improvements to the staging site to improve results for keyword matching and update tag matching so that any result with at least one of the selected terms is returned. Do you think you and @camachoo will have time to review this over the next few working days? I won't be able to deploy this _and_ the faceting improvements from #622 to staging at the same time, so want to coordinate to make sure the feature you want to test is live, when you want to test it!

**Comment by shrayshray** [comment]
@hancush yes, I can test this. When I tried just now though, any word I entered displayed "The results could not be loaded" instead of suggestions:
![image](https://user-images.githubusercontent.com/28063988/83181942-6e2d5200-a0da-11ea-8cb6-0623c0fb95d9.png)

![image](https://user-images.githubusercontent.com/28063988/83182008-869d6c80-a0da-11ea-9709-48ba0ee6a32f.png)

**Comment by hancush** [comment]
@shrayshray Whoops! Updated the site to query the right SmartLogic instance. It's working for me – can you [hard refresh](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.XtAPUp5KjOQ), and try again?

**Comment by shrayshray** [comment]
@hancush yes, it's working now!

**Comment by shrayshray** [comment]
@hancush the actual search results from constructed queries are great in my tests so far. I've tested text + concept + concept, keyword + keyword + text, and other variations with consistent performance.
One thing I did find a little confusing: the text typed into the search field is shown in the suggestion list even when there is not a matching concept. If I select the non-concept suggestion, it's added to the search field as if it were a concept, even though it gets sent as a text search query.

In the example below, "student" is not a Legistar enabled concept, but it appears as a suggestion, and when I select it, it's added to the search bar and looks like a concept. I think it would be better to only show concepts in the suggestions, unless there's a systematic requirement to present them this way.

![image](https://user-images.githubusercontent.com/28063988/83191300-a2a80a80-a0e8-11ea-9503-1ab097f68d2b.png)

**Comment by hancush** [comment]
@shrayshray Yay! I hear you on the interface. The challenge is that there's not a great way to add a keyword to your search if we don't show it to the list. What if I prefixed the first term (the keyword) with `Keyword:` to make it clearer what's going on?

**Comment by shrayshray** [comment]
@hancush I think adding a prefix could help mitigate any confusion over selecting a concept versus keyword. But on the other hand, we're not expecting users to bring with them any understanding of the difference. 
I guess the other concern about needing to have keywords show in the suggestion list is that if I execute my search before it appears there, the query is empty and returns zero results. 
So if I search as I normally would on any other search engine or website - quickly type the query and Enter - I get nothing. I guess we could add instructions "wait for your search terms to appear in the list below the search box" or something, but it strikes me as overly cumbersome.

It's good though that if I wait for it to appear in the suggestion list, it will automatically be added to the search query even if I don't select it. 
Those are some initial thoughts, I'll keep testing and I'd like to hear what Omar thinks after testing, too!

**Comment by hancush** [comment]
@shrayshray Any outlook on when @camachoo can take a look? I imagine things are quite busy for you all right now, just let me know when you know. 🙏

**Comment by shrayshray** [comment]
@hancush Omar and I just went through this, and a few thoughts:
1. Is it possible to still return search results when a user types in text and hits enter before the drop down with suggestions appears? Right now if the search is submitted before the drop down appears, it returns zero results.

2. We're assuming it's not possible to not show what the user typed at all, and only show concept suggestions, but still allow for free text to be used in the search - is this correct?

3. If 2. is correct, we think the following prefixes would be helpful - instead of "keywords:", prefix of "what you typed". And below that, in front of concepts, "Suggested terms for query builder:"

**Comment by hancush** [comment]
@shrayshray 

1. Sure.
2. Correct – that would be very challenging.
3. Will add those prefixes.

Will notify you when these changes are in! In the meantime, query building will be removed from the staging site. Hope to stage the first draft of enriched faceting for your feedback in the next day or two.

**Comment by hancush** [comment]
Update: These changes are in and live on the staging site: https://lametro-upgrade.datamade.us

Think your suggestions made this a lot more sensible! Thoughts, @shrayshray and @camachoo?

**Comment by shrayshray** [comment]
@hancush The prefixes look good!
It also looks like you've added some helpful text about the number of characters required for suggestions!:
![image](https://user-images.githubusercontent.com/28063988/83928203-b9cba580-a743-11ea-8063-b99b3b27f3f9.png)
But is there a requirement/constraint on the matching term to also be three characters ... or? Could you let us know, or remind us, what is the logic on how the number of characters impacts concept matches?
A test, using student again:
a. "stu" has no matches
![image](https://user-images.githubusercontent.com/28063988/83928413-96552a80-a744-11ea-9384-8e9b7dc5bee3.png)

b. "stud" gets stud matches
![image](https://user-images.githubusercontent.com/28063988/83928427-a3721980-a744-11ea-8cb0-75691ae5c9d7.png)

c. "stude" = no matches
![image](https://user-images.githubusercontent.com/28063988/83928445-aec54500-a744-11ea-9c32-1f67aff709e1.png)

d. "studen" = no matches
![image](https://user-images.githubusercontent.com/28063988/83928457-ba187080-a744-11ea-92b8-f125878fef1e.png)

e. "student" = student concept matches
![image](https://user-images.githubusercontent.com/28063988/83928473-c6043280-a744-11ea-8f42-eb20b5c3108b.png)

**Comment by hancush** [comment]
@shrayshray I set the limit to 3 to reduce the number of requests to the SES API, figuring that results for 1 or 2 characters would be too noisy (i.e., there isn't enough to meaningfully guess what someone wants to discover with that few characters). I can turn off the character limit if you disagree. Let me know!

As far as results go, we don't have control over that, apart from potentially changing the endpoint we query. IIRC, we piloted `hints` but it did not return obvious matches, so we transitioned to `concepts` because it generally yielded the best results, in particular for free text search. See: https://github.com/datamade/la-metro-councilmatic/pull/496.

Note that this has _not_ changed during query builder implementation: The suggestions you see on staging should mirror the ones on the live site. If you have questions about results, then it would be best to open a thread with Steve (and please Cc us, as it will be useful information on our end).

I'd also recommend decoupling that thread from this enhancement, as it not a problem introduced by this change set, so I don't think it should block it.

**Comment by shrayshray** [comment]
@hancush Understood. We plan to loop Steve in on the concerns about suggestions and meet when you return to discuss, and treat it as a separate issue. We'd also like to hold off on implementing this update until you return.
And the character limit of 3 seems reasonable, so let's not reduce the limit - the concern over 3-character entries not retrieving a match will be addressed with Steve. 
Thank you!

**Comment by hancush** [comment]
@shrayshray Thanks for the update! Are you saying I should hold off on the query builder update?The functionality from the query builder (namely, separating out terms) is a building block for related topics (#464), so that work will be blocked until we can bring this in. Let me know.

**Comment by shrayshray** [comment]
@hancush got some feedback from the Metro team on this!
On reported issue is if you type in the search bar, then click back into it without selecting a term from the drop down, the search bar clears out any entered text. The same thing happens if you click the magnifying glass search button after typing in the search bar and not selecting anything from the drop down.

**Comment by hancush** [comment]
Good catch, @shrayshray. Just deployed a fix that retains input in both of those instances. Give it a shot on staging: https://lametro-upgrade.datamade.us/

(Hard refresh first, to ensure you have the latest scripts!)

**Comment by shrayshray** [comment]
@hancush I've been testing this for the past hour or so and it looks as expected. I'm still not totally thrilled with the suggestions, but understand that's out of scope and any future solutions would involve additional work with Smartlogic. So, for what we were expecting from Datamade, this is fantastic - thank you! Unless Omar has additional feedback, I think we're good to go.

**Comment by hancush** [comment]
Deployed!
