### ISSUE TITLE
allow for multiple values of report type

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#462]
metro bills can often include many kinds of report. as such, metro has defined report types as smartlogic tags, so that a report can be classified as multiple types.

- [ ] source a canonical list of report type tags from metro.
- [ ] define some property on the bill model to return the appropriate array of tags.
- [ ] investigate whether haystack index needs to be updated to accommodate the change in model. see: [faceting docs](https://django-haystack.readthedocs.io/en/v2.4.1/faceting.html#switch-to-the-facetedsearchview-and-facetedsearchform).

**Comment by hancush** [comment]
This feels related to #463... @shrayshray, how is a term classified as a report type in Semaphore? We can likely extract this information from their API, but again, we'd want to wait on implementation until the changes to topics in our end are made in the upgrade.

**Comment by hancush** [comment]
Same here, @shrayshray – any guidance on how terms are classified as report types in Semaphore?

**Comment by shrayshray** [comment]
@hancush the report types we want to use are in the Concept Scheme "Board Report Types".
Here's a note Omar and I dug up from way back about this facet:

> Report Types (REPLACES: current “Filter by Report Type”) - Concept Scheme: “Board Report Types” & “System: Legistar” equals true

**Comment by hancush** [comment]
@shrayshray I pulled concepts in the given concept scheme using this SES API query: https://cloud.smartlogic.com/svc/0dcee7c7-1667-4164-81e5-c16e46f2f74c/ses/CombinedModel/concepts/Board Report Types.json?FILTER=AT=System: Legistar

Here are the results: https://docs.google.com/spreadsheets/d/1d1qiYxcq9UunMAwG9s1Ghb2AIszIUpCvq3QhwbPCms8/edit?usp=sharing

The top of the list looks good, but some of the terms further down the list don't seem to belong. Any advice for pulling the correct list of terms from the API?

If you want to use a fixed set of board report types, instead, can you provide a list? Many thanks!

**Comment by hancush** [comment]
Update: Connected with Steve, who gave me some super helpful guidance. Have enough to move forward here, hope to stage this change in the first half of next week!
