### ISSUE TITLE
investigate enriched faceting from smartlogic tags

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#463]
metro has created several tag groupings that would be useful to include as facets. these include:

- lines/ways, e.g., "bus line", "rail line"
- phase
- project type
- location
- motion by
- topics/subjects

these will all be imported into legistar as matterindexes. there are some examples in the test api now.

**Comment by hancush** [comment]
Hi, @shrayshray! Is there any way to add information about what grouping an index belongs to the indexes listing in the Legistar API? Otherwise, I bet we can grab it from the Semaphore API. Is a grouping equivalent to a class in Semaphore?

In any case, the way topics are represented in our data is changing in the upgrade, so we will probably want to wait on implementation here until those changes come in.

**Comment by hancush** [comment]
Hey, @shrayshray – want to reup the question here: Is there any way to add what grouping a matter index belongs to, to the Legistar API?

**Comment by shrayshray** [comment]
@hancush These facets are based on concept Class.

i.	Lines / Ways - Class: “Transportation Method” and all of its Subclasses & “System: Legistar” equals true
ii.	Phases - Class: “Transportation Phase” and all of its Subclasses & “System: Legistar” equals true
iii.	Projects - Class: “Project” and all of its Subclasses & “System: Legistar” equals true
iv.	Locations - Class: “Location” and all of its Subclasses & “System: Legistar” equals true
v.	Significant Dates - Class: “Significant Dates” and all of its Subclasses & “System: Legistar” equals true
vi.	Motion by -  Class: “Board Member” and all of its Subclasses & “System: Legistar” equals true
vii.	Topics/Subjects (REPLACES: current “Filter by Topic”) – Any term/tag not covered above & “System: Legistar” equals true

**Comment by hancush** [comment]
@shrayshray I know that it's _possible_ for a concept to have more than one class, but in practice, will any of the concepts in the taxonomy you describe ever belong to more than one of the classes we're using for faceting? For example, can a concept be both a line and a location?

**Comment by shrayshray** [comment]
@hancush it's highly unlikely we'll have any concepts with two classes which are also two different facets. I can't think of any existing examples, or any cases where this might occur. On any concepts I've seen with two classes assigned, only one of them is a facet.

**Comment by hancush** [comment]
@shrayshray Very helpful! Thank you!

**Comment by hancush** [comment]
@shrayshray @camachoo New Lines / Ways and Phase facets are live on the staging site! (As a bonus, I've also fixed #592.) 

https://lametro-upgrade.datamade.us/search/

When you view the empty search and toggle open the new facets, do they contain the values you expect?

It'd also be helpful if you could play with various combinations of filters on search results:

- Select facets from the filters in the sidebar, and confirm they are applied correctly.
- Click a topic from a search result and confirm results for the related facet (lines / ways, phase, or subject) are returned.

Also check out legislation pages, where I've grouped topics by facet.

<img width="490" alt="Screen Shot 2020-06-04 at 9 55 02 AM" src="https://user-images.githubusercontent.com/12176173/83772876-7bea5680-a649-11ea-8aaa-8d91e1dd2dc2.png">

If this all looks good so far, I'll set about adding the remaining new facets. Let me know what you think!

**Comment by camachoo** [comment]
I like the way that looks....  Maybe a little more room for text to show?

[cid:ceed7d04-3c0e-4ffd-841c-28458ace1f28]
________________________________

**Comment by hancush** [comment]
@camachoo I assume you mean in the filter side bar? Good call. Just deployed a patch.

<img width="478" alt="Screen Shot 2020-06-04 at 1 34 57 PM" src="https://user-images.githubusercontent.com/12176173/83797411-37ba7e80-a668-11ea-9e58-0864200dd0f9.png">

**Comment by shrayshray** [comment]
@hancush could we sort the faceted concepts alphabetically, instead of by occurrence count?

**Comment by hancush** [comment]
@shrayshray Sure thing. Any other feedback?

**Comment by hancush** [comment]
@shrayshray Just deployed a patch to order faceted concepts alphabetically, with selected concepts first. (Same behavior as combined topics was originally.) If this looks good to you both, I'll add the remaining topics next week! Let me know. 

P.s., I have changes ready to deploy for the query builder (#460) once you're done testing the new facets.

**Comment by shrayshray** [comment]
@hancush yes, this looks great!!

**Comment by hancush** [comment]
Hi again, @shrayshray! I'm not getting any results for the `Location` and `Significant Dates` classes. Are there any terms of those class in SES?

**Comment by hancush** [comment]
Also, all of the new facets (plus report types from #462) have been implemented and are live on staging: https://lametro-upgrade.datamade.us/search/. 

Can you have a look and let me know if they appear and are behaving as expected?

As I mentioned, I'm not getting any results from SES for the Location and Significant Dates classes, but as terms are added, they should appear as facets on the site. Let me know about those classes, and we can get this bundle of issues out the door!

**Comment by shrayshray** [comment]
@hancush thank you! I'll take a look. Regarding Locations, we recently made some changes to the class names - they're in the test model right now but will be pushed to production soon. The new top-level class name is "All Locations". So the criteria for this facet should now be:
iv. Locations - Class: “All Locations” and all of its Subclasses & “System: Legistar” equals true

**Comment by shrayshray** [comment]
@hancush re: your earlier comment asking whether there are any terms for those Location and Significant Dates classes in SES - Yes (Although, see above - the locations class is now "All Locations"). Here is a report that has one from each tagged:
https://lametro-upgrade.datamade.us/board-report/2020-0129/
 Location - "Long Beach"
Significant Dates - "Board Approved a Motion"
Here's another: https://lametro-upgrade.datamade.us/board-report/2019-0806/
Location - "City of Los Angeles" "Inglewood" and others
Significant Dates - "Board Approved a Motion"

Are those examples helpful? Would a list of terms or something be more helpful?

**Comment by shrayshray** [comment]
Ah, okay - just figured out what might be causing the problem. We gave you the wrong class name for Significant Dates. It's just "Date". So:
v. Significant Dates - Class: “Date” and all of its Subclasses & “System: Legistar” equals true

**Comment by hancush** [comment]
@shrayshray Got it! Updated both class names. We're pulling from the live SES instance, so no location topics yet, but Significant Dates are up @ https://lametro-upgrade.datamade.us/search/.

**Comment by hancush** [comment]
(Also, just my prelim two cents, but breaking the massive subjects facet into these smaller topical facets provides such a better search experience, especially when you don't have a ton of context for the subject matter, like me. ^_^)

**Comment by shrayshray** [comment]
@hancush I agree, this is awesome! Definitely a better experience! All looks as expected to me.

**Comment by hancush** [comment]
Woohoo! Any update on when you'll launch the location class, @shrayshray? I can always deploy this today, and rebuild the index when those topics come through. Let me know.

**Comment by camachoo** [comment]
Please try again with the class “All Locations”.  Although we probably have to breakup this facet also into two.


  1.  Metro Specific Locations: Class= All Transportation Locations
  2.  Geographic Locations: Class= All Locations (except not) All Transportation Locations

These two also need to have the attribute System: Legistar.

I forget, do we know how to exclude subclasses?  Maybe we can get a call with Steve to hammer out some of these issues.

Let me know if the “All Locations” works.

Omar Camacho
LA Metro
Sr. Manager, Systems Projects
Research & Records Information Management
213.922.2335 W
camachoo@metro.net
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro’s mission is to provide world-class transportation for all.

**Comment by hancush** [comment]
@camachoo Have these classes been launched? I'm not getting any results from the live SES instance: `https://cloud.smartlogic.com/svc/0dcee7c7-1667-4164-81e5-c16e46f2f74c/ses/v1.2/CombinedModel/terms.json?FILTER=CL=All Locations`

**Comment by hancush** [comment]
Not getting any from the test instance, either: https://cloud.smartlogic.com/svc/0ef5d755-1f43-4a7e-8b06-7591bed8d453/ses/v1.2/CombinedModel/terms.json?FILTER=CL=All Locations

:-/

**Comment by shrayshray** [comment]
From Hannah: "Per Steve:
The SES filter FILTER=CL=<Class> only returns concepts that have that class explicitly assigned. There's no inheritance. However, multiple filters can be combined into an OR type filter to get the same effect

So, can you provide a list of classes for each facet?" 

Here's a comprehensive update to the original list of classes, which includes subclasses.
i

1.	Lines / Ways - Class: “Transportation Method” and all of its Subclasses & “System: Legistar” equals true. Subclasses are:
- Bus Line
- Bus Way
- Rail Line

2.	Phases - Class: “Transportation Phase” & “System: Legistar” equals true.
3.	Projects - Class: “Project” and all of its Subclasses – EXCLUDING “Transportation Phase” & “System: Legistar” equals true. Subclasses to include:
-	Project Development
-	Project Finance
        -- Capital Project
        -- Construction Project
        -- Grant Project
        -- Other Working Project

4.	Metro Specific Locations: Class: “All Transportation Locations” and all of its Subclasses & “System: Legistar” equals true. Subclasses to include:
-	Alignment
-	Division
-	Employee Parking Lot
-	Pank ‘n’ Ride
-	Radio Station
-	Route
-	Station
-	Surplus, Temporary And Miscellaneous Property
-	Terminal
-	Transportation Location

5.	Geographic/Administrative Locations - Class: “All Location” and all of its Subclasses - EXCLUDING “All Transportation Locations” & “System: Legistar” equals true. Subclasses to include:
-	Administrative Division
      -- Electoral Districts
      -- Sector
-	Corridor
-	Geographic Location
      -- City
      -- Country
      -- County
      -- Neighborhood
      -- State
      -- Unincorporated Area
-	Point of Interest
-	Subregion

6.	Significant Dates - Class: “Dates” & “System: Legistar” equals true
7.	Motion by - Class: “Board Member” & “System: Legistar” equals true
8.	Topics/Subjects (REPLACES: current “Filter by Topic”) – Any term/tag not covered above & “System: Legistar” equals true

**Comment by shrayshray** [comment]
@hancush This looks amazing!!!! I comfortable with pushing to production.

**Comment by hancush** [comment]
Deployed!
