### ISSUE TITLE
Board and Committees: Fy19/20 members not showing

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#467]
The Board Members for FY19/20 were updated in Legistar Friday afternoon, but are still not showing on https://boardagendas.metro.net/board-members/ or https://boardagendas.metro.net/committees/. Can you please make sure they new assignments display on the site as soon as possible?

The full Board for July 1, 2019 - June 30, 2020 is below, and committee assignments are here: [Board Committees - July 2019 - June 2020.pdf](https://github.com/datamade/la-metro-councilmatic/files/3369579/Board.Committees.-.July.2019.-.June.2020.pdf)

James Butts, Chair   
Eric Garcetti , Vice Chair   
Hilda Solis, 2nd Vice Chair   
Kathryn Barger   
Mike Bonin   
Jacquelyn Dupont-Walker   
John Fasana   
Robert Garcia   
Janice Hahn   
Paul Krekorian   
Sheila Kuehl   
Ara Najarian   
Mark Ridley-Thomas

**Comment by jmithani** [comment]
Taken care of with https://github.com/opencivicdata/scrapers-us-municipal/pull/285
