### ISSUE TITLE
Committees: Update to FY19/20 members

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#471]
There have been changes to two committees:

CONSTRUCTION COMMITTEE
Jaquelyn Dupont-Walker was added as a member.
EXECUTIVE MANAGEMENT COMMITTEE 
1. Eric Garcetti is Vice Chair (was 1st Vice Chair)
2. Hilda Solis is a Board Member (was 2nd Vice Chair)

I've made these changes in the Legistar, could you make sure they're updated on the site?

**Comment by jmithani** [comment]
Hi @shrayshray,

Both of those have been updated on their respective committee pages.
