### ISSUE TITLE
Reports: Add keyword list to Report page

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#475]
Display a list of the keywords a report is tagged with to the right of the report PDF on the Report page. Boxes in mock-up below are just to mark the area and don't need to be included in the actual design:
![image](https://user-images.githubusercontent.com/28063988/62242431-00b47600-b390-11e9-852a-2fdaaf178fa8.png)

**Comment by shrayshray** [comment]
@hancush I don't think this is done? I still don't see tags on the report pages.

**Comment by hancush** [comment]
@shrayshray hm, it looks like the work got done in https://github.com/datamade/la-metro-councilmatic/pull/491, but we didn't push the changes to production.

this is an oversight on my part. right now, autocomplete is deployed to the staging site for your input. can you let me know when you've reached a stopping point with autocomplete testing? when that happens, i'll put this change on staging for your sign off, then get it out the door!

**Comment by hancush** [comment]
this has been deployed!
