### ISSUE TITLE
Board Meeting: Missing Agenda Packet

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#476]
The[ 6/27/19 Regular Board Meeting page](https://boardagendas.metro.net/event/regular-board-meeting-ba05088b6d26/) is missing the "Download Agenda and Attachments" link: 
![image](https://user-images.githubusercontent.com/28063988/62981123-513ec100-bddd-11e9-9c93-11b4ab1e570c.png)

**Comment by jmithani** [comment]
@shrayshray this has been resolved! https://boardagendas.metro.net/event/regular-board-meeting-ba05088b6d26/

**Comment by hancush** [comment]
for posterity: this was caused because of an error in the pdf merger for which we should have received an error notification, but didn't. we upgraded the sentry sdk to resolve the missing errors, and re-ran the merge for events to resolve the issue.

**Comment by hancush** [comment]
https://github.com/datamade/metro-pdf-merger/pull/20
