### ISSUE TITLE
Board of Directors: Chair and Vice Chair should be listed first

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#481]
Is it possible to list the Chair (James Butts) and Vice Chair (Eric Garcetti) first on the list of [Board of Directors](https://boardagendas.metro.net/board-members/), followed by other members in alphabetical order?

**Comment by hancush** [comment]
We're adding a centralized way to order board members in the upgrade (#512). Can this wait until then?

**Comment by hancush** [comment]
@shrayshray I just merged and deployed this to the staging site: https://lametro-upgrade.datamade.us/board-members/. What do you think?

**Comment by shrayshray** [comment]
@hancush the chair and vice chair are first - awesome!! Is it possible to list the other members alphabetically by last name instead of first?

**Comment by hancush** [comment]
Sure, I can get to this next week. (Taking Monday/Tuesday off.) Have a good weekend!

**Comment by shrayshray** [comment]
Thanks, Hannah! Hope you have a relaxing long weekend.

**Comment by hancush** [comment]
Hi, @shrayshray. Made the requested change. It's now live on staging: https://lametro-upgrade.datamade.us/board-members/

**Comment by shrayshray** [comment]
@hancush perfecto - thank you!

**Comment by hancush** [comment]
You're welcome! We're live: https://boardagendas.metro.net/board-members/
