### ISSUE TITLE
Board Reports - Identify searches by File ID and show the matching report first in results

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#487]
To address searches by File ID not returning the matching report first in the results list (e.g., someone types [2018-0101](https://boardagendas.metro.net/search/?q=2018-0101&search-all=on) in the search bar, and that report shows up 2nd): 
When someone searches using the File ID, identify this structure (20##-####) and assume they're looking for the matching report - have the matching report show up first in search results.

**Comment by hancush** [comment]
@shrayshray Bonus! I've implemented and deployed a fix for this, as well. The upshot is that I doubled the relevance score of the result with an identifier matching the query, so it's ordered first. This should work if the query contains multiple identifiers, too. We've done some successful testing on our end. Want to give it a go on yours?

**Comment by shrayshray** [comment]
@hancush wow - this is so exciting! Single identifier searches are working consistently. Multiple identifier searches aren't exactly what I'd expect, but they're good enough I'm not super concerned. One example is a query for "2020-0101 2020-0202" returns:
1. 2020-0201
2. 2018-0201
3. 2017-0201
4. 2020-0101
Since the single identifier result is what we were aiming for, I don't consider the results for multiple returning in not quite the right order an issue.

**Comment by hancush** [comment]
I will try one small change to get multiple IDs working. If that doesn't work, I'll go ahead and take the single ID search lvie and break ou t a separate issue for multi ID search for the ice b ox.

**Comment by shrayshray** [comment]
I received a user report of this happening again - searching for a report by file ID doesn't always display the exact match first. I tested and also found a few cases. Some examples:
2022-0037
2021-0222
2020-0220
2019-0089
Could you look into what might be causing this?

**Comment by hancush** [comment]
Sure, @shrayshray!
