### ISSUE TITLE
Home page: Text on Board Archive link

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#498]
On the homepage, below the search box, please change the text on the link to the Board Archive to "Search the Metro Board Archive from 1952-2015 (Board Boxes 1994-Present)"
![image](https://user-images.githubusercontent.com/28063988/66077472-eb390500-e514-11e9-8d89-7ecd08389efd.png)

**Comment by hancush** [comment]
This is live on the staging site! https://lametro.datamade.us/

Look ok, @shrayshray? If so, I'll deploy Monday.

**Comment by shrayshray** [comment]
Yes, looks great!

**Comment by hancush** [comment]
Woohoo! We're live. Closing.
