### ISSUE TITLE
Independent oversight committees on Councilmatic

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#502]
Get body type name and number over to Datamade for scraping.

**Comment by hancush** [comment]
@shrayshray Hi, Shelly! Is it your expectation that the oversight committees are added to Councilmatic prior to next week's meeting of the Measure M Independent Taxpayer Oversight Committee?

**Comment by shrayshray** [comment]
Yes, the oversight committees should be added to Councilmatic before the Measure M meeting next week.

**Comment by shrayshray** [comment]
BodyTypeName: Independent Taxpayer Oversight Committee 
BodyTypeId: 68

BodyName: Measure M Independent Taxpayer Oversight Committee
BodyId: 248

BodyName: Measure R Independent Taxpayer Oversight Committee
BodyId: 250

BodyName: Independent Citizen’s Advisory and Oversight Committee
BodyId: 251

BodyTypeName: Independent Taxpayer Oversight Committee (SAP)
BodyTypeId: 69

BodyName: Measure M Independent Taxpayer Oversight Committee (SAP)
BodyId: 254

BodyName: Measure R Independent Taxpayer Oversight Committee (SAP)
BodyId: 255

BodyName: Independent Citizen’s Advisory and Oversight Committee (SAP)
BodyId: 252

**Comment by hancush** [comment]
Got it, thank you!

**Comment by hancush** [comment]
Updated the scraper to import the new oversight committees in https://github.com/opencivicdata/scrapers-us-municipal/pull/301. They should come in, in this evening's full scrape. Will check on this in the morning!

**Comment by hancush** [comment]
New committees are in! Next week's meeting of the Measure M Oversight Committee is displaying as expected in the upcoming meetings section on the homepage and on the events page.

<img width="904" alt="Screen Shot 2019-11-27 at 8 54 43 AM" src="https://user-images.githubusercontent.com/12176173/69733837-9d471480-10f3-11ea-8237-a3f62212e457.png">
<img width="1051" alt="Screen Shot 2019-11-27 at 8 54 54 AM" src="https://user-images.githubusercontent.com/12176173/69733838-9d471480-10f3-11ea-8a99-ef1598db4e29.png">

None of the oversight committees have memberships in Legistar, so they aren't displayed on the committees page. Two questions, @shrayshray:

- Do you expect the oversight committees to show up on the committees page?
- Should/will there be memberships on the oversight committees?

**Comment by shrayshray** [comment]
My inclination is to not show them on the committees page as they are not Board of Directors committees, @camachoo can you confirm?
For the same reason, I don’t believe we will be entering members for them in legistar.

**Comment by hancush** [comment]
Safe to close this, @shrayshray?

**Comment by shrayshray** [comment]
Yes.
