### ISSUE TITLE
Restore filtering of test events in 2.5 upgrade

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#508]
Need to restore the filtering of test events in the 2.5 upgrade.

**Comment by hancush** [comment]
It seems like this was already done in https://github.com/datamade/la-metro-councilmatic/commit/45256e00c0905899adfd54230bf5bc88c44eda58#diff-154e85485bdcc3826d208aa9dbc8d8e3R252, but we do need to restore bill filtering still!
