### ISSUE TITLE
Home page: Change logic for Upcoming Meetings list and include Regular Board

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#511]
Update the logic for showing Upcoming Committee Meetings on Home Page:
1. Do not exclude Regular Board Meetings
    a. Change header to "Upcoming Meetings"
2. Show all meetings up to and including the next Regular Board Meeting, and
3. Show a minimum of 5 meetings.

Examples.
On 11/19, we'd see:
11/20 - Planning and Programming
11/20 - Finance, Budget and Audit
11/21 - Operations, Safety and Customer Experience
11/21 - Construction
11/21 - Executive Management
12/4 - Measure M
12/5 - Crenshaw Project
12/5 - Regular Board Meeting
(all meetings up to and including the next Regular Board Meeting)

on 11/22, we'd see:
12/4 - Measure M
12/5 - Crenshaw Project
12/5 - Regular Board Meeting
1/15 - Planning and Programming
1/15 - Finance, Budget and Audit
(minimum of 5 meetings)

on 12/6, we'd see:
1/15 - Planning and Programming
1/15 - Finance, Budget and Audit
1/16 - Operations, Safety and Customer Experience
1/16 - Construction
1/16 - Executive Management
1/23 - Regular Board Meeting
(all meetings up to and including the next Regular Board Meeting)

**Comment by hancush** [comment]
@shrayshray This is live on the staging site: https://lametro-upgrade.datamade.us/. Look ok?

**Comment by shrayshray** [comment]
@hancush yes, looks great! The locations are showing up differently for the Crenshaw project and Regular board on the test and live sites, though. The live site is correct, so is there just a difference in scraping schedules? Although, it doesn't look like any edits were made to the Crenshaw meeting with 15 minutes of it being created on 5/6/2020.
Test:
![image](https://user-images.githubusercontent.com/28063988/81459005-708f3280-9152-11ea-8fac-100bc3d86061.png)

Live site (correct):
![image](https://user-images.githubusercontent.com/28063988/81459020-869cf300-9152-11ea-90ce-f9e70b0e21ff.png)
![image](https://user-images.githubusercontent.com/28063988/81459078-ded3f500-9152-11ea-8a57-168be8fcf848.png)

**Comment by hancush** [comment]
Yes, I'd chalk that up to the difference in scraping schedule, as the test site is now correct: https://lametro-upgrade.datamade.us/.

**Comment by hancush** [comment]
Deployed to the live site!
