### ISSUE TITLE
Models and Views

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#521]
This an epic for tracking the remaining work for updating models and views.

**Comment by hancush** [comment]
We're a bit over time here. Land the necessities; we can likely swing back around for improvements later.

- [ ] #509
- [ ] #520
- [ ] #519
- [ ] #300

**Comment by hancush** [comment]
I'm going create a branch for the staging deployment off `2.5`, and develop in feature branches off that branch. FG will review those merged PRs when he returns.
