### ISSUE TITLE
Final deployment

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#523]
Once we are ready for deployment to production we will need to adjust the deployment scripts to enact that.

Once issue that we will need to think about is that if we put the scrapers and la-metro-councilmatic on separate servers (as we should), then we will need to set up the database so that more than one server can connect with it.

RDS may be a good solution for this, we could also have the db be on one server and expose a port to the other server.

**Comment by hancush** [comment]
I have configured the database server on the new Metro server to allow inbound connections from the OCD server. 

Remaining tasks:

- [ ] Update the scraping scripts to populate the OCD API, as well as the Metro database
- [ ] Update the Metro ETL scripts to run on staging once a day and production every 15 minutes
- [ ] Before final cut over, migrate identifiers one final time
- [ ] Update staging and production domains https://github.com/datamade/la-metro-councilmatic/issues/520#issuecomment-580892852

More to come, surely.

**Comment by hancush** [comment]
A new instance has been set up at https://lametro-upgrade-prod.datamade.us. We'll need to do the remaining items in https://github.com/datamade/la-metro-councilmatic/issues/523#issuecomment-598405869 prior to launch, but they shouldn't take too long. I expect to see full data in the new instance later this evening, once the full scrape runs.
