### ISSUE TITLE
Home and Events pages: Feb 2020 Meetings listed 2x

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#536]
On the home page and [events page](https://boardagendas.metro.net/events/), the February 2020 committee meetings are listed twice (except Finance committee):
![image](https://user-images.githubusercontent.com/28063988/72561203-8bfdc700-385d-11ea-9e0d-d1a7e2486ba9.png)

**Comment by hancush** [comment]
Hi, @shrayshray. It looks like all four pairs of duplicate events reference meetings that were deleted and recreated in Legistar (i.e., for each pair of duplicates, one references a live event in the Legistar API, and the other references an event that 404s).

councilmatic url | ocd api | legistar api | deleted
-- | -- | -- | --
https://boardagendas.metro.net/event/planning-and-programming-committee-379ff97884c9/ | https://ocd.datamade.us/ocd-event/d5ca5228-adad-49a7-853f-379ff97884c9/ | http://webapi.legistar.com/v1/metro/events/1650 |  
https://boardagendas.metro.net/event/planning-and-programming-committee-fbe977f51a0a/ | https://ocd.datamade.us/ocd-event/8b9e5a3b-8735-4918-bd94-fbe977f51a0a/ | http://webapi.legistar.com/v1/metro/events/1633 | T
https://boardagendas.metro.net/event/operations-safety-and-customer-experience-97c8fe6b4256/ | https://ocd.datamade.us/ocd-event/0730a616-55eb-4c08-ae33-97c8fe6b4256/ | http://webapi.legistar.com/v1/metro/events/1635 | T
https://boardagendas.metro.net/event/operations-safety-and-customer-experience-571116c9124b/ | https://ocd.datamade.us/ocd-event/7f9a1737-8592-48ae-90ed-571116c9124b/ | http://webapi.legistar.com/v1/metro/events/1652 |  
https://boardagendas.metro.net/event/construction-committee-92e64784be2d/ | https://ocd.datamade.us/ocd-event/489439f4-2ed7-411e-ab24-92e64784be2d/ | http://webapi.legistar.com/v1/metro/events/1653 |  
https://boardagendas.metro.net/event/construction-committee-cc6688ed6f70/ | https://ocd.datamade.us/ocd-event/3fa7d47c-ce6a-46ec-8ded-cc6688ed6f70/ | http://webapi.legistar.com/v1/metro/events/1636 | T
https://boardagendas.metro.net/event/executive-management-committee-e1d68ab55edd/ | https://ocd.datamade.us/ocd-event/040435e1-bf6a-471b-a50b-e1d68ab55edd/ | http://webapi.legistar.com/v1/metro/events/1654 |  
https://boardagendas.metro.net/event/executive-management-committee-b644249be2e5/ | https://ocd.datamade.us/ocd-event/c7281e2b-ba0d-45d2-8b20-b644249be2e5/ | http://webapi.legistar.com/v1/metro/events/1637 | T

Can you confirm this happened on your end?

If so, handling deletes is a longstanding challenge with our data framework (https://github.com/opencivicdata/pupa/issues/295). I can go in and remove the duplicates that reference dead links!

**Comment by hancush** [comment]
@shrayshray Went ahead and removed the duplicates from our system! If everything looks good to you, I'll go ahead and close this.
