### ISSUE TITLE
Board Reports: Operations, Safety, and Customer Experience Committee missing from sidebar filter

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#537]
On the Board Reports search page, under "Filter by Meeting" in the left sidebar, Operations, Safety, and Customer Experience Committee is not listed:
![image](https://user-images.githubusercontent.com/28063988/72562475-61613d80-3860-11ea-93f0-db902349ba40.png)

**Comment by shrayshray** [comment]
I also noticed the other meeting filters are not picking up reports for recent meetings. With nothing in the search bar and no previous query or filter applied, clicking any of the meeting names filters reports from that meeting body, 1/25/2018 and prior. 
Operations, Safety, and Customer Experience Committee has only been meeting since 7/19/2018.

**Comment by hancush** [comment]
Hello again! 🙃 We populate the meetings facet by looking at matter histories, so if there are no histories associated with a board report, then it won't come back when you filter by meeting. I queried the database: It doesn't look like we have any histories associated with the Operations, Safety, and Customer Experience Committee, which would explain why it's not an available filter.

I'm seeing more recent reports [when I filter by Board of Directors](https://boardagendas.metro.net/search/?selected_facets=sponsorships_exact%3ABoard+of+Directors&sort_by=date&order_by=desc), so I'm not convinced there's a temporal element at play.

Does this explanation track with your expertise on the data?

Thinking more about this, since we know not every report has a history (#340), it doesn't seem appropriate to populate this facet using histories. Instead, I'd think something like sponsorships or committees associated with agendas that the report appears on would be more accurate. Thoughts?

**Comment by shrayshray** [comment]
Yes, thank you! This all make sense, thanks for putting the pieces together. And yes, we should definitely be doing this based on the name of the committee the report is associated with at agenda posting time, rather than the matter history entry. 
Sponsors is not a required field and not always entered, but "In Control"/Controlling Body is - Would that work?

**Comment by hancush** [comment]
Possibly! Is that the information in the `MatterBodyName` in the API?

**Comment by shrayshray** [comment]
Yes, it is in MatterBodyName in the API.

**Comment by hancush** [comment]
Update: Looks like this filter isn't appearing at all! I can look into this.

**Comment by hancush** [comment]
@shrayshray What is the desired behavior of this filter? One thought I had is that we could populate it using the same logic we used to add appearing on an agenda to board report history in #348. This would associate the board report with any meeting body for which it appears on an agenda, as well as with those that act on it (i.e., appear in the matter history). What do you think?

**Comment by hancush** [comment]
Looks like I removed the sponsorships facet from the search view by mistake: https://github.com/datamade/la-metro-councilmatic/pull/628/files#diff-c166f53b78217ee6895496fa71c80a567b4922203a857b0c39c51218f3d359cbL70

We should add that back!

**Comment by camachoo** [comment]
@hancush I am not sure we want to do that.  I think we had a discussion about the consistency of use of this field @ metro....  I think that the logic used for appearing on an agenda sounds like a better idea.  What are the considerations to this option? The filters only show if they have a file history, when they are on the agenda, or both?

**Comment by hancush** [comment]
Hi, @camachoo. It the original implementation, the Meetings facet used matter history to determine which meeting bodies a board report is associated with. 

Are you saying you'd prefer to eschew matter history altogether and just use agendas? In that case, should a board report be associated with all meeting bodies for which it appears on an agenda, or just the most recent one? For example, [2020-0671 appears on two agendas](https://boardagendas.metro.net/board-report/2020-0671/). Should it appear in search results filtered for both the Planning and Programming Committee and the Board, or just the Board (most recent agenda)?

**Comment by hancush** [comment]
Board reports are sometimes acted upon without appearing on an agenda, so we will use `actions_and_agendas` to populate the meeting facet (as well as adding it back!)

**Comment by hancush** [comment]
@fatima3558 Can you take this on? The tasks here are to:

- Add the meeting facet back to the search template. N.b., the facet _label_ is Meetings, but it's called `sponsorships` under the hood. I'm pretty sure that all the other infrastructure is still in place, but it wouldn't hurt to double check that it's still in the following files:
    - Haystack index
    - Solr index
    - Search view
- Update [the `prepare_sponsorships` method](https://github.com/datamade/la-metro-councilmatic/blob/d63d978b63478eba69f46b62d289438307bf1b2a/lametro/search_indexes.py#L31) on the Haystack index model to return a de-duplicated list of organizations from the `actions_and_agendas` property.

**Comment by hancush** [comment]
@shrayshray This is live on staging: https://lametro-upgrade.datamade.us/search/

What do you think?

**Comment by hancush** [comment]
(Most excitingly: https://lametro-upgrade.datamade.us/search/?selected_facets=sponsorships_exact%3AOperations%2C%20Safety%2C%20and%20Customer%20Experience%20Committee)

**Comment by shrayshray** [comment]
@fatima3558 @hancush looks great!! I'm so happy to see this - thank you!

**Comment by hancush** [comment]
Yay! Deployed to the live site, @shrayshray.
