### ISSUE TITLE
Document admin interface for uploading headshots

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#552]

**Comment by hancush** [comment]
The workflow for this is non-optimal: It requires adding headshots by URL to each person in the database, then running the management command to download those headshots to our server, i.e., it still requires DataMade intervention. It would be awesome to refine this in the future (including #549), but since it's new functionality, it should be done outside of the upgrade. Moving this into the icebox for now.

**Comment by hancush** [comment]
Meanwhile, we're rendering the headshots provided by Metro, as we were before, on the upgrade site: https://lametro-upgrade.datamade.us/board-members

**Comment by shrayshray** [comment]
Looks great, @hancush !
