### ISSUE TITLE
Last action date is not displaying as expected in feeds on the person detail page

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#553]
<img width="1440" alt="Screen Shot 2020-02-25 at 1 16 53 PM" src="https://user-images.githubusercontent.com/12176173/75279393-26441980-57d1-11ea-9448-34ff9a0ef495.png">

**Comment by hancush** [comment]
This was resolved via https://github.com/opencivicdata/pupa/pull/329 and https://github.com/datamade/django-councilmatic/pull/265.

<img width="1412" alt="Screen Shot 2020-03-11 at 2 08 06 PM" src="https://user-images.githubusercontent.com/12176173/76454057-f0db2680-63a1-11ea-8ec0-d1266e7e8b4d.png">

**Comment by shrayshray** [comment]
@hancush yes, looks good!
