### ISSUE TITLE
Board Report: Reports missing packets on upgrade test site

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#556]
On report pages, the option to "Download Board Report and Attachments" is missing. [Example](https://lametro-upgrade.datamade.us/board-report/2018-0339/):
![image](https://user-images.githubusercontent.com/28063988/75393596-47753a80-58a3-11ea-9205-bc319288c89a.png)

**Comment by hancush** [comment]
Ditto https://github.com/datamade/la-metro-councilmatic/issues/558#issuecomment-598339293. Looks like our merging process is still chugging through board report documents. Let's check on this tomorrow.

**Comment by hancush** [comment]
Update: The merge has completed! @shrayshray, board reports should now display packets as expected. Look ok?
