### ISSUE TITLE
Meeting: Option to download Agenda packet is missing on upgrade test site

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#558]
Meetings are missing the link to "Download Agenda Packet". [Example](https://lametro-upgrade.datamade.us/event/finance-budget-and-audit-committee-45e2ae77fc28/):
![image](https://user-images.githubusercontent.com/28063988/75394449-ff571780-58a4-11ea-84c2-f0687c6a36e1.png)

**Comment by hancush** [comment]
Needed to turn on the step in our new pipeline to build packets. Look ok now, @shrayshray?

**Comment by shrayshray** [comment]
@hancush yes, looks good!
