### ISSUE TITLE
Meetings: Upcoming meetings showing as updated on upgrade test site

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#566]
On the [upgrade test site](https://lametro-upgrade.datamade.us/events/), upcoming meetings are showing as "updated", but the agendas haven't been posted yet: 
![image](https://user-images.githubusercontent.com/28063988/76449945-35f35e80-638a-11ea-9d7c-61198ec6cf19.png)

**Comment by hancush** [comment]
This should be addressed by the fix in place for #509.
