### ISSUE TITLE
Board Member: Remove Sponsored Board Actions temporarily

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#567]
As addressed in #342, Minutes Histories are not being entered for Committee meetings. As such, the "Sponsored Board Actions" section on Board Member pages is showing the most recent actions as 2017. Similar to #483, please disable/hide the "Sponsored Board Actions" section for now. Omar and I will work with the Board Secretary's Office to get Minutes Histories entered and request to have it re-enabled once histories start being entered consistently.

**Comment by hancush** [comment]
@shrayshray This is deployed to the staging site, https://lametro.datamade.us! Want to take a look at the board member pages? If it looks ok to you, I can deploy this along with multiple meeting display (#577) to the live site.

**Comment by shrayshray** [comment]
@hancush yes, looks good to me!

**Comment by hancush** [comment]
Deployed!
