### ISSUE TITLE
Board Member: Board actions/reports listed differently than on Reports page

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#568]
Not urgent, as #567 will hide this section temporarily.
On Board Member/Person detail pages, on the Board Actions tab, Board Reports are listed as [Report Type] [File ID]. 
![image](https://user-images.githubusercontent.com/28063988/76463624-ebc9a780-63a0-11ea-98da-3a1b8fde0312.png)

On the Board Reports page, reports are listed as [File ID] [Subject]. For consistency, please list reports in both places as [File ID] [Subject].
![image](https://user-images.githubusercontent.com/28063988/76463695-1451a180-63a1-11ea-98bf-ac5fbc5a5836.png)

**Comment by hancush** [comment]
Rolled this change in with #567, since both involve re-enabling the board report listing. It's deployed to staging right now!
