### ISSUE TITLE
Home: Show the next board meeting, even if it was cancelled

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#573]
On 3/17, the 3/26 Regular Board Meeting was cancelled. After it was cancelled, the home page showed the nest Regular Board Meeting as 4/23. While 4/23 is technically the next time a Regular Board Meeting will take place, for a number of reasons, we still want to show the next meeting as 3/26, with the notation it is cancelled, until the date/time of the  meeting passes.

**Comment by shrayshray** [comment]
Additional logic: the ability to show more than one upcoming meeting. Example: Regular Board meeting and Special Board Meeting are scheduled one day apart.  They both have the same members, which is the full board, but one is required for very special circumstances.  Or one is cancelled, and the special Board meeting is the same or next day.

It seems like a very remote possibility, but it might actually happen in the next few months.

**Comment by hancush** [comment]
hi, @shrayshray! is this something you'd like us to implement right away?

**Comment by shrayshray** [comment]
@hancush yes, please!

**Comment by hancush** [comment]
@shrayshray Working on showing cancelled meeting now. What are your thoughts on logic to display multiple upcoming meetings? 

The board generally meets once a month, right? What about something like:

- Check for meetings of the board for the current month.
    - If there are meetings, display them all. (Generally there will only be one, except in the special instance you described.)
    - If there are no meetings (the current month's meeting has already happened, or there's not a meeting, e.g., in August), check for and display all board meetings for the following month.

Let me know!

**Comment by hancush** [comment]
@shrayshray Hello, again! The cancelled meeting logic is live on the staging site: https://lametro.datamade.us/. If this looks good to you, I can get it live this afternoon, then tackle the multi-meeting display separately.

**Comment by shrayshray** [comment]
This looks great!

**Comment by hancush** [comment]
Thanks, @shrayshray! This has been deployed to the live site, albeit a little belatedly. 😓
