### ISSUE TITLE
Home: Add ability to show more than one upcoming board meeting

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#577]
From @shrayshray in https://github.com/datamade/la-metro-councilmatic/issues/573#issuecomment-600865099: 

<blockquote>
<p>Additional logic: the ability to show more than one upcoming meeting. Example: Regular Board meeting and Special Board Meeting are scheduled one day apart. They both have the same members, which is the full board, but one is required for very special circumstances. Or one is cancelled, and the special Board meeting is the same or next day.</p>

<p>It seems like a very remote possibility, but it might actually happen in the next few months.</p>
</blockquote>

**Comment by hancush** [comment]
Proposed logic, migrated from https://github.com/datamade/la-metro-councilmatic/issues/573#issuecomment-602834400: 

<blockquote>
<p>What are your thoughts on logic to display multiple upcoming meetings?</p>

<p>The board generally meets once a month, right? What about something like:</p>

<ul>
<li>Check for meetings of the board for the current month.</li>
<ul>
<li>If there are meetings, display them all. (Generally there will only be one, except in the special instance you described.)</li>
<li>If there are no meetings (the current month's meeting has already happened, or there's not a meeting, e.g., in August), check for and display all board meetings for the following month.</li>
</ul>
</ul>

<p>Let me know!</p>
</blockquote>

Cc: @shrayshray. Let's continue this thread here in this issue!

**Comment by hancush** [comment]
Experimenting with layout options when there is more than one meeting. Simply showing two meetings doesn't look too bad. What do you think, @shrayshray?

<img width="1440" alt="Screen Shot 2020-03-23 at 4 44 56 PM" src="https://user-images.githubusercontent.com/12176173/77366379-e0259b80-6d25-11ea-8a9c-167565f360e2.png">

<img width="496" alt="Screen Shot 2020-03-23 at 4 45 09 PM" src="https://user-images.githubusercontent.com/12176173/77366395-eb78c700-6d25-11ea-80b2-d214c3bbaa03.png">

**Comment by shrayshray** [comment]
@hancush having the image one their twice kind of throws me off, is it possible to only show the image in the first instance? If not, I think we should just stick with one listing.

**Comment by hancush** [comment]
@shrayshray How about something like this?

<img width="746" alt="Screen Shot 2020-03-26 at 2 11 51 PM" src="https://user-images.githubusercontent.com/12176173/77687037-db522900-6f6b-11ea-88b0-bb888d0cbe04.png">
<img width="471" alt="Screen Shot 2020-03-26 at 2 12 27 PM" src="https://user-images.githubusercontent.com/12176173/77687043-de4d1980-6f6b-11ea-84ed-4245cc10f64e.png">

**Comment by shrayshray** [comment]
@hancush looks great! But just want to clarify - We would continue to highlight only full board meetings, Regular Board and Special Board, right? I wasn't sure whether Finance committee was showing just as an example or not.

**Comment by hancush** [comment]
That's correct, @shrayshray! The meetings in the screenshot are only for testing purposes.

**Comment by shrayshray** [comment]
@hancush awesome, then this looks good to go!

**Comment by hancush** [comment]
Nice. Deployed to staging, https://lametro.datamade.us, though you won't see any change until there are two board meetings scheduled in a given month!

**Comment by hancush** [comment]
Also deployed!

**Comment by shrayshray** [comment]
@hancush can you confirm both meetings are also displayed when meetings are concurrent? Related to #162 
On 5/28, There is a Crenshaw Project and Regular Board Meeting which both begin at 10am. Per other concurrent meetings, one meeting begins when the other ends without systematically starting and ending the meeting broadcast, so we display both as live from their start time. Can we expect the appropriate links to public comment will display at the same time, too?
