### ISSUE TITLE
Meeting pages: Change text for when public comment is not enabled

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#582]
On the page for each meeting, replace "Online public comment is not available for this meeting" with "Online public comment will be available after the Agenda is posted, and remain open through the duration of the meeting.  If you are unable to access online public comment during the expected Agenda time frames, please visit: https://metro.granicusideas.com/meetings."

![image](https://user-images.githubusercontent.com/28063988/78063771-92241f80-7345-11ea-93f3-cb363397d54d.png)

**Comment by hancush** [comment]
Hi, @shrayshray. Is online public comment available anywhere after a meeting, or only leading up to the meeting? The provided text is very useful to display for upcoming events, but it might be confusing after an event has passed if users won't be able to access online public comment again. If that's the case, we can show nothing, or some alternative text like "Online public comment has closed." Let me know what you think.

**Comment by shrayshray** [comment]
@hancush agreed, thanks for flagging this. 
If the Agenda has not yet posted, display: "Online public comment will be available after the Agenda is posted, remain open until the meeting concludes. If you are unable to access online public comment during the expected Agenda time frames, please visit: https://metro.granicusideas.com/meetings."

After the meeting has ended or another meeting has started, display: "Online public comment for this meeting has closed."

**Comment by shrayshray** [comment]
Online public comment will now only be available during the meeting, so let's change the text here to: "Online public comment will be available once the meeting begins."

**Comment by hancush** [comment]
Done in #595.
