### ISSUE TITLE
Home: Show eComment button for Next Board Meeting

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#583]
In the "Next Board Meeting" section on the Home page, add a button for eComment which goes directly to comment on the meeting (as it does on the button/link on the meeting page).
If eComment is not yet available, display "Online public comment will be available after the Agenda is posted, and remain open through the duration of the meeting. If you are unable to access online public comment during the expected Agenda time frames, please visit: https://metro.granicusideas.com/meetings."
![image](https://user-images.githubusercontent.com/28063988/78065196-c4368100-7347-11ea-93e4-47d6ffd46009.png)

**Comment by camachoo** [comment]
I feel like this needs to be a button for attention.  However, I am open for discussion.  Shelly and I will discuss with the group.

**Comment by hancush** [comment]
@camachoo If there's a link, it will be displayed as a button. See the screenshots [here](https://github.com/datamade/la-metro-councilmatic/pull/589#issue-399902043).

**Comment by hancush** [comment]
Done in #595.
