### ISSUE TITLE
Load test the site ahead of April board meeting

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#585]
Metro anticipates an unusual increase in traffic to the site for next month's board meeting. Let's load test the site to ensure it can meet demands.

First things first, @shrayshray, could you grant me access to your Google Analytics? This will inform the size of the load we throw at the site.

**Comment by shrayshray** [comment]
@hancush you now have access to Google Analytics for the site.

**Comment by hancush** [comment]
Thank you!

**Comment by hancush** [comment]
In a normal world, about 200 comments is normal, and about 400 is high. Since we're in an abnormal world, there may be more interest/activity than usual. 

I'll take a look at the analytics to see what's normal during meetings, and I'll throw traffic at the site and see where performance degrades and requests start timing out. We can use those numbers to decide whether any action is needed ahead of this month's board meeting.

**Comment by hancush** [comment]
Here's site traffic for board meetings in the last year:

date | total users | peak simultaneous users
--: | --: | --:
2/27/2020 | 406 | 118
1/23/2020 | 556 | 130
12/5/2019 | 395 | 121
10/24/2019 | 404 | 162
9/26/2019 | 395 | 118
7/25/2019 | 411 | 117
6/27/2019 | 321 | 83
5/23/2019 | 367 | 92
4/25/2019 | 345 | 99
3/28/2019 | 289 | 73
2/28/2019 | 412 | 114
1/24/2019 | 478 | 115

Based on these numbers, I'll throw an increasing amount of traffic up to double the max simultaneous users (324) and see how the site fares.

**Comment by hancush** [comment]
I used the staging site to run several rounds of testing simulating 325 users navigating to the homepage, event listing, and board meeting detail page at random intervals between 60 and 90 seconds, for a 10-minute period. This works out to about 5 requests per second across the user pool, a heavier load than even peak use during board meetings in the last year.

Based on the earlier rounds of testing, I increased the number of workers responding to requests and configured them to restart at staggered intervals, so there is always at least one live worker.

During the last test, aggregate median response time was less than one second, and aggregate response time at the 90th percentile was less than three seconds. I also cruised the site while the test was ongoing and didn't experience any noticeable lag.

I expect to see the same if not better performance on production, because there is one more worker than on staging listening for requests. I'll keep this open through this week's board meeting – if things go well, I think it's safe to close this!

**Comment by hancush** [comment]
@shrayshray How did the site perform yesterday? Any reports of sluggishness or timeouts?

**Comment by shrayshray** [comment]
@hancush everything looked great to me! And no reports of timeouts from other users either. Thanks for following up to check.

**Comment by hancush** [comment]
That's awesome, @shrayshray. Looks like you were right to predict an uptick in traffic: Yesterday, we had 1,236 users, with a one-hour peak of 541 users.
