### ISSUE TITLE
Meeting detail: Show remote public comment options

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#593]
On each meeting detail page, show the following text above the list of Board Reports (see screenshot below)

_Submit Public Comment remotely_
**On the web**: http://boardagendas.metro.net **or** https://metro.granicusideas.com/meetings
**Via email:** jacksonm@metro.net 
**By postal mail:** Board Secretary's Office, One Gateway Plaza, MS: 99-3-1, Los Angeles, CA 90012 

![image](https://user-images.githubusercontent.com/28063988/78841079-50345280-79b1-11ea-998a-21bb085d996b.png)

**Comment by hancush** [comment]
@shrayshray Questions:

1. Should this _replace_ the existing eComment link on meeting detail pages?
2. Should this be visible on past meeting pages? Put another way, are you accepting public comment after a meeting has concluded? 
3. Should "On the web" always show the generic link, or should we show the event-specific eComment link if it's available?

**Comment by shrayshray** [comment]
> 1. Should this replace the existing eComment link on meeting detail pages?

No. The original button/link should remain, and this additional info should be added.

> 2. Should this be visible on past meeting pages? Put another way, are you accepting public comment after a meeting has concluded?

Personally, I think it should go away after the meeting to minimize confusion. Comments can still be sent, but they obviously won't be considered before voting if the meeting has already concluded. It'd be better to not have it appear they will be. @camachoo did you intend to have this info be static, or should it behave like the link/button on the page and not show after the meeting ends?

> 3. Should "On the web" always show the generic link, or should we show the event-specific eComment link if it's available?

If we can show the event-specific link, that would be ideal!

One more thing - before the line "Via email", please add the text, "Please make sure to note the agenda number and item along with comments submitted by mail."

**Comment by camachoo** [comment]
In stead of

"Please make sure to note the agenda number and item along with comments submitted by mail."

We should use

"Please make sure to note the meeting name, meeting date, and agenda number \ item along with comments submitted by mail."

-Omar
________________________________

**Comment by shrayshray** [comment]
Re: item 2. above:
> Should this be visible on past meeting pages? Put another way, are you accepting public comment after a meeting has concluded?

Per Omar, the remote public comment options should behave like the link/button to ecomment and not show for past meetings or after the meeting concludes.

**Comment by camachoo** [comment]
Test meeting run complete.  Here are the results:  Shelly, please feel free to "comment" here.   HA HA!

  1.
Front page scheduled meeting with agenda and eComments:
[cid:e61c349f-6a54-423d-8c04-822f235c5ac9]
Looks perfect.  Shelly thoughts?

  2.
Front page upcoming meetings area:
[cid:8911cf3d-97bc-4e10-9704-31afd8be09ed]
Still not sure if I like the button on the right but am not opposed to it.

  3.
Meetings details page scheduled meeting with agenda and eComments:
[cid:76e2aca2-43ad-436c-b1d3-ab5c2742c884]
Again looks good to me.

  4.
Front page current \ live meeting:
[cid:d56d067d-d1b1-4948-b46f-a3da5732c305]
I am a bit uncomfortable about the layout here.  Might be because of the missing location lines and the missing Spanish button.  How to we make this look better if this does happen?  It will happen at the next meeting.  The location is set to be "Virtual Online Meeting".  One line.

  5.
Meeting details page current \ live & post meeting:
[cid:80d58bad-85c0-4650-9ee7-c5cbb91b76c9]

We need to fix this, at least for the current \ live meetings.  Hannah, do we have the capability to replicate the front page current meeting logic to a certain degree on the meeting details pages?

Omar
________________________________

**Comment by shrayshray** [comment]
> 1. Front page scheduled meeting with agenda and eComments:
[cid:e61c349f-6a54-423d-8c04-822f235c5ac9]
Looks perfect.  Shelly thoughts?

Perfect. *chef's kiss*

>   2. Front page upcoming meetings area:
[cid:8911cf3d-97bc-4e10-9704-31afd8be09ed]
Still not sure if I like the button on the right but am not opposed to it.

I think it will look better when the all the committees have the button, instead of just a couple. It's hidden on mobile so no issue there.

> 3. Meetings details page scheduled meeting with agenda and eComments:
[cid:76e2aca2-43ad-436c-b1d3-ab5c2742c884]
Again looks good to me.

Yep, exactly as expected.

>  4. Front page current \ live meeting:
[cid:d56d067d-d1b1-4948-b46f-a3da5732c305]
I am a bit uncomfortable about the layout here.  Might be because of the missing location lines and the missing Spanish button.  How to we make this look better if this does happen?  It will happen at the next meeting.  The location is set to be "Virtual Online Meeting".  One line.

[#589](https://github.com/datamade/la-metro-councilmatic/pull/589#issuecomment-611584220) has screenshots of how it looks with a typical meeting and all buttons - does it look okay to you there?

**Comment by shrayshray** [comment]
As explained via email, Metro will now be accepting public eComment only during the meeting. This means we need to change the copy about remote public comment options. 

Text should now read:

"**EComment will be available on this page once the meeting begins.**
 
**Via email:** jacksonm@metro.net
**By postal mail:** Board Secretary's Office, One Gateway Plaza, MS: 99-3-1, Los Angeles, CA 90012

_Please make sure to note the meeting name, meeting date, and agenda number or item along with comments submitted by email or postal mail. **Comments via mail must be received by 5pm on the day prior to the meeting.**_ "

This info should display once the Agenda is available, and hide once the meeting ends. If possible, the text "EComment will be available on this page once the meeting begins" should be replaced with the link to the event-specific comment page once it's available (even though it will also be on the button).

**Comment by hancush** [comment]
Done in #595.
