### ISSUE TITLE
Meeting detail: Show Watch Live buttons

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#597]
While a current meeting is live, the "Watch in English" and "Watch in Espanol" buttons show on the homepage and link to the live meeting broadcast.
Show these same buttons on the meeting detail page during the live meeting.

**Comment by hancush** [comment]
@shrayshray Is this high priority, or can it go in the ice box? TY!

**Comment by shrayshray** [comment]
Can it go in the backlog before #477?

**Comment by hancush** [comment]
Done!

**Comment by hancush** [comment]
Hi, @shrayshray, I just deployed this to the staging site. Would you all like to run a test live event this week to confirm it works as expected?

**Comment by hancush** [comment]
This is deployed as well. Let's keep an eye on it during next week's meetings. If it behaves as expected, we can close this issue.
