### ISSUE TITLE
Meetings: Event shows with future date but in Past meetings

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#598]
A test meeting scheduled for 4/9/2020 at 5:00pm was created for the System Safety, Security and Operations Committee. On 4/10/2020 at 1pm, the meeting was listed in the Past meetings section of the [Meetings page](https://lametro-upgrade.datamade.us/events/), under the header of meetings for 4/10/2020.
![image](https://user-images.githubusercontent.com/28063988/79021820-6832e000-7b31-11ea-9c87-24b4124c8b9a.png)

Had the date of the meeting been changed from 4/9 to 4/10 at 5pm, it still should not have been in Past meetings at 1pm on 4/10.

But the date nor time had been changed on the meeting, and [the meeting detail page](https://lametro-upgrade.datamade.us/event/system-safety-security-and-operations-57fac4320003/) still showed the correct meeting date and time.
![image](https://user-images.githubusercontent.com/28063988/79022033-eabb9f80-7b31-11ea-85ca-93ebf95c22ed.png)

**Comment by shrayshray** [comment]
Similar to System Safety, Security, and Operations in the case above, the Construction Committee test meeting which was scheduled for 4/10/2020 is showing under 4/11/2020:
![image](https://user-images.githubusercontent.com/28063988/79152913-de2d8600-7d81-11ea-950e-b1ba5bf0ec0a.png)

**Comment by hancush** [comment]
Just deployed a fix for this to staging: https://lametro-upgrade.datamade.us/events/. If this looks good, I'll make it live.
