### ISSUE TITLE
Create an endpoint that returns the comment link for the current meeting

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#599]
This endpoint should live at `boardagendas.metro.net/public-comment`. It should return the comment link for the current meeting. If there is no current meeting, or if there is no live meeting and more one meeting scheduled to start in the last 20 minutes or the next five minutes, it will return the generic eComment link.

**Comment by camachoo** [comment]
I'm getting a page not found from that URL.

[cid:5a9adee9-bb42-483f-bd18-0f18e6829787]
________________________________

**Comment by hancush** [comment]
This is deployed to staging! https://lametro-upgrade.datamade.us/public-comment should redirect to the generic public comment link. When a meeting is live, it will redirect to the public comment link for the live meeting.
