### ISSUE TITLE
Add a map?

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#6]
Should we include a map for displaying LA Metro board members?

**Comment by hancush** [comment]
I vote against a map for the full list of board members (too many layers of jurisdictions), but we should find out if they're meant to represent the constituencies relevant to whatever office qualifies them to be on the board, and if that's the case, perhaps we ought to put maps on their individual pages?

**Comment by reginafcompton** [comment]
This is happening.....
