### ISSUE TITLE
Not all bills have a bill type.

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#60]
Not all bills have a bill type, so this distorts the results for the faceted search filter. 

<img width="1246" alt="screen shot 2016-11-22 at 9 11 46 am" src="https://cloud.githubusercontent.com/assets/13078679/20528951/e1d7ea84-b093-11e6-9800-f8b8b6246f89.png">

**Comment by fgregg** [comment]
Can you give me an example of a bill without a bill type?

**Comment by reginafcompton** [comment]
False alarm! I was doing some work with the Haystack indices, and I might have temporarily messed up something. Short story: everything is there now.
