### ISSUE TITLE
Meetings: Exclude Service Council meetings

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#606]
Metro's Service Councils will be using the Metro Board Granicus iteration to host meetings in May. We'll need to exclude them from showing up on boardagendas.metro.net, by next week - Wednesday at the latest We'd need to exclude these meetings on Councilmatic before we add the meetings in Legistar next week.

The BodyTypeId is 70, as shown below.  

[
    {
        "BodyId": 256,
        "BodyGuid": "4D7B1130-DEDA-4B0D-9970-F99351773016",
        "BodyLastModifiedUtc": "2020-04-22T23:37:29.973",
        "BodyRowVersion": "AAAAAAEddx0=",
        "BodyName": "San Fernando Valley Service Council",
        "BodyTypeId": 70,
        "BodyTypeName": "Service Council",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 257,
        "BodyGuid": "64F0C0D0-C14D-49D8-9E2B-DCC9CCA60BE0",
        "BodyLastModifiedUtc": "2020-04-22T23:38:30.693",
        "BodyRowVersion": "AAAAAAEddy8=",
        "BodyName": "South Bay Service Council",
        "BodyTypeId": 70,
        "BodyTypeName": "Service Council",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 258,
        "BodyGuid": "9F2F2315-99FB-4E4E-9A9D-4A90191D4CF8",
        "BodyLastModifiedUtc": "2020-04-22T23:38:57.883",
        "BodyRowVersion": "AAAAAAEdd1M=",
        "BodyName": "San Gabriel Valley Service Council",
        "BodyTypeId": 70,
        "BodyTypeName": "Service Council",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 259,
        "BodyGuid": "70FE89EC-7783-4C05-8D26-1C7A41720205",
        "BodyLastModifiedUtc": "2020-04-22T23:39:24.29",
        "BodyRowVersion": "AAAAAAEdd1w=",
        "BodyName": "Westside/Central Service Council",
        "BodyTypeId": 70,
        "BodyTypeName": "Service Council",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 260,
        "BodyGuid": "B82A843F-8254-439D-B108-F7BC3531292F",
        "BodyLastModifiedUtc": "2020-04-22T23:39:59.18",
        "BodyRowVersion": "AAAAAAEdd0o=",
        "BodyName": "Gateway Cities Service Council",
        "BodyTypeId": 70,
        "BodyTypeName": "Service Council",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    }
]

**Comment by hancush** [comment]
We only scrape [committees and the taxpayer oversight committee](https://github.com/datamade/scrapers-us-municipal/blob/5bf0d2f26d5bf7a0c928c8723b628c4e725f4d5e/lametro/people.py#L112), so the ccouncil itself should not be scraped for display on the committees page. I'll look into whether we need to omit these explicitly from the event scrape.

**Comment by hancush** [comment]
@shrayshray We made a change to the scraper that should skip service council meetings. Let us know if one gets through, otherwise we can consider this done.

**Comment by hancush** [comment]
Looks like these were successfully omitted!

**Comment by shrayshray** [comment]
@hancush it looks like a Service Council Meeting got through - "Service Councils - Meet and Confer" (about 25 of them ... looks like user error). Is the scraper excluding based on "BodyName", or "BodyTypeName" / "BodyTypeID"?
"BodyTypeName "= "Service Council" or "BodyTypeID" = 70 would exclude all non-Public Hearing Service Council meetings, including including "Service Councils - Meet and Confer"

    {
        "BodyId": 274,
        "BodyGuid": "91EC6980-4B13-4C1C-AB5B-E9AF9EFD5567",
        "BodyLastModifiedUtc": "2020-07-15T20:12:05.34",
        "BodyRowVersion": "AAAAAAEm9YI=",
        "BodyName": "Service Councils - Meet and Confer",
        "BodyTypeId": 70,
        "BodyTypeName": "Service Council",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    }

**Comment by hancush** [comment]
@shrayshray We are using `EventBodyName` to exclude meetings, specifically we are omitting meetings where the `EventBodyName` ends with "Service Council" or "Service Council Public Hearing". These don't fit the pattern, so they got through. Would it be safe to omit all meetings where the `EventBodyName` contains "Service Council"?

**Comment by shrayshray** [comment]
I don't think we can 100% guarantee the name will always contain "Service Council". And while it's unlikely, we also can't guarantee a new Board Committee won't be given a name containing "Service Council". Since "BodyTypeName " or "BodyTypeID" are fields we do have control over, since they're created in Legistar, would it be possible to use one of them instead? 
Would it be possible to use "BodyTypeName " or "BodyTypeID" instead?
so, exclude
    "BodyTypeName "= "Service Council" and "BodyTypeName "= "Service Council Public Hearing"
or 
    "BodyTypeID" = 70 and "BodyTypeID" = 75

**Comment by camachoo** [comment]
ID would be the best...
________________________________

**Comment by hancush** [comment]
I agree that ID would be best. We use the events endpoint in the Legistar API to scrape meetings. Let me see if I can figure out a way to query it that allows us to exclude meetings of certain types of bodies. (@shrayshray, @camachoo – If either one of you has ideas on that, happy for your input. Will update this thread with what I find out.)

**Comment by hancush** [comment]
Update: This turned out to be a lot easier than I thought! Will publish the change today.

**Comment by hancush** [comment]
I deployed a change to the scraper to omit meetings of bodies of the "Service Council" (70) or "Service Council Public Hearing" (75) type. I also removed the meetings that got through yesterday from the live site. Look ok?

**Comment by shrayshray** [comment]
@hancush yes! You're the best, thank you!

**Comment by hancush** [comment]
Never a problem!
