### ISSUE TITLE
Committee pages: Flag cancelled meetings

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#613]
On Committee pages, display cancelled meetings consistent with how they're displayed on the home page, events listing page, and the meeting page - with the "cancelled" flag, and strike-through on the meeting name. 

![image](https://user-images.githubusercontent.com/28063988/81123003-f313ba00-8ee6-11ea-914c-42a55fe11f29.png)

**Comment by hancush** [comment]
@shrayshray This is live on staging, e.g., https://lametro-upgrade.datamade.us/committee/finance-budget-and-audit-committee-d2000bac9379/. What do you think?

**Comment by shrayshray** [comment]
@hancush Perfection!
