### ISSUE TITLE
Board members: Member list not showin

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#632]
Last week on our priorities call, I noticed the board members weren’t showing up on [this page,](https://boardagendas.metro.net/board-members/) because their terms have ended. I added their new terms on the Regular Board Meeting (Committee assignments haven’t been finalized yet) in Legistar right after our call, but they’re still not showing up on [the page](https://boardagendas.metro.net/board-members/). 
I thought the members showed based on their term being current - or am I mistaken and I should send you a list to add manually?

**Comment by hancush** [comment]
No, you're correct, @shrayshray, they should show up if they have a current membership. I'll look into this, this afternoon.

**Comment by hancush** [comment]
@shrayshray I'm not seeing any current members for the Board of Directors in Legistar: https://metro.legistar.com/DepartmentDetail.aspx?ID=28529&GUID=44319A1A-B2B7-48CC-B857-ADCE9064573B&R=f654923a-3000-40e2-9893-b9417ebcdb4c

Did the new memberships get published?

**Comment by shrayshray** [comment]
@hancush doh! This was totally my bad. I forgot to check the "Show on web" box on the new entries. It's checked now, so they should show up soon. Sorry about that!

**Comment by hancush** [comment]
If I had a nickel for every time I've made a similar mistake, we could both retire, @shrayshray! :-) The new terms should get picked up in the full scrape this evening – will check on this in the morning to confirm they're appearing as expected.

**Comment by hancush** [comment]
Behold, the Board is back: https://boardagendas.metro.net/board-members/

**Comment by shrayshray** [comment]
Excellent! The titles of 1st and 2nd Vice Chairs for Hilda Solis and Ara Najarian aren't showing though. See screenshot below - they're set in Legistar. Can you look into why they're showing as "Board Member" on the site, and have 1st and 2nd Vice listed after Chair, followed by other members in alphabetical order? We did this for last years members in #481 
![image](https://user-images.githubusercontent.com/28063988/87705935-896c2380-c753-11ea-8b6a-ad98ed08c611.png)

**Comment by hancush** [comment]
@shrayshray We hadn't previously seen 1st and 2nd vice chairs! I added them as board office titles and the members are displayed correctly: https://lametro-upgrade.datamade.us/board-members/

**Comment by shrayshray** [comment]
@hancush ah, got it! All looks great now, thank you.

**Comment by shrayshray** [comment]
@hancush could this be pushed to the live site as soon as possible? Thank you!

**Comment by hancush** [comment]
@shrayshray Pushed and refreshed cache – live site updated: https://boardagendas.metro.net/board-members/
