### ISSUE TITLE
Meetings: Exclude Service Council Public Hearings

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#634]
Similar to #606, we also need to exclude Service Council Public Hearings.

https://webapi.legistar.com/v1/metro/bodies?$filter=BodyTypeId eq 75

BodyTypeId: 75
BodyTypeName:  Service Council Public Hearings

This is the list of meetings with their info.

[
    {
        "BodyId": 269,
        "BodyGuid": "B81ED0C0-82C7-46CD-A139-A7DF807E6113",
        "BodyLastModifiedUtc": "2020-07-15T19:53:27.607",
        "BodyRowVersion": "AAAAAAEm8Vw=",
        "BodyName": "Gateway Cities Service Council Public Hearing",
        "BodyTypeId": 75,
        "BodyTypeName": "Service Council Public Hearings",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 270,
        "BodyGuid": "9F41A49C-D585-4AFE-BB19-5919F6C44AF4",
        "BodyLastModifiedUtc": "2020-07-15T19:54:49.217",
        "BodyRowVersion": "AAAAAAEm8WM=",
        "BodyName": "San Fernando Valley Service Council Public Hearing",
        "BodyTypeId": 75,
        "BodyTypeName": "Service Council Public Hearings",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 271,
        "BodyGuid": "6BEBAD2D-8E01-421D-A97E-CC03943BDA8D",
        "BodyLastModifiedUtc": "2020-07-15T19:55:33.03",
        "BodyRowVersion": "AAAAAAEm8Ww=",
        "BodyName": "San Gabriel Valley Service Council Public Hearing",
        "BodyTypeId": 75,
        "BodyTypeName": "Service Council Public Hearings",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 272,
        "BodyGuid": "7E9D0207-12A0-46CD-80F5-1BB5BB449BD3",
        "BodyLastModifiedUtc": "2020-07-15T19:55:50.437",
        "BodyRowVersion": "AAAAAAEm8X4=",
        "BodyName": "South Bay Service Council Public Hearing",
        "BodyTypeId": 75,
        "BodyTypeName": "Service Council Public Hearings",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    },
    {
        "BodyId": 273,
        "BodyGuid": "B68D50F0-AEEB-4A9D-8FCD-8986B0C5DCC0",
        "BodyLastModifiedUtc": "2020-07-15T19:56:15.093",
        "BodyRowVersion": "AAAAAAEm8Yc=",
        "BodyName": "Westside/Central Service Council Public Hearing",
        "BodyTypeId": 75,
        "BodyTypeName": "Service Council Public Hearings",
        "BodyMeetFlag": 1,
        "BodyActiveFlag": 1,
        "BodySort": 999,
        "BodyDescription": "",
        "BodyContactNameId": 1862,
        "BodyContactFullName": "Dolores Ramos",
        "BodyContactPhone": "",
        "BodyContactEmail": "ramosd@metro.net",
        "BodyUsedControlFlag": 0,
        "BodyNumberOfMembers": 0,
        "BodyUsedActingFlag": 0,
        "BodyUsedTargetFlag": 0,
        "BodyUsedSponsorFlag": 0
    }
]

**Comment by hancush** [comment]
Done!

**Comment by hancush** [comment]
Also removed the existing Service Council Public Hearings from the Board Agendas site.
