### ISSUE TITLE
Board Report: Related board reports not populating as expected

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#648]
E.g., https://boardagendas.metro.net/board-report/2019-0800/ should have two related documents, but only one is showing.

**Comment by hancush** [comment]
It's working on the test site! https://lametro-upgrade.datamade.us/board-report/2019-0800/

**Comment by hancush** [comment]
I believe the addressed this in #669. @shrayshray Can you confirm the related reports look right for the example report: https://boardagendas.metro.net/board-report/2019-0800/?

**Comment by shrayshray** [comment]
@hancush The example report's related reports are populating as expected.
