### ISSUE TITLE
Board Report Search: Some terms missing from filters

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#650]
Omar noticed some tags missing from the "Subjects" section of the filters on the [search page](https://boardagendas.metro.net/search/).
To recreate, search "Customer Experience Plan" by typing in the search bar and clicking on the term in auto-suggest, then execute search.
If you look at the first report, 2018-0668, it's tagged with "NextGen Bus Study" and "Metro Vision 2028 Plan". If you click to expand "Filter by Subject", these terms do not appear in the list. 
In what we've seen so far, all the missing terms have had Class="Plan", "Program" or "Policy" (Subclasses of "Initiatives" ... but there are some other terms from those 3 classes which do appear, such as "Long Range Transportation Plan" and "Metro Equity Platform".
Could you look into why some terms are left out of the filter list?

**Comment by hancush** [comment]
@shrayshray How would you like us to prioritize this issue?

**Comment by shrayshray** [comment]
@hancush do you think there's time this month to at least look into it?

**Comment by hancush** [comment]
@shrayshray Sure!

**Comment by hancush** [comment]
Hey, @shrayshray! This was a fun question. The answer is that our search engine is configured to return at most 100 tags, in order of most hits to least, in each category. For the example search, if you click on the NextGen Bus Study tag under the initial result, you can see there are only 30 results from the original query with that tag. The smallest number of hits on the top 100 tags for the original query is 41, so NextGen Bus Study didn't make the cutoff. 

It'd be negligible to change the max number of tag facets that come back if you'd like. I think whether we should do so really depends on what purpose you want the facets to serve. Right now, they highlight topics that most often appear with the user's search, i.e., topics they're most likely to care about. We could broaden that view, though I'd caution against showing too many, as they decrease in relevance the fewer hits they're associated with, and especially because there are other entry points to unlisted topics, such as with the search result, as you discovered.

What do you think?

**Comment by hancush** [comment]
Some ideas:

- Add a new facet for Metro plans, policies, and programs
- Add this particular relationship to related terms (HCG will update this issue with SES call / response for how related terms are populated for the test query)

**Comment by shrayshray** [comment]
Yes, let's add a new facet. Terms in the facet Plans, Programs and Policies will have a class of either:
Plan
Program
Policy

**Comment by hancush** [comment]
@fatima3558 I'd like you to give this issue a shot! 

Metro Councilmatic classifies topics based on a third-party system called SES. The task here is to add a new facet that includes topics from the SES classes `Plan`, `Program`, and `Policy`. Luckily, scaffolding for adding new facets already exists. 

The high level steps of this task are as follows:

1. Add a new facet, `plan_program_policy`, and a corresponding `prepare_plan_programming_policy` function to the Haystack index and Solr schema. (You can copy/paste a similar facet, e.g., `motion_by` and `motion_by_exact`, and swap in the new facet name to update the Solr schema. When you make this change, refer to the local development portion of [Making changes to the Solr schema](https://github.com/datamade/la-metro-councilmatic#making-changes-to-the-solr-schema) to learn how to reload Solr with your updated config.)
2. Add the new facet to classification choices on the `LAMetroSubect` model
3. Add the facet name and corresponding SES classes to the `FACET_CLASSES` mapping in the `refresh_guid` management command
4. Add an additional `facet()` call for the new facet to the search queryset in the search view
5. Update the search filter partial to display the `ordered_search_filter_items.html` partial for the new facet

You can see examples of all of these steps in the PR where I added the initial rich faceting: https://github.com/datamade/la-metro-councilmatic/pull/628

When you're ready to test your changes, run the `refresh_guid` management command to reclassify the topics in your database, then run the `rebuild_index` management command to rebuild your search index. Finally, head over to the search page and see whether your new facet is appearing. (N.b., you will need a working SmartLogic API key in your local settings file to run `refresh_guid`. If you don't have a key, get in touch and I'll send it over.)

I can't remember if you've worked with search before, but if not, some new concepts here are Solr, which is the search engine we use, and Haystack, which provides the interface for interacting with Solr from our Django application. All of the setup is already done, but I'd recommend Haystack's [Getting started](https://django-haystack.readthedocs.io/en/v2.8.1/tutorial.html) and [Faceting](https://django-haystack.readthedocs.io/en/v2.8.1/faceting.html) docs to help you get a handle on the Haystack-related changes you'll be making in this PR.

Let me know if you want to hop on a Hangout to ask questions and/or chat through these changes before you get started. Once you get going, if you get stuck on anything for more than an hour, Slack me and we can sort out the next step together. :-)

**Comment by shrayshray** [comment]
@hancush could you add the call that populates the search suggestions underneath the facets, as we discussed on our call?

**Comment by hancush** [comment]
Hi, @shrayshray, yes. We're making this call to the `concepts` endpoint: `https://cloud.smartlogic.com/svc/0dcee7c7-1667-4164-81e5-c16e46f2f74c/ses/CombinedModel/concepts/${TERM}.json?FILTER=AT=System:%20Legistar&stop_cm_after_stage=1&maxResultCount=5`

For "Customer Experience Plan", that translates to `https://cloud.smartlogic.com/svc/0dcee7c7-1667-4164-81e5-c16e46f2f74c/ses/CombinedModel/concepts/Customer Experience Plan.json?FILTER=AT=System:%20Legistar&stop_cm_after_stage=1&maxResultCount=5`

Here's the response:

```json
{
    "parameters": {
        "maxresultcount": "5",
        "fl": "* score [child limit=10000 parentFilter=\"(content_type:concept OR content_type:concept_scheme)\" childFilter=content_type:related_concept] [child limit=10000 parentFilter=\"(content_type:concept OR content_type:concept_scheme)\" childFilter=content_type:ordered_related_concept] [child limit=10000 parentFilter=\"(content_type:concept OR content_type:concept_scheme)\" childFilter=content_type:related_concept_scheme] [child limit=10000 parentFilter=\"(content_type:concept OR content_type:concept_scheme)\" childFilter=content_type:facet] [child limit=10000 parentFilter=\"(content_type:concept OR content_type:concept_scheme)\" childFilter=content_type:path_element] prefLabelCount:termfreq(conceptmap_en_plf, \"Customer\\ Experience\\ Plan\") altLabelCount:termfreq(conceptmap_en_f, \"Customer\\ Experience\\ Plan\")",
        "language": "\"en\", \"en\", \"en\"",
        "sort": "score desc, name_en_pl asc",
        "fq": "\"metadata_en_U3lzdGVtOiBMZWdpc3Rhcg__:true\", \"content_type:concept_scheme content_type:concept\"",
        "rows": "5",
        "version": "1",
        "structure": "JSON",
        "command": "conceptmap",
        "filter": "AT=System: Legistar",
        "q": "conceptmap_en_plf:Customer\\ Experience\\ Plan^1000.0  conceptmap_en_f:Customer\\ Experience\\ Plan^100.0  conceptmap_en_pl:Customer\\ Experience\\ Plan^10.0  conceptmap_en:Customer\\ Experience\\ Plan^1.0 ",
        "stop_cm_after_stage": "\"1\", \"1\"",
        "wt": "sesConceptsJSON"
    },
    "terms": [
        {
            "term": {
                "name": "Customer Experience Plan",
                "displayName": "Customer Experience Plan",
                "id": "e671909f-ed00-473b-b7db-dc690529558d",
                "uri": "http://example.com/CombinedModel#CustomerExperiencePlan",
                "classes": [
                    "Plan"
                ],
                "weight": "9806.911",
                "facets": [
                    {
                        "name": "Plans, Programs and Policies",
                        "freq": 0,
                        "id": "c8e158b8-6ced-4dd6-9e17-1f069c81db9c"
                    }
                ],
                "freq": "0",
                "documents": "0",
                "createdDate": "2020-07-21T18:16:41+0000",
                "lastUpdatedDate": "2020-09-30T17:02:20+0000",
                "equivalence": [
                    {
                        "qty": "2",
                        "name": "acronym",
                        "fields": [
                            {
                                "field": {
                                    "name": "CX"
                                }
                            },
                            {
                                "field": {
                                    "name": "CXP"
                                }
                            }
                        ]
                    },
                    {
                        "qty": "3",
                        "name": "Use For",
                        "fields": [
                            {
                                "field": {
                                    "name": "Customer Experience (CX) Planning"
                                }
                            },
                            {
                                "field": {
                                    "name": "Customer Experience Planning"
                                }
                            },
                            {
                                "field": {
                                    "name": "Metro Customer Experience Plan"
                                }
                            }
                        ]
                    }
                ],
                "hierarchy": [
                    {
                        "qty": "1",
                        "name": "Broader Term",
                        "abbr": "BT",
                        "fields": [
                            {
                                "field": {
                                    "name": "Plans, Programs and Policies",
                                    "freq": 0,
                                    "id": "c8e158b8-6ced-4dd6-9e17-1f069c81db9c"
                                }
                            }
                        ]
                    }
                ],
                "associated": [
                    {
                        "qty": "3",
                        "name": "Related To",
                        "abbr": "RT",
                        "fields": [
                            {
                                "field": {
                                    "name": "Customer satisfaction",
                                    "freq": 0,
                                    "id": "926d80a4-bd2f-4e87-a167-7e0f2db7916b"
                                }
                            },
                            {
                                "field": {
                                    "name": "Customer service",
                                    "freq": 0,
                                    "id": "babbc26e-a614-4dab-b062-d3dbc8c99a5e"
                                }
                            },
                            {
                                "field": {
                                    "name": "Recovery and Restoration Task Force (Metro)",
                                    "freq": 0,
                                    "id": "8b3bd8ea-1a16-42aa-b90f-402a6889fb19"
                                }
                            }
                        ]
                    }
                ],
                "paths": [
                    {
                        "path": [
                            {
                                "field": {
                                    "name": "Plans, Programs and Policies",
                                    "freq": 0,
                                    "id": "c8e158b8-6ced-4dd6-9e17-1f069c81db9c"
                                }
                            },
                            {
                                "field": {
                                    "name": "Customer Experience Plan",
                                    "freq": 0,
                                    "id": "e671909f-ed00-473b-b7db-dc690529558d"
                                }
                            }
                        ],
                        "name": "Narrower Term",
                        "abbr": "NT"
                    }
                ],
                "metadata": {
                    "System: SharePoint 365": "1",
                    "System: Legistar": "1",
                    "definition": "<p>Customer Experience (CX) is the sum total of the experiences our [Metro's] customers have at every stage of their journey. The goal is to minimize pain points, maximize smooth, uneventful experiences, and find opportunities for occasional surprise and delight.</p><p><br/></p><p><br/></p><p>For 2020 Plan, focus on Option C/pain points and Covid Recovery. Dig deeper into journey mapping and best practices in 2021.<br/></p>",
                    "URI": "http://example.com/CombinedModel#CustomerExperiencePlan"
                },
                "src": "1"
            }
        }
    ],
    "total": "1"
}
```

I would actually expect to see all three of those associated terms listed, but I only see one on the live site... looks like there's a bug in the script to populate related terms. I will take a look at that.

**Comment by hancush** [comment]
Oh, I see – we only render related terms if they're associated with a board report in the search index. "Customer service" is the only associated term that's also a topic.

**Comment by shrayshray** [comment]
thank you, @hancush ! This confirms what we suspected after looking into it further. @camachoo is looking into a work-around where we can relate terms we'd like to see suggested without them contributing to the relevancy score of the term itself, or having other impacts on the baseline auto-tagging.

**Comment by fatima3558** [comment]
@shrayshray hannah and I have successfully deployed the new facet to the staging site. Could you check the changes on the site and let us know if they look good to you? Thanks!

**Comment by shrayshray** [comment]
@fatima3558 this looks great! Exactly what I would expect. Thank you!
