### ISSUE TITLE
Add new Public Comment info

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#652]
Please add the following info to the Public Comment sections which show during the meeting, and hide before and after. Omar is confirming whether the eComment option will continue to be available and will report back.

Participant Instructions
The conference begins at 10:00 AM Pacific Time on September 24, 2020; you may join the conference 5 minutes prior.
Dial-in: 888-251-2949 or 215-861-0694
English Access Code: 8231160#
Spanish Access Code: 4544724#
Need an international dial-in number?
Need assistance with your audio? Please dial 888-796-6118.

**Comment by hancush** [comment]
Hey, @shrayshray! Obviously the date and time in this message will change depending on the event. Are the dial-in and access codes consistent, or will they depend on the event, as well?

**Comment by shrayshray** [comment]
@hancush my understanding based on Omar's email is the dial-in and access codes will be consistent.

**Comment by hancush** [comment]
@camachoo, is there a generic link I should use for the international dial-in number? The one in your original email does not work when I add it to the site: https://www.teleconference.att.com/servlet/glbAccess?process=1&accessNumber=8882512949&accessCode=8231160&data=02|01|CamachoO@metro.net|a3703f3f0bb242d9b6fb08d85b25ec57|ab57129bdbfd4cacaa77fc74c40364af|0|0|637359565723000140&sdata=ft51LLU3MCgbfVr/ajVShtcy/5D3p1/V3+wV0ktFyR8=&reserved=0

**Comment by hancush** [comment]
Will wait for guidance from Omar on text changes. In the meantime, I've added the dial-in info to the block that shows during the meeting.

Here's what event headings will look like at each stage.

### Before meeting, no agenda:

![Screen Shot 2020-09-17 at 2 39 21 PM](https://user-images.githubusercontent.com/12176173/93519320-ba073f80-f8f3-11ea-8ac9-15d8a1a14f81.png)

### Before meeting, agenda posted:

![Screen Shot 2020-09-17 at 2 38 05 PM](https://user-images.githubusercontent.com/12176173/93519328-bb386c80-f8f3-11ea-885d-35c6cb29793f.png)

### During meeting:

![Screen Shot 2020-09-17 at 2 43 21 PM](https://user-images.githubusercontent.com/12176173/93520266-297d2f00-f8f4-11ea-87be-f22b9137bece.png)

### After meeting:

![Screen Shot 2020-09-17 at 2 38 28 PM](https://user-images.githubusercontent.com/12176173/93519322-ba9fd600-f8f3-11ea-8245-8d97b64fa39f.png)

**Comment by shrayshray** [comment]
@hancush this looks perfect! We also just got notification online public comment will no longer be available, so those links can be removed for now. Actually, it might make more sense to just hide them, as this change is by request of this year's Chair and a future Chair may wish to use the online option.

**Comment by shrayshray** [comment]
@hancush yes, leave the email / postal mail instructions. Also add "When you call in to comment, you will be able to hear the live stream of the meeting while you wait to comment. If you are also listening to the meeting on another device, **please lower the volume on the second device to avoid feedback and ensure you can be heard clearly.**"

**Comment by shrayshray** [comment]
@hancush Omar would like these changes push through now, is it possible to go live today?

**Comment by shrayshray** [comment]
@hancush update: waiting til Monday is fine, but by EOD Monday, please. Sorry to push this "emergency" on to you, after the final updates were pushed to us so late in the day. I really appreciate you always rolling with these last minute changes along with Omar and me. It truly helps me sleep better at night - thanks for being on our team.

**Comment by hancush** [comment]
Ok, @shrayshray. I will preserve the pre-meeting instructions and update the dial-in instructions.

Can you please advise about the international dial-in link? https://github.com/datamade/la-metro-councilmatic/issues/652#issuecomment-694453637

**Comment by hancush** [comment]
@shrayshray I've updated the text per your instructions.

**Agenda posted, before meeting starts**

<img width="1381" alt="Screen Shot 2020-09-21 at 2 09 34 PM" src="https://user-images.githubusercontent.com/12176173/93810596-82123c00-fc14-11ea-9cab-65f0b25b942f.png">

**During meeting**

<img width="1394" alt="Screen Shot 2020-09-21 at 2 11 54 PM" src="https://user-images.githubusercontent.com/12176173/93810608-88a0b380-fc14-11ea-9e2d-d7cf1f7ffb70.png">

1. Previously, we indicated that people could comment online during the meeting ("Online public comment will be available on this page once the meeting begins.") Should we show any indication that users can call in during the meeting, before the meeting starts?
2. The international dial-in link goes here:

<img width="1440" alt="Screen Shot 2020-09-21 at 2 14 14 PM" src="https://user-images.githubusercontent.com/12176173/93810873-df0df200-fc14-11ea-85ec-0fc5aa5854af.png">

Is that what you expect? If not, what is the correct link?

I am online until 4 p.m. Central. Happy to publish these updates today, provided I hear back from you in time. Please let me know at your earliest convenience.

**Comment by camachoo** [comment]
@hancush<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhancush&data=02%7C01%7Ccamachoo%40metro.net%7C7ffc086c27b74a94f62a08d85c34f955%7Cab57129bdbfd4cacaa77fc74c40364af%7C0%7C0%7C637360729891141265&sdata=yr5zq9QoZUj1Qx3BOgTkB0RVLLoMNo5D8vCtRUCruTw%3D&reserved=0> Thank you.  I think we need to have some logic and formatting changes to make things clear for users.

  1.  The "Submit public comment remotely" heading should be consistent before and during the meeting.
  2.  The "Before the meeting" section should disappear at 5pm PST the day before the meeting and be replaced with the call in participant instructions.  This way users will know that they can call in to the meeting 5 minutes before the meeting is supposed to start.
  3.  A heading of "During the meeting" should be below "Submit public comment remotely" heading and above the "Participant instructions" heading, and should be using the same grey heading format as "Before the meeting".
  4.  The heading "Participant instructions" should be changed to "Phone participant instructions", and should be using the same grey heading format as "Before the meeting".
  5.  Change the language "The conference begins at 10:00 AM Pacific Time on September 24, 2020; you may join the conference 5 minutes prior." to "You may join the public comment participation call 5 minutes prior to the start of the meeting."

________________________________

**Comment by hancush** [comment]
@camachoo I will not be able to add logic to show dial-in instructions the day before the meeting before my work day is over in 30 minutes.

I can update the copy and leverage existing logic to show dial-in instructions while the meeting is ongoing. I can also add generic language about comment phone phone prior to the meeting, something like. "You can submit public comment by phone during the meeting. Dial-in instructions will be available on this page during the meeting" 

Will that work? And can you please advise about the international call in link? Thank you.

**Comment by camachoo** [comment]
@hancush<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhancush&data=02%7C01%7Ccamachoo%40metro.net%7C7ffc086c27b74a94f62a08d85c34f955%7Cab57129bdbfd4cacaa77fc74c40364af%7C0%7C0%7C637360729891141265&sdata=yr5zq9QoZUj1Qx3BOgTkB0RVLLoMNo5D8vCtRUCruTw%3D&reserved=0> Can we just work on this tomorrow?

Let's just remove the international information all together.  I have not received any responses to my inquiries.

________________________________

**Comment by hancush** [comment]
@camachoo 

> Can we just work on this tomorrow?

Sure! I was under the impression this needed to be finished today.

**Comment by camachoo** [comment]
@hancush<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhancush&data=02%7C01%7Ccamachoo%40metro.net%7C7ffc086c27b74a94f62a08d85c34f955%7Cab57129bdbfd4cacaa77fc74c40364af%7C0%7C0%7C637360729891141265&sdata=yr5zq9QoZUj1Qx3BOgTkB0RVLLoMNo5D8vCtRUCruTw%3D&reserved=0> It was.  I was able to push back under the objective of getting this done right since this was rushed in the first place and want to have as few mistakes as possible.
________________________________

**Comment by hancush** [comment]
Got it. I have some new logic drafted. I'll finalize and deploy to staging tomorrow so you can take a look. Will update this thread when it's in place. Thanks, @camachoo!

**Comment by hancush** [comment]
@shrayshray, @camachoo – Changes have been deployed to the staging site. You can see the pre-meeting instructions on this week's event pages. 

Did you two want to create a test event for tomorrow and check this evening that the dial-in instructions are shown as expected? Just let me know, and I'll make sure to grab it.

**Comment by hancush** [comment]
(FWIW, you can see demo screenshots in this PR description: https://github.com/datamade/la-metro-councilmatic/pull/653)

**Comment by shrayshray** [comment]
@hancush, this looks great to me. @camachoo did you want to test?

**Comment by hancush** [comment]
At this point, tomorrow's meetings could be used to test on the staging site. Could also deploy to test on the live site. I'll leave it up to you two, @shrayshray and @camachoo, just let me know.

**Comment by camachoo** [comment]
Let's deploy to the test site.
________________________________

**Comment by camachoo** [comment]
Never mind...  It looks good.  We probably won't be able to test the changes and timing.
________________________________

**Comment by hancush** [comment]
Got it. These changes have been deployed to the live site. Give tomorrow's board meeting a look after 5 p.m. today to confirm that the before meeting instructions have been removed and the public comment dial-in instructions have been added: https://boardagendas.metro.net/event/regular-board-meeting-66b775f8c695/

(Also, I turned off online public comment across the site with this change site, so there should no longer be public comment text or links on the homepage or event pages!)

**Comment by shrayshray** [comment]
@hancush the public comment dial-in instructions still aren't showing up on the site. It still just shows the message about it being posted this evening.
![image](https://user-images.githubusercontent.com/28063988/94087247-238ac080-fdc2-11ea-90b0-279498b08614.png)

**Comment by hancush** [comment]
@shrayshray I saw that at 5 p.m. your time, but checked again at 6 p.m. your time and there they were. I bet there's something wonky going on with timezones, specifically daylight vs. standard time. Will look into it! (But in the meantime, the dial-in info is live for today's meetings!)

**Comment by shrayshray** [comment]
@hancush I was also thinking it might be a timezone thing. You're right, all was good this morning. Thanks for turning this around so quickly!

**Comment by hancush** [comment]
@shrayshray Just pushed a change to address the time zone snafu! Let's keep an eye on this ahead of next week's meetings. (Alternatively, if you want to do a test event, just let me know and I'll make sure it gets imported into the staging site promptly.)

**Comment by shrayshray** [comment]
Comment info for tomorrow's meetings is showing up on time and as expected!

**Comment by hancush** [comment]
Yay! With that, I think we can call this issue closed.
