### ISSUE TITLE
loaddata looks for a bill that does not exist.

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#66]
Here's the traceback from my most recent run of "loaddata":

<img width="820" alt="screen shot 2016-11-23 at 3 54 02 pm" src="https://cloud.githubusercontent.com/assets/13078679/20579958/3a7f7830-b195-11e6-9f71-5d693c54b3e0.png">

**Comment by reginafcompton** [comment]
@fgregg Is this an issue that you handled, when revisiting the import_data script? (In any case, this issue should be in django-councilmatic.)

**Comment by fgregg** [comment]
yes.
