### ISSUE TITLE
Search: Apostrophes are escaped to character references (&#39;) on search execution 

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#663]
Is it possible to use apostrophes instead of ACSII when executing a topic search for a term with an apostrophe in it? I can't tell if it's what's causing the issue retrieving tag results for "It's Off Limits" (quotes are for clarity here and not part of the query).

If a topic has an apostrophe (and perhaps other punctuation) in a word or phrase, when the topic is selected from the auto-suggest drop down, the search executes with ACSII code instead of the punctuation mark.
Example: "It's Off Limits" executes as "[It&#39;s Off Limits](https://boardagendas.metro.net/search/?q=It%27s+Off+Limits&search-all=on&result_type=topic)".
Search results are for "Off Limits", and clicking "Tag Search" returns zero results (edit - this is expected, it's not tagging yet).

Another example: "Twenty-Eight by '28 Initiative" executes as "[Twenty-Eight by &#39;28 Initiative](https://boardagendas.metro.net/search/?q=Twenty-eight+by+%2728+Initiative&search-all=on&result_type=topic)" and search results are for "Twenty-Eight Initiative". In this case, however, "Tag Search" returns 27 results as expected.

**Comment by hancush** [comment]
@shrayshray This is a display issue (the search executes as expected on the back end). 

Per https://github.com/datamade/la-metro-councilmatic/issues/640#issuecomment-712904281, terms containing single quotes are not handled correctly behind the scenes by our search engine, specifically when they are part of a "quoted phrase".  I'm still looking for an appropriate solution, but I'd like to break that off into a separate issue, as not to block the fixes for phrase search and the display of single quotes (this issue) in #662. 

I opened #666 (how fitting!!!) to track work on the back end fix for phrases containing single quotes.
