### ISSUE TITLE
Home: Text overlapping on mobile site

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#674]
Omar and I are both seeing overlapping text on the Home page of the mobile site (Android/Chrome and iOS/Safari). 
"Current Meeting" or "Next Meeting" header overlaps the red text below the search bar "Search the Metro Board Archive from 1952-2015 (Board Boxes 1994-Present)"
![image](https://user-images.githubusercontent.com/28063988/99593453-89508e80-29a6-11eb-8094-3becc7a046da.png)

**Comment by fatima3558** [comment]
@shrayshray we've implemented a fix that's available for you to take a look at on the staging site. Let us know how it looks to you!

**Comment by shrayshray** [comment]
@fatima3558 looks great on staging, thank you!
