### ISSUE TITLE
Meeting: Add pound 2 to public comment instructions 

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#675]
Please add to the public comment instructions a line about entering pound 2
“To give public comment on an item, enter #2 (pound two) when that item is taken up by the Board.”
Ideally, after the Spanish Access Code:

 
![poundtwo](https://user-images.githubusercontent.com/28063988/99611594-d6ddf300-29c8-11eb-919c-bb5b30f8503d.png)

**Comment by hancush** [comment]
@shrayshray This was a quick fix! It's been deployed to the live site.

**Comment by shrayshray** [comment]
@hancush perfect, thank you!
