### ISSUE TITLE
Board Members: Replace John Bulinski with Tony Tavares

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#676]
Non-voting board member John Bulinski has retired, and Tony Tavares has been appointed to replace him. Legistar has been updated so Bulinski's term ends 11/29/2020 and Tavares's begins 11/30/2020 for the Regular Board and all Committee assignments. 
Tavares's first meetings will be the Regular Board and Crenshaw Project Corporation on 12/3, so we'd like to have this update to the site made in advance of 12/3.
Tavares' title and role in the list on the [Board Members page](https://boardagendas.metro.net/board-members/) will be the same and Bulinski's: 
![image](https://user-images.githubusercontent.com/28063988/100154558-a085f500-2e5a-11eb-8cb3-1b26e2693e85.png)

Attached is a PDF with his headshot and bio for his board member page.
[Tony Tavares bio Nov 2020.pdf](https://github.com/datamade/la-metro-councilmatic/files/5592940/Tony.Tavares.bio.Nov.2020.pdf)

**Comment by hancush** [comment]
@shrayshray Can you send his headshot separately, as an image file? Please and thank you!

**Comment by hancush** [comment]
Also, it looks like Bulinski still has a current office:

```
<GranicusOfficeRecord>
<OfficeRecordBodyId>139</OfficeRecordBodyId>
<OfficeRecordBodyName>Finance, Budget and Audit Committee</OfficeRecordBodyName>
<OfficeRecordEmail/>
<OfficeRecordEndDate>2021-06-30T00:00:00</OfficeRecordEndDate> <---------
<OfficeRecordExtendFlag>0</OfficeRecordExtendFlag>
<OfficeRecordFirstName>John</OfficeRecordFirstName>
<OfficeRecordFullName>John Bulinski</OfficeRecordFullName>
<OfficeRecordGuid>1F8A25FE-7A52-4051-8DB8-376DFF92FFEF</OfficeRecordGuid>
<OfficeRecordId>1217</OfficeRecordId>
<OfficeRecordLastModifiedUtc>2020-07-31T20:56:16.25</OfficeRecordLastModifiedUtc>
<OfficeRecordLastName>Bulinski</OfficeRecordLastName>
<OfficeRecordMemberType>Member</OfficeRecordMemberType>
<OfficeRecordMemberTypeId>3</OfficeRecordMemberTypeId>
<OfficeRecordPersonId>2113</OfficeRecordPersonId>
<OfficeRecordRowVersion>AAAAAAE4eo4=</OfficeRecordRowVersion>
<OfficeRecordSort>10</OfficeRecordSort>
<OfficeRecordStartDate>2020-07-01T00:00:00</OfficeRecordStartDate>
<OfficeRecordSupportFullName i:nil="true"/>
<OfficeRecordSupportNameId i:nil="true"/>
<OfficeRecordTitle>non-voting member</OfficeRecordTitle>
<OfficeRecordVoteDivider>0</OfficeRecordVoteDivider>
</GranicusOfficeRecord>
```

See https://metro.legistar.com/PersonDetail.aspx?ID=206944&GUID=B1F986AD-B5B6-4B50-A6CB-18A514F89E5E&Search=.

Does this need to be updated, @shrayshray?

**Comment by shrayshray** [comment]
@hancush ah yes, I missed Finance, Budget and Audit - just made the update in Legistar.

**Comment by shrayshray** [comment]
Tony's picture:
![Tony_Tavares-8x10@300dpi](https://user-images.githubusercontent.com/28063988/100818233-8e79f880-33fe-11eb-9cf6-f9404d3bbbe5.jpg)

**Comment by hancush** [comment]
Welcome, Tony Tavares! https://boardagendas.metro.net/person/tony-tavares-a81515b1c413/

**Comment by shrayshray** [comment]
@hancush perfect, thank you!
