### ISSUE TITLE
Board Members: Remove John Fasana

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#680]
John Fasana has retired and his term on the Regular Board and Committees has been updated to end December 31, 2020. Please remove him from the website. We don't know yet who will replace him.

**Comment by hancush** [comment]
Thanks for the heads up! I've removed Fasana's memberships ending in 2021 (as they're replaced by the ones ending 12/31), so he should automatically be removed from the site come Jan. 1. Will set a reminder to check when we return from our break 1/4.

**Comment by hancush** [comment]
Looks like Fasana has stayed retired in our database. Let me know if you see otherwise, @shrayshray, otherwise we can mark this one done!

**Comment by shrayshray** [comment]
@hancush looks good!
