### ISSUE TITLE
Board Members: Replace Robert Garcia's headshot

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#681]
Robert Garcia has a new headshot (attached). Please update it on the site.
![mrg_officialphoto](https://user-images.githubusercontent.com/28063988/101839434-370f1300-3af7-11eb-92e1-7dd5d64e1d0a.jpg)

**Comment by shrayshray** [comment]
Here is a version cropped for consistency with the other board member pictures.
![Robert_Garcia_200x250.png](https://images.zenhubusercontent.com/5f4e8ba43612f72a1d435022/f09901f0-4ebd-47f3-bfaf-f35fb5d0d883)

**Comment by hancush** [comment]
@shrayshray Done! (I needed to hard refresh for the new image to show up, but it's there.)
