### ISSUE TITLE
Board Members: Replace Mark Ridley-Thomas with Holly Mitchell

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#683]
Holly Mitchell was elected as the new Los Angeles County Board Supervisor for District 2. Please remove Mark Ridley-Thomas from the Board Members and replace him with Mitchell. Below are her bio and headshot.

---
![Holly_OrangeDredress_CU-1](https://user-images.githubusercontent.com/28063988/101953576-700abe80-3baf-11eb-85ee-5a508ee83cae.jpg)

On November 3, 2020, Supervisor Holly J. Mitchell was elected to serve the Second District of Los Angeles County. Throughout her career in public service, Supervisor Mitchell has always worked with the understanding – that creating a California where all residents can thrive – means investing in the communities, small businesses, families and children of LA County.

Having authored and passed over 90 laws in the California Legislature, Supervisor Mitchell brings an extensive public policy record to the Board of Supervisors. Many of her bills have been at the forefront of expanding healthcare access, addressing systemic racism, and championing criminal justice reform.

During her tenure in the California State Legislature, Supervisor Mitchell represented the 54th District for three years as an Assemblymember and later served seven years as State Senator for the 30th District.

As State Senator, she also held the distinction of being the first African American to serve as Chair of the Senate Budget and Fiscal Review Committee. In this capacity, she led the passage of state budgets each totaling over $200 billion for the fifth largest economy in the world.

Prior to serving in elected office, Supervisor Mitchell was CEO of Crystal Stairs, California’s largest nonprofit dedicated to child and family development. In this role, she ensured that families across Los Angeles County gained access to child care and poverty prevention resources. Before leading Crystal Stairs, she gained formidable experience in crafting public policy both as a former Senate district field representative and legislative advocate at the Western Center for Law and Poverty.

Supervisor Mitchell’s leadership has been recognized by over 100 community and business groups. She was recently honored as a 2020 Visionary by Oprah Winfrey’s O Magazine for making California the first state in the nation to ban natural hair discrimination with The CROWN Act.

As Supervisor, Mitchell is proud to serve the two million residents of the Second District which includes  the neighborhood she grew up in, Leimert Park, and the following cities: Carson, Compton, Culver City, Gardena, Hawthorne, Inglewood, Lawndale, Lynwood, parts of Los Angeles, and dozens of unincorporated communities.

Supervisor Mitchell is a University of California at Riverside Highlander, a CORO Foundation Fellow and mother to Ryan.

**Comment by hancush** [comment]
Note to self: `LAMetroPerson.objects.get(family_name='Ridley-Thomas').memberships.filter(end_date__startswith='2021').delete()`

**Comment by hancush** [comment]
Done!
