### ISSUE TITLE
Remove logic to skip Holly Mitchell committee memberships

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#687]
Shelly requested that we remove Mitchell's committee memberships until they're announced. As we don't have access to the show on InSite flag via the Legistar API, I instead added a check to manually skip scraping her committee memberships in https://github.com/opencivicdata/scrapers-us-municipal/pull/338. When they're announced, we should remove her from the people to skip array so her committee memberships come through.

Cc @shrayshray, just let us know when her memberships are announced and we can make the necessary change!

**Comment by hancush** [comment]
Unleash the memberships!

**Comment by hancush** [comment]
@fatima3558 ran into some trouble running the scrapers locally while testing this issue. Let's fully containerize the scrapers for local development to avoid sinking any more time into tricky database installations. 😵 https://github.com/opencivicdata/scrapers-us-municipal/issues/339

**Comment by shrayshray** [comment]
@hancush @fatima3558 can we prioritize this issue? The Board Chair staff are concerned with the inconsistency of what's on the site versus agenda.

**Comment by hancush** [comment]
@fatima3558 and I alley-ooped this one! Behold: Holly Mitchell's committee chairwomanship and membership are live: https://boardagendas.metro.net/person/holly-mitchell-68d838612b17/
