### ISSUE TITLE
Show today's meetings on the homepage on meeting days

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#694]
In place of the About section to the right of the upcoming / current meeting block, show the day's meetings and their status (passed, live, scheduled or something to that effect).

**Comment by hancush** [comment]
Part 1: Show the About section or a new "Today's Meetings" section, conditional on whether there are any meetings scheduled today.

Part 2: Render the day's meetings with the correct status. Leverage [existing code](https://github.com/datamade/la-metro-councilmatic/blob/1137e4b3e4cae435d8a81bc14342cfd54f543bbb/lametro/models.py#L634-L644) to determine whether a meeting is passed, ongoing, or scheduled.

@fatima3558 How about you submit a draft PR for review after you finish Part 1?

**Comment by fatima3558** [comment]
@hancush was able to get part 1 done without too much trouble. Here's the first part of the PR: https://github.com/datamade/la-metro-councilmatic/pull/698

**Comment by fatima3558** [comment]
@shrayshray The changes for this issue are now on the staging site! It looks like the soonest there will be meetings is Thursday, May 27. Could you give the staging site a look sometime then and let us know what you think?

**Comment by shrayshray** [comment]
@fatima3558 Wow, this looks great!!
![image](https://user-images.githubusercontent.com/28063988/119873482-7250a300-bed9-11eb-92a1-93d87143e02a.png)

**Comment by fatima3558** [comment]
@shrayshray great! are there any tweaks we should make before deploying to the live site?

**Comment by shrayshray** [comment]
@fatima3558 no tweaks at the moment, though I do want to keep an eye on how it displays on days with multiple meetings. I'm comfortable with going live though - thanks, Fatima!

**Comment by shrayshray** [comment]
@fatima3558 i noticed on little issue with display - the "upcoming" buble on the first meeting looks like it's cut-off on the line break: 
![image](https://user-images.githubusercontent.com/28063988/120525291-d3babb00-c38c-11eb-937a-3425a6962241.png)

**Comment by hancush** [comment]
@shrayshray Ah! What browser are you using?

**Comment by shrayshray** [comment]
@hancush Firefox. I just checked and it's happening on "Concluded", too - but it looks great in Chrome!

**Comment by hancush** [comment]
Thanks, @shrayshray! I just put a patch in and forced meetings to display to test in Firefox. See https://github.com/datamade/la-metro-councilmatic/pull/729#issue-660962057.

Ok to go ahead and deploy?

**Comment by shrayshray** [comment]
@hancush yes, ready to deploy!

**Comment by hancush** [comment]
It's live, @shrayshray!
