### ISSUE TITLE
map of post titles to board members

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#7]
@fgregg i've also included in parentheses the posts held by each board member that fulfill the membership requirement, in case we need to incorporate that

Mayor of Los Angeles: 
Eric Garcetti 

Los Angeles County Supervisors: 
Hilda L. Solis - district 1
Mark Ridley-Thomas - district 2
Sheila Kuehl - district 3
Don Knabe - district 4
Michael Antonovich - district 5

Appointee of Mayor of Los Angeles (two members of public, one city council member):
Jacquelyn Dupont-Walker 
Mike Bonin (Council Member, City of Los Angeles) 
Paul Krekorian (Council Member, City of Los Angeles)

Appointee of Governor of California:
Carrie Bowen (Caltrans District 7 Director) 

Appointee of League of California Cities ("each of whom shall be a mayor or a member of a city council"):
John Fasana - San Gabriel Valley sector (Council Member, City of Duarte)
James Butts - Southwest Corridor sector (Mayor, City of Inglewood)
Diane DuBois -  Southeast Long Beach sector (Council Member, City of Lakewood)
Ara Najarian - North County/San Fernando Valley sector (Council Member, City of Glendale)

p.s. would a list of cities in each sector be useful?

**Comment by fgregg** [comment]
This is great. I don't think we need a list of cities in the sectors.

**Comment by reginafcompton** [comment]
Map(s). Done.
