### ISSUE TITLE
Replace email address for public comment

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#700]
On Meeting/Agenda pages, please replace the email address for submitting public comments via email. Remove jacksonm@metro.net and replace with goinsc@metro.net
![image](https://user-images.githubusercontent.com/28063988/109051724-a7a5e480-768f-11eb-9683-efa640403eaf.png)

**Comment by hancush** [comment]
Done and deployed. Cc: @shrayshray
