### ISSUE TITLE
Search Page: Internal Service Error

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#703]
The Board Reports search page is showing an Internal Service Error: https://boardagendas.metro.net/search/
I noticed this after trying to click "Board Reports" in the navigation on the home page, but it also occurs when visiting the page directly.

**Comment by hancush** [comment]
Hey, @shrayshray, this was an instance of https://github.com/datamade/la-metro-councilmatic/issues/623. Might be a good one to prioritize!

**Comment by hancush** [comment]
(In the meantime, I've removed the offending item from the search index and all is well in search land: https://boardagendas.metro.net/search/)

**Comment by shrayshray** [comment]
@hancush thank you!
