### ISSUE TITLE
Document API calls used

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#704]
Sometimes Smartlogic makes updates to its API which might impact the calls Councilmatic makes to Semaphore. We'd like to have all the API calls used by our project documented for reference. Granicus doesn't tend to make these kind of updates, but it would also be useful to have all the calls to the Legistar API documented, too. Hannah recommended using a Google Doc, and linking to it from the dashboard.

**Comment by hancush** [comment]
- Where data comes from (scrapes)
- SES / other third-party integrations

Workflow / dependency diagram

**Comment by hancush** [comment]
Due by the end of 2021.
