### ISSUE TITLE
Board Members: Add Fernando Dutra

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#707]
Fernando Dutra will be replacing Robert Garcia as the representative of the Southeast Long Beach sector. His credentials on the page will be the same as Garcia's:
Appointee of Los Angeles County City Selection Committee
Southeast Long Beach sector
Sector appointee

And he should have the same sector area highlight on the map as Garcia did.
His bio and headshot are forth coming, but since his first meetings will be next week, it's a priority to have him added to the website.

**Comment by shrayshray** [comment]
Fernando Dutra's headshot and bio are below!

![Dutra August 2012_web](https://user-images.githubusercontent.com/28063988/110557403-62ed6500-80f5-11eb-8fb3-ff98c816d996.png)
Fernando Dutra was elected in April 2018 to represent District 4 for four years after being elected citywide in April 2014 to a four-year term. Fernando was initially appointed by the City Council in August 2012 to fill the remaining term of the Council seat vacated by Greg Nordbak.
Fernando and his wife, Mary, have three children—Sara, Megan, and Eric. The Dutras have lived in Whittier since 1987. Fernando is President of Allwest Development Company and holds licenses for general building contractor and general engineering.
Fernando served as a Member of the Planning Commission for six years from 2006 to 2012 and has served as Chairman of the Commission. Prior to his term on the Planning Commission, he served for six years on the Design Review Board. He has chaired the Metro Light Rail Extension Project Washington Boulevard Coalition; sits on the Whittier YMCA Board of Directors; and has served on the St. Gregory Parish Board. Fernando serves on the League of California Cities' Housing, Community & Economic Development Policy Committee.  On March 8, 2021, Fernando was appointed to the Los Angeles County Metro Board and serves on the Finance, Budget and Audit Committee and MTA Construction Committee.

**Comment by hancush** [comment]
We plan to address this on Friday!

**Comment by hancush** [comment]
Done and deployed!
