### ISSUE TITLE
Board Members: Remove Robert Garcia

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#708]
[Fernando Dutra is replacing Robert Garcia](https://github.com/datamade/la-metro-councilmatic/issues/707) on the Metro Board. Please remove Garcia from the list of Board Members, and from his Committee assignments if needed. His assignments have been removed in Legistar.

**Comment by hancush** [comment]
@shrayshray Done. Can you confirm that he'll continue his membership on the Special Construction Committee thru June, or [is the API incorrect](http://webapi.legistar.com/v1/metro/persons/1986/officerecords)?

**Comment by hancush** [comment]
Stashing query to remove these memberships:

```python
>>> p = LAMetroPerson.objects.get(family_name='Garcia')
>>> p.memberships.filter(end_date='2021-06-30').exclude(organization__name__in=['Crenshaw Project Corporation', 'Special Construction Committee'])
<QuerySet [<Membership: Robert Garcia in Board of Directors (Board Member)>, <Membership: Robert Garcia in Construction Committee (Member)>, <Membership: Robert Garcia in Operations, Safety, and Customer Experience Committee (Chair)>, <Membership: Robert Garcia in Construction Committee (Vice Chair)>]>
>>> p.memberships.filter(end_date='2021-06-30').exclude(organization__name__in=['Crenshaw Project Corporation', 'Special Construction Committee']).delete()
```

**Comment by shrayshray** [comment]
@hancush No, he won't continue on Special Construction, but yes, the the API was correct - I forgot to update that committee! I just changed his term so it ends 3/9/2021.

**Comment by hancush** [comment]
Got it. Removal complete, @shrayshray.

**Comment by hancush** [comment]
Edit to add: I've deployed a change to the scraper such that changes to a membership's end date will update the existing membership, rather than minting a new one (provided the start date stays the same). In other words, changes like this should be automatically captured moving forward.
