### ISSUE TITLE
Meetings: Remove 3/1 Regular Board Meeting

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#711]
A Regular Board Meeting on 03/01/2021 is showing on the site. It was created by mistake and has been deleted in Legistar. Please remove it from the website.

**Comment by hancush** [comment]
@shrayshray You should be able to remove this event from the site yourself, thanks to the changes in #697. Let me know if you have any questions / issues?

**Comment by shrayshray** [comment]
@hancush yes, sorry! I was having trouble with the login but figured it out and removed the event.

**Comment by hancush** [comment]
Sooo satisfying to hear it worked, though, @shrayshray! :-)
