### ISSUE TITLE
Add new CEO

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#730]
Metro has a new CEO, Stephanie Wiggins, who should replace Phil Washington on the website. I've requested her headshot and bio and will add them here once I receive them.

**Comment by shrayshray** [comment]
Stephanie Wiggins' bio and headshot have arrived!
[Stephanie Wiggins Bio 06 07 21 w photo.pdf](https://github.com/datamade/la-metro-councilmatic/files/6711089/Stephanie.Wiggins.Bio.06.07.21.w.photo.pdf)
![Stephanie N Wiggins (2)](https://user-images.githubusercontent.com/28063988/123307343-3d833c00-d4d7-11eb-9d77-e470bae3f379.jpg)

**Comment by hancush** [comment]
@fatima3558 In lieu of #399, can you pick this up before next Wednesday? The CEO is a non-voting post, so there are no scraper changes required! Instead, you can follow our docs on adding a member to the Metro app, starting here: https://github.com/datamade/la-metro-councilmatic#update-the-metro-app.
