### ISSUE TITLE
Hide related reports with non-public statuses

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#734]
[2021-0136](https://boardagendas.metro.net/board-report/2021-0136/) is related to [2021-0353](https://boardagendas.metro.net/board-report/2021-0353/). 2021-0353 is still a Draft, so the related report link in the sidebar of 2021-0136 goes to "Page not found". 
We'd like to update the logic for showing related reports to hide reports that are Drat, Approval review, or other non-public statuses. If they're not viewable on the web, they shouldn't show in the sidebar.

**Comment by hancush** [comment]
@shrayshray Just deployed a fix for this to the staging site! Observe: Draft report 2021-0353 is no longer listed as a related board report here: https://lametro-upgrade.datamade.us/board-report/2021-0136/

The logic is that related board reports will not be shown if they are private. A board report is private if one or more of the following is True:

- MatterRestrictViewViaWeb is True
- MatterStatusName is "Draft"
- MatterBodyName is "TO BE REMOVED"
- MatterTypeName is one of 'Board Box' or 'Board Correspondence' AND MatterStatusName is not "Sent"
- The board report isn't viewable in InSite

Can you help me to QA another board report or two with private related board reports, and also a couple of board reports without private related board reports, to confirm relations are hidden/shown as expected?
