### ISSUE TITLE
Event scrape: If there is more than one minutes file, which one should we use?

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#742]
@shrayshray @camachoo To reiterate from #740, I've deployed a patch to handle the case where there is more than one minutes file for a particular meeting to unblock event scrapes: https://github.com/opencivicdata/scrapers-us-municipal/pull/350. 

Let's move the conversation on how to handle that case here. Here's where we stand on the thread.

---

@camachoo:

Can we take the first appearance by date (opposite of most recent) that has an actual minute's history, if not then first appearance by date regardless of minute's history?

---

Me:

I want to take a quick step back and clarify how we get approved minutes currently:

- If there is EventMinutesFile in the API, use that
- If there is a minutes link in the UI, use that
- Otherwise, look for a file to approve minutes of the given meeting and use that (regardless of minutes history)
    - This is the step that currently expects one and only one file to exist

So, we're dealing with a case where we are trying to infer minutes from the file's title.

I bring this up because neither of the files we're dealing with right now was approved (as best I can tell). Would it be more accurate, if we get to this step, to look for an approval in the minutes history, or otherwise return nothing for approved minutes?

**Comment by hancush** [comment]
For December and January board meetings, there have been two attachments to the approve minutes item: One is the actual minutes file, and one is a public comment summary.

The minutes files are named like this: 

- 'December 2, 2021': 'Regular Board Meeting MINUTES - December 2, 2021'
- 'January 27, 2022': 'Regular Board Meeting MINUTES - January 27, 2022'

Currently, we need to handle this on a case by case basis. It would be better to add some logic to handle it. Will this naming convention (and condition of two attachments to minutes approval) be consistent moving forward?

**Comment by shrayshray** [comment]
@hancush unfortunately, we cannot guarantee this naming convention will be consistent moving forward.

**Comment by hancush** [comment]
Hmm, bummer. What about something less strict, such as the minutes file will always contain the word "minutes" (and the other attachments, e.g., public comment, won't)?

**Comment by shrayshray** [comment]
@hancush "minutes" in the file name is probably the best bet. Still can't 100% guarantee it will be there, but it's more likely than not.

**Comment by hancush** [comment]
Submitted a patch to look for an attachment containing "Minutes" for approval matters. We'll keep an eye on this to see whether there are any incorrect minutes files or if it ever happens that there's more than one attachment containing "Minutes".

**Comment by hancush** [comment]
@shrayshray will ask records folks to include minutes so this approach works.

**Comment by hancush** [comment]
@shrayshray and @camachoo will look for any errors in minutes files once meetings start up again in late summer / early fall. Will keep an eye on scrape failures on our side.

**Comment by hancush** [comment]
Standard naming conventions are hard to enforce – implement a logic similar to unpaired events where alerts are sent but the scraper does not break.
