### ISSUE TITLE
Links for events don't go to the right legistar page

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#75]
If you go to "View on the Metro website" for any event, for example https://lametro.datamade.us/event/finance-budget-and-audit-committee-d2a7a5d39152/

it does not take you to the appropriate legistar page. this is an upstream data issue that I'm trying to resolve right now. If we can't get it fixed we should disable the link.

**Comment by fgregg** [comment]
@reginafcompton, this is not possible to fix now. Please disable these links on event pages.

**Comment by reginafcompton** [comment]
@fgregg Links are disabled.

**Comment by reginafcompton** [comment]
DONE...we had two of the same issue.
