### ISSUE TITLE
Replace Recap link with Minutes link on event listing page

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#753]
![Screen Shot 2021-09-08 at 3.51.53 PM.png](https://images.zenhubusercontent.com/5b0dc8d3348b7966b4340de0/7ec0ae6d-9377-480a-96e8-0f81ec0cbb3b)

**Comment by hancush** [comment]
Working draft idea:

- Add logic to swap minutes link for recap link when minutes become available on the event listing item and on the event detail page
- Add link to recaps web folder at the top of the event listing page 
- Possible add link to recaps web folder at the top of the event detail page

**Comment by hancush** [comment]
@shrayshray Can you let us know the final desired functionality once you've had a chance to meet with your folks?

**Comment by shrayshray** [comment]
@hancush desired functionality: swap minutes link for recap link when minutes become available on the event listing item and on the event detail page.
We're not going to worry about the recaps folder at this time. Access to Minutes is priority, and Minutes supersede the recaps so we don't need to keep them around once the Minutes are ready. We also would like to add a new page dedicated to Minutes, but I will open a separate issue to address that.

**Comment by fatima3558** [comment]
Here are the relevant lines of code:
https://github.com/datamade/la-metro-councilmatic/blob/3a523b47f1d8fe08adbd58d797c027cf2c948cb1/lametro/templates/partials/past_event_day.html#L56-L74

Here is the logic I propose using instead of what is currently here:
* check if minutes exist and show them if they do
* if they do not, use recap link (and existing logic for displaying it)
@hancush seems like a small change, am I missing anything I should make sure to consider?

**Comment by hancush** [comment]
@fatima3558 Seems like a good plan for the event listening page! What about on the event detail page? Does it use the same partial or something else?

**Comment by fatima3558** [comment]
@hancush thanks for bringing my attention to that. The logic is very similarly set up, so I anticipate making very similar logic tweaks (check for minutes first, show recap if no minutes):
https://github.com/datamade/la-metro-councilmatic/blob/3a523b47f1d8fe08adbd58d797c027cf2c948cb1/lametro/templates/lametro/event.html#L221-L236

**Comment by hancush** [comment]
Cool, that makes sense to me! Thanks, @fatima3558. Proceed with a PR.

**Comment by fatima3558** [comment]
@shrayshray This is ready for you to take a look at! Here's an event that should show a minutes link instead of a minutes and recap link: https://lametro-upgrade.datamade.us/event/regular-board-meeting-ff063c93ee77/

**Comment by shrayshray** [comment]
@fatima3558 this looks great!!
