### ISSUE TITLE
New page: Minutes

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#770]
Because Minutes are the official record of Board meetings, we'd like to have a page dedicated to them so it's easier for users to get to them will minimal scrolling. Could you let us know an estimate of hours to create a new page for Minutes? Here is some context for this request:
1. We would like the new page to be included in the navigation at the top of the website, after "Board Reports" and before "Archive Search" 
![image](https://user-images.githubusercontent.com/28063988/141213136-fbfddf7d-7f81-4b5d-a968-7b40f061e10f.png)

2. Once we get it from our people, we will provide a spreadsheet with dates and links to Minutes from prior meetings.
3. Logic for adding links to the page for future meeting Minutes would be required.

**Comment by shrayshray** [comment]
[https://app.zenhub.com/files/70518566/98125240-70d8-4e17-b593-04b1d4dbeb76/download](https://app.zenhub.com/files/70518566/98125240-70d8-4e17-b593-04b1d4dbeb76/download)

**Comment by fatima3558** [comment]
proposed steps:
- [ ] identify any duplicate historical events that are currently searchable on the metro site
- [ ] import csv data based on risk and reach [utility method](https://github.com/datamade/risk-and-reach/blob/b5306f49a88804f55d70ee4bad5ac05e964d4b32/risk_and_reach/utils.py#L5) and [view](https://github.com/datamade/risk-and-reach/blob/b5306f49a88804f55d70ee4bad5ac05e964d4b32/risk_and_reach/views.py#L47)
- [ ] create a new view and list template that looks similar to the [events page on the metro site](https://boardagendas.metro.net/events/)

**Comment by fatima3558** [comment]
@shrayshray it looks like there are several events in the spreadsheet that are already in our database. From March 30, 2015 through the end of the spreadsheet, all events are currently searchable on the metro site except for the Special Board Meeting on May 21, 2015.

Wanted to check in about this information -- is the information in this spreadsheet different than the information we scrape from legistar?

**Comment by hancush** [comment]
@fatima3558 looking good! may i suggest splitting the last step into two? 

step 3a. created a view that lists all events and their minutes, both from the csv and the database
step 3b. implement the event filter ui (whether that's recycling the date picker from the event page or doing a simpler year picker)

thoughts?

**Comment by shrayshray** [comment]
@fatima3558 For 2015 forward, the information in the spreadsheet is the same as what is in Legistar. 2015 is when we first started using Legistar, and early on agendas PDF generated in Legistar were also added to the archive.

**Comment by fatima3558** [comment]
wherever available, Legistar data should take precedence over spreadsheet data
