### ISSUE TITLE
Meetings can be incorrectly reported as concluded when the previous meeting runs over

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#772]
Our logic to check whether a meeting has concluded assumes that if it's after a meeting's start time, but the meeting is not live, then that meeting has concluded. This isn't necessarily the case, as meetings can start late if a prior meeting runs over, or for some other reason.

If a previous meeting (or concurrently scheduled) meeting is still streaming, the meeting has not yet started and should not be marked as concluded.

It's a bit harder if there is not a previous meeting. For current meetings, we introduced a 20-minute buffer to account for late starts. @shrayshray, does a similar approach make sense here? What's a reasonable buffer for the start time of the first meeting of the day?

**Comment by hancush** [comment]
@shrayshray Is it true that every meeting will be broadcast? 

If so, we could simplify the logic to determine whether a meeting is over by marking a meeting as having been streamed when it is returned by the running events endpoint (http://metro.granicus.com/running_events.php). (We use this endpoint to determine when meetings are current.) Then, we can use that indicator to tell when the meeting has concluded. The logic would look like:

If the meeting has been streamed but is no longer ongoing, then it's concluded. Otherwise, it is not concluded.

What do you think?

**Comment by shrayshray** [comment]
@hancush Yes, every meeting will be broadcast. This sounds effective to me: "If the meeting has been streamed but is no longer ongoing, then it's concluded. Otherwise, it is not concluded."

**Comment by camachoo** [comment]
Reference screenshot for meetings occurring on 1/27/2022. Regular Board meeting had not started yet, but the LA Safe meeting was running.

—

Omar Camacho
Sr. Manager, Systems Projects, Research & Records Information Management
Office of Board Administration
213.922.2335

Metro Los Angeles
metro.net | facebook.com/losangelesmetro | @metrolosangeles
Metro provides excellence in service and support.

**Comment by hancush** [comment]
I will draft this ahead of February meetings and we'll trial it on staging!

**Comment by hancush** [comment]
@shrayshray I've deployed the change in logic to the staging site: https://lametro-upgrade.datamade.us/

Can you keep an eye on it during this week's meetings and let me know whether you spot anything amiss?

**Comment by hancush** [comment]
FYI @shrayshray @camachoo this is redeployed to staging for testing during today's meeting: https://lametro-upgrade.datamade.us/

**Comment by shrayshray** [comment]
Apologies, I was caught up in other troubleshooting during last week's meetings. I set up a calendar reminder to watch the site during next month's meetings and will report back.

**Comment by hancush** [comment]
No problem, @shrayshray, sounds like a plan! 👍

**Comment by hancush** [comment]
This, along with #790, has been staged ahead of tomorrow's meetings, @shrayshray!

**Comment by shrayshray** [comment]
@hancush Today's meeting didn't run over, but it was showing as "In Progress" and "Concluded" as expected! Will keep an eye out tomorrow as well.

**Comment by hancush** [comment]
Deployed.
