### ISSUE TITLE
New Page: Contact us

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#773]
The Board Clerk would to have a new page added to the site: "Contact Us"
We'd like this page to be linked in the top navigation, after "Archives Search".

Content for the "Contact Us" page:
"For questions about or comments for the Metro Board, please contact boardclerk@metro.net. Written public comment can be mailed to: Board Administration, 1 Gateway Plaza, Mail Stop 99-3-1, Los Angeles, CA 90012.
If you are commenting on a specific item, please include the item number and your position on it - for, against, general comment, or item needs more consideration - in your message.  **Written public comment (via mail or email) must be received by 5pm the evening prior to the meeting where the item will be considered.**
To provide live public comment during a meeting, please see page 4 of the agenda where item appears for instructions on how to call into the meeting.

For questions about this website or Board records, please email boardreport@metro.net"

Could you please also update the ["Contact Us" section of the "About" page](https://boardagendas.metro.net/about/#contact) with this same info in the meantime?

**Comment by fatima3558** [comment]
@shrayshray working on this now -- would you like the text for the Contact Us page to appear on the site twice? One on the new "Contact Us" page, and once on the "Contact Us" section of the About page? Or just once on the new "Contact Us" page?

**Comment by fatima3558** [comment]
@shrayshray happy new year! bumping the above question for you:

> @shrayshray working on this now -- would you like the text for the Contact Us page to appear on the site twice? One on the new "Contact Us" page, and once on the "Contact Us" section of the About page? Or just once on the new "Contact Us" page?

**Comment by fatima3558** [comment]
@shrayshray hello again! bumping the above question one more time:

> @shrayshray working on this now -- would you like the text for the Contact Us page to appear on the site twice? One on the new "Contact Us" page, and once on the "Contact Us" section of the About page? Or just once on the new "Contact Us" page?

**Comment by shrayshray** [comment]
@fatima3558 so sorry for holding you up on this! We'd like the contact information on both the Contact Us page, and in the "Contact Us" section of the About page.

**Comment by hancush** [comment]
@shrayshray New page and about page update have been deployed to staging. Can you have a look and confirm everything looks good?

**Comment by fatima3558** [comment]
@shrayshray happy Monday! could you take a look at the staging site and confirm that the 'Contact Us' text in the new page & the About page looks good to you?

**Comment by shrayshray** [comment]
@fatima3558 Looks GREAT! Thank you!
