### ISSUE TITLE
Reorganize nav

### ISSUE THREAD

**Issue by fatima3558** [datamade/la-metro-councilmatic#785]
Due to the addition of the 'Contact Us' page in the navigation, the navigation bar is wrapping and taking up more vertical space than intended on certain window widths:
<img width="1202" alt="Screen Shot 2022-01-11 at 12 36 58 PM" src="https://user-images.githubusercontent.com/48227264/149001599-6a392801-dc9d-4ea8-a79c-c2a22868561b.png">

@shrayshray We can group some of these nav items into sub-menus or potentially move some of these items so that they only live in the footer, for example. Would either of these, or another, approach work for you?

**Comment by hancush** [comment]
Ideas from 1/18 priorities:

About
  - Board of Directors
  - Committees
  - Contact Us
Search
  - Board Reports
  - Archive Search
Meetings and Agendas
  - Minutes

Shelly and Omar to get internal feedback and let us know.

**Comment by hancush** [comment]
Shelly to follow up on this in Feb. Let us know when you hear back, @shrayshray!

**Comment by shrayshray** [comment]
@hancush feedback received! They like this grouping:

- About 
Board of Directors
Committees
Contact Us
About us [Change name of current About page]

- Search 
Board Reports
Archive Search

- Meetings 
Meetings and Agendas 
Meeting Minutes

**Comment by antidipyramid** [comment]
@shrayshray New navbar is up on the [staging site](https://lametro-upgrade.datamade.us/)! How does it look?
