### ISSUE TITLE
Board Reports Search: Open search results in new tab

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#788]
User report: "When I do a subject search and I get a list of links back, I’ll open one, then use the browser back button, and the search results are gone, I have to re-run the search term to get my search results list back.  Is there another back arrow or button in the webpage I’m not seeing?"
I was able to replicate this issue in Firefox, and with keyword search results and filters.

**Comment by hancush** [comment]
Syncing up this thread from email: 

> This is a result of the recaptcha implementation and is expected behavior. Please let us know if a change to this behavior is high priority.

**Comment by hancush** [comment]
Let's open search results in a new tab!

**Comment by antidipyramid** [comment]
@shrayshray The staging site now opens Board Report search results in a new tab. How does it look on your end?

https://lametro-upgrade.datamade.us/search/

**Comment by shrayshray** [comment]
@antidipyramid looks fantastic, thank you!
