### ISSUE TITLE
HOMEPAGE: Add recently passed meetings to the homepage

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#790]
![Screen Shot 2022-02-02 at 3.37.31 PM.png](https://images.zenhubusercontent.com/5b0dc8d3348b7966b4340de0/b3e9e9f4-8de6-41df-8118-4f50e744072b)

Add a bit more visual distinction between blocks. @shrayshray, also let us know if you have a better title than "Recently Passed Meetings" and if you all want to add any explainer text to either section.

**Comment by hancush** [comment]
Show meetings from the last two weeks, provided they're in the current calendar month. Hide section if no meetings within that window.

**Comment by hancush** [comment]
Add a new section, "Recent Meetings", to the homepage, below the "Upcoming Meetings" section.

This section should contain links to meetings that occurred in the last two weeks of the current calendar month. (That means, on March 1, even though there were meetings the last two weeks of February, this section should be empty.)

Consistent with `todays_meetings` and `upcoming_committee_meetings`,  implement a classmethod, `most_recent_past_meetings`, on the `LAMetroEvent` model that returns meetings within the specified time frame, or an empty queryset. (FYI, the naming convention for the proposed classmethod comes from [a similar one upstream in `django-councilmatic` called `most_recent_past_city_council_meeting`](https://github.com/datamade/django-councilmatic/blob/5b074f376667766e4b6dbf093871d294bb35fc51/councilmatic_core/models.py#L373).)

This section should be styled similarly to "Upcoming Meetings", but with some visual distinction, e.g., a different icon and/or button color, a horizontal rule, etc. You have creative liberty with the distinction, so long as it's cohesive with the rest of the site.

Metro has an extensive test suite. Please also add a test for your new classmethod. @fatima3558 has some experience with this pattern from her work on `todays_meetings`! The event tests also contain several examples of creating test events with different dates and mocking different times with [`freezegun`](https://pypi.org/project/freezegun/0.1.11/).

**Comment by hancush** [comment]
Stage for @shrayshray and Omar to meet with folks after this month's meetings to review.

**Comment by hancush** [comment]
Use concluded logic to make sure events don't show up in the new section until they have been broadcast.

**Comment by shrayshray** [comment]
@hancush The broadcast has concluded for Planning and Programming, but it's not showing in "Recent Meetings" yet. Is there a time frame in which we can expect to see it there?

**Comment by shrayshray** [comment]
@hancush Planning and Programming is showing in "Recent Meetings" now! So that's about 30 minutes after the meeting concluded. Good to know.

**Comment by hancush** [comment]
Whoops, @shrayshray, we made a little typo preventing the meetings from showing up. Fixed and deployed to staging! This morning's meeting is now showing up, and this afternoon's meeting should show up immediately after it concludes.

**Comment by shrayshray** [comment]
@hancush wonderful, thank you!

**Comment by shrayshray** [comment]
@hancush Confirming that the Finance, Budget and Audit meeting showed up in "Recent Meetings" immediately after concluding. Huzzah!

**Comment by hancush** [comment]
Yay! Big ups to @antidipyramid for his first data munging PR. :-)

**Comment by shrayshray** [comment]
@antidipyramid BIG UPS! Is it possible to list the recent meetings in order by date? It looks like they're being displayed alphabetically.
![image](https://user-images.githubusercontent.com/28063988/158868654-299d8a19-1972-47cb-9e29-83fdea8bfd05.png)

**Comment by hancush** [comment]
@shrayshray Done! We put them in reverse chronological order, so the most recent one is first. Let us know if this works for you.

**Comment by shrayshray** [comment]
@hancush @antidipyramid reverse chronological looks great, thank you! Some feedback from the Board Clerk (screenshot with notes below):
1. Under "Upcoming Meetings" and "Recent Meetings", could there be less space between the section headers and the list of meetings?
2. Above "Recent Meetings", could there be more space between the header and the button above it?
3. They'd like to remove the meeting and call-in info under the date and time
4. Add buttons to watch the meeting once the links are available
They were overall very pleased. Great work!!
![image](https://user-images.githubusercontent.com/28063988/158902805-34d4fa55-dfd8-412c-bc41-5d273d6a24a0.png)

**Comment by hancush** [comment]
@antidipyramid is on it!

**Comment by hancush** [comment]
Deployed.
