### ISSUE TITLE
BOARD MEMBERS: Add note on pending redistricting

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#798]
@shrayshray Can you provide some text about ongoing redistricting that we can put on the board members page? 🙏

**Comment by shrayshray** [comment]
@hancush On December 15, 2021, the County of Los Angles Citizens Redistricting Commission passed resolutions to adopt a final redistricting [plan](https://redistricting.lacounty.gov/wp-content/uploads/2021/12/LA-County-CRC-Resolution-Adopting-Redistricting-Plan.pdf) and [report](https://redistricting.lacounty.gov/wp-content/uploads/2021/12/LA-County-CRC-Resolution-Adopting-Redistricting-Report.pdf). Click [here](https://redistricting-lacounty.hub.arcgis.com/) to view the final redistricting plan and all other submitted maps in the Redistricting Hub. The map on this page will be updated once the County provides finalized maps.

**Comment by hancush** [comment]
@shrayshray We've added a note to the staging site: https://lametro-upgrade.datamade.us/board-members/

Look ok?

**Comment by shrayshray** [comment]
@hancush looks great, thank you!

**Comment by hancush** [comment]
Done and deployed!
