### ISSUE TITLE
Omit meetings without Minutes from Minutes page

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#808]
Include all meetings of the board, Crenshaw and LA Safe committees, whether or not they have an available minutes file yet. Exclude committees.

**Comment by hancush** [comment]
We're pulling the minutes page until this fix is in. To start this PR, revert the revert commit from #824.

```bash
git revert -m 1 <REVERT COMMIT HASH>
```

Then, add the fix to omit meetings without minutes.

[Here's a good overview of `git revert`](https://www.datree.io/resources/git-undo-merge), with a link to the git-scm docs for further reading.

**Comment by hancush** [comment]
Hi, @shrayshray – @antidipyramid landed a change to show all board meetings and meetings of the LA Safe and Crenshaw committees, but omit all other committee meetings from the minutes page. New version is deployed to the staging site. What do you think?

**Comment by shrayshray** [comment]
@antidipyramid @hancush i sent this out for review by the team and they all love it! We're good to go live.

**Comment by hancush** [comment]
Deployed!
