### ISSUE TITLE
Add DAG to run tag analytics management command

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#812]
Over in https://github.com/datamade/la-metro-dashboard, create a new DAG that runs the tag analytics management command on the first of every month.

**Comment by hancush** [comment]
Need to publish a built dashboard image to unblock @antidipyramid.

**Comment by hancush** [comment]
DAG implemented by @antidipyramid, but is being killed when run on staging. Assigning myself to debug.

**Comment by hancush** [comment]
@hancush to schedule pairing sesh week of 5/9.

**Comment by antidipyramid** [comment]
Shared Google drive folder with @shrayshray and Omar.
