### ISSUE TITLE
Priority: Remove call-in info for 3/31 meeting

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#820]
Can this be prioritized? For the upcoming 3/31 Measure R meeting (https://boardagendas.metro.net/event/measure-r-independent-taxpayer-oversight-7159aebed1a8/), can you please delete the following text from the website that references submitting public comments by phone?:
![image](https://user-images.githubusercontent.com/28063988/159083114-0f0f47db-527c-43cf-b6b7-c171c045cc93.png)

 
There are no live public comments during the Measure R meetings (neither are there for Measure M and ICAOC).

**Comment by hancush** [comment]
@shrayshray Should we also disable the live ecomment link that appears during the meeting?

**Comment by hancush** [comment]
@shrayshray Ah, disregard, I forgot we hid ecomment links a while ago!

**Comment by shrayshray** [comment]
@hancush, perfect! Looks great to me!
