### ISSUE TITLE
Board Members: Update Ara Najarian's headshot

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#832]
Ara Najarian has a new headshot - can you please replace his old one in the list of Board Members, and on his individual member page.
![Ara Najarian - Portrait 2020](https://user-images.githubusercontent.com/28063988/162289301-3d01fe34-7b26-4f8e-9caf-1cee5416ae9f.jpg)
.

**Comment by antidipyramid** [comment]
@shrayshray We just updated [Ara Najarian's photo](https://lametro-upgrade.datamade.us/person/ara-najarian-a9c58166e1da/) and changed 'ex-officio' to 'non-voting' on the [About page](https://lametro-upgrade.datamade.us/about/). 

How does it look on your end?

**Comment by shrayshray** [comment]
@antidipyramid great, thank you!
