### ISSUE TITLE
Evaluate app and server dependencies for upgrade candidates

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#846]
This site has been online for going on six years. We upgraded major dependencies a couple of years ago, but it would be prudent to review again and bring anything out of support / with security warnings up to a contemporary version.

To start, let's capture the current version of our major dependencies (Python, Django, Postgres, Solr) and whether that version has reached end of life. Also note whether anything [has active Dependabot alerts](https://github.com/datamade/la-metro-councilmatic/security/dependabot).

@antidipyramid Can you add this info in a comment here? Here's an example of this exercise from another DataMade project: https://github.com/security-force-monitor/sfm-cms/issues/707#issuecomment-916122866

**Comment by antidipyramid** [comment]
Here are the major dependencies we're running:

**Python 3.6.9**: No longer supported. The current version is 3.10. Support for 3.7 will also end soon so we probably want to upgrade to at least 3.8.

**Django 2.2.25**: No longer supported. The current version is 4.0.4. Django maintains "long term support" for the last feature release in a major update (i.e. x.2). Django 4.2 won't come out until sometime next year so I think it makes sense to shoot for Django 3.2. For any given version, Django recommends that we use the latest supported version of Python (for Django 3.2 that's Python 3.10).

**Postgres 9.6.12**: No longer supported. The current version is 14.3. 

**Solr 7.5**: No longer supported. The current version is 9.0.0. I think it makes sense to upgrade to Solr 8.8. 

We'll want to upgrade Python first as Python 3.6 is not supported by any Django version we'd want to upgrade to.

**Comment by hancush** [comment]
Support schedules for:

- Django: https://endoflife.date/django
- Python: https://endoflife.date/python
- Postgres: https://endoflife.date/postgresql

**Comment by hancush** [comment]
Clean up Ara Najarian's stray membership.

**Comment by hancush** [comment]
@hancush to ensure Metro admins have admin access to upgrade site for event removal, etc.

**Comment by hancush** [comment]
Done! Now, to deploy in #908.
