### ISSUE TITLE
About: Alphabetize Board Report Types + 2 other updates

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#856]
It's been a bit since we reviewed the [About Us page](https://boardagendas.metro.net/about/), and there a a couple of areas I'd like to update! It's been getting some attention internally because the Report Type definitions are really useful, so I hope this updates make them even more: 
1. Remove the description of "Types of Board Reports" (highlighted in the snip below) - the current text is a little off and I think the section speaks for itself.
![image](https://user-images.githubusercontent.com/28063988/170590068-c11052ac-84b2-4168-bdb5-86b3beffe31f.png)

2. Alphabetize the Board Report Types. It looks like they're organized by meta-type, but I think alphabetic organization would be easier to use for most users.

3. Change the name of what is currently the last item in the list, "Board Box" to "Board Box / Board Correspondence" and update the definition to read: “Formal information communication from Metro staff to the Board, which does not require Board action. Historically, these items were called "Board Box"(es), because a physical box containing each month's items was delivered to the Board for review. Because these items are now delivered digitally, their "Board Report Type" designation is "Board Correspondence" so the nature of these items is more clear to the public. We are in the process of importing Board Boxes to this website; in the meantime, please access Board Box/Correspondence items through the [Archive Search](https://boardagendas.metro.net/archive-search. You can also access a directory of Board Correspondence from 2015 to present, by year, here: http://boardarchives.metro.net/BoardBox/"

**Comment by hancush** [comment]
@shrayshray Deployed to the live site
