### ISSUE TITLE
Top Nav: Point Archives Search Links to FSS

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#864]
We're ready to replace the old Board Archives Search with our new Federated Search System! In the top navigation, please replace the the current URL on the link with this one: https://mtasearch01.metro.net:23352/apps/boardarchives/
![image](https://user-images.githubusercontent.com/28063988/175430653-eaa5e4a7-f3fb-46bc-b61c-7173a1abcb8f.png)

@camachoo Do you also want to re-add the link to Board Box Search, using this link: https://mtasearch01.metro.net:23352/apps/boardarchives/?tab=boardbox or do you view that direct link as having use just internally?

**Comment by hancush** [comment]
@shrayshray Deployed to the live site
