### ISSUE TITLE
Board Member/s - Replace Tony Tavares with Gloria Roberts

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#880]
Tony Tavares (non-voting member) is temporarily being replaced by Gloria Roberts. This change has been made in Legistar. Gloria's title should be "Caltrans District 7 Director (Interim)".
![GloriaRoberts](https://user-images.githubusercontent.com/28063988/182945379-c76c4b6c-e542-48d0-a4de-9f7298a13a52.PNG)

**Comment by hancush** [comment]
Hi, @shrayshray – Can you update the end dates of Tony Tavare's memberships, so they disappear from the site?

**Comment by hancush** [comment]
@antidipyramid Tomorrow, can you add Roberts' title to the scrape and headshot to the app site? See https://github.com/datamade/la-metro-councilmatic#adding-a-new-board-member

**Comment by hancush** [comment]
Ran the person scrape to bring Roberts in!

**Comment by shrayshray** [comment]
> Hi, @shrayshray – Can you update the end dates of Tony Tavare's memberships, so they disappear from the site?

Done.
