### ISSUE TITLE
Board Member/s pages: Add initial to Holly Mitchell's name

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#881]
Another initial-adding request! Please add a J. to Holly Mitchell's name so it reads "Holly J. Mitchell". I made this change in Legistar, can you please make sure the site is updated to reflect this? (Including her bio!)

**Comment by hancush** [comment]
Done!

**Comment by hancush** [comment]
Steps:

First, run a person scrape via the dashboard.

Then, shell into the server and clean up duplicate person and memberships.

```python
# Update existing person object
LAMetroPerson.objects.filter(given_name='Holly', family_name='Mitchell', name='Holly Mitchell').update(given_name='Holly J.', name='Holly J. Mitchell')
# Delete new person object
LAMetroPerson.objects.filter(family_name='Mitchell').order_by('-updated_at').first().delete()
# Delete memberships without person object
Membership.objects.filter(person__isnull=True).delete()
```

Re-run person scrape.

```python
# Delete obsolete memberships
 Membership.objects.filter(person__councilmatic_person__slug='holly-mitchell-68d838612b17', created_at__lt='2022-08-04').delete()
```

FYI, this method seems to result in loss of the correct title. Cc: @antidipyramid, possibly helpful context for your spelunking tomorrow.
