### ISSUE TITLE
Staging site not showing watch in Spanish link

### ISSUE THREAD

**Issue by neilarellano** [datamade/la-metro-councilmatic#888]
Hi, Hannah! During today’s Planning meeting, all the links (Watch in English, Watch in Spanish and Get Agenda PDF) were showing as expected on the home page of [boardagendas.metro.net] But on the staging site, only the Watch in English link was showing, see below.
 
Shelly Ray
Principal Transportation Planner, Research & Records Information Management
Office of Board Administration
LA Metro
![Picture1](https://user-images.githubusercontent.com/110051034/185229923-0e7b70ac-3678-4d75-9fd1-0dde128610e4.jpg)

**Comment by hancush** [comment]
Thanks, @neilarellano! 

I checked out the data, and we have the right GUID for the Spanish-language event in the staging database, so I think this may be a snafu in the template logic. Will take a look.

**Comment by neilarellano** [comment]
Thanks @hancush . Just noticed as well that the status of the meetings on the right hand side remain as "Upcoming" on the staging site, whereas it already shows "Concluded" in the production site. Please advise.

![image](https://user-images.githubusercontent.com/110051034/185231494-3bf6eb61-bbc9-438b-96cd-d844a07524bf.png)
![upcomingstatus](https://user-images.githubusercontent.com/110051034/185231571-dd62f8a5-3628-45d0-bf1c-4b7fa5c4310d.PNG)

**Comment by hancush** [comment]
@neilarellano Can you clarify whether the original issue and this one refer to the lametro-upgrade.datamade.us (original staging site) or lametro-app-upgrade (new staging site)?

**Comment by neilarellano** [comment]
Hi @hancush,

We apologize. We just checked and confirmed that it was on the original staging site. I will go ahead and just close the ticket.

Thanks!

**Comment by hancush** [comment]
@neilarellano No worries! I could have done y'all a favor and picked a more original subdomain. Do let us know if you see anything misbehaving on the new staging site today / this week!
