### ISSUE TITLE
Meetings: Delay on recordings being available

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#896]
Board admin staff made the English recordings of yesterday's Committee meetings public yesterday, but the links to watch them are still not showing on boardagendas.metro.net. I confirmed the links are showing on [metro.Legistar.com](https://metro.legistar.com/Calendar.aspx). They typically show on boardagendas.metro.net the day after they are made public. Could you please look into what might be causing the delay in the links showing?

**Comment by hancush** [comment]
Hi, @shrayshray – there was a transient Legistar error during the full event scrape Wednesday night, which caused it to fail. Audio links do not toggle the updated timestamp, so they generally only come in during full scrapes. Accordingly, the links came in, in the next successful full scrape last night.

We currently scrape all meetings with updates, as well as ones that are in the future, with the idea that meetings that haven't happened yet are most likely the change. How long after a meeting does it take for audio to be added? We might consider adding a backwards window, as well, so we are rescraping recently passed meetings more frequently, as well.

**Comment by shrayshray** [comment]
@hancush The audio is typically added the day after the meeting. On this one, it was added on the same day the meeting happened. A 72 hour backward window would probably be the best bet.

**Comment by hancush** [comment]
@antidipyramid For this issue, let's flex those code following skills. Can you please:

1. Find the spot in the code that causes us to scrape events that have been updated since a particular date, as well as events scheduled to take place after that date. (LMK if you'd like a hint!)
2. Propose an approach (pseudo code is ok if you aren't 100% sure on the implementation) for editing that spot to also retrieve events that happened within the previous 72 hours of a given date?

**Comment by antidipyramid** [comment]
@hancush 

It seems like the scrape behavior is defined [here](https://github.com/opencivicdata/python-legistar-scraper/blob/2507bea809ccc835ca39dcc0ae7e1dcf8913a8ff/legistar/events.py#L251) in `LegistarAPIEventScraperBase.events()` to which we pass a date [in the Metro scraper](https://github.com/datamade/scrapers-us-municipal/blob/master/lametro/events.py#L194) to scrape events from then. 

I could be misunderstanding but couldn't we just start any Metro scrape three days before the given window? That would be something like 

```python
    def scrape(self, window=None) :
        if window and float(window) != 0:
            n_days_ago = datetime.datetime.utcnow() - datetime.timedelta(float(window)) - datetime.timedelta(hours=72)
        else:
            n_days_ago = None

        events = self.events(since_datetime=n_days_ago)
```

**Comment by hancush** [comment]
That's one way to do it! The logic to scrape events that haven't happened yet currently lives on the Legistar scraper, [here](https://github.com/opencivicdata/python-legistar-scraper/blob/2507bea809ccc835ca39dcc0ae7e1dcf8913a8ff/legistar/events.py#L232), so it feels a little inconsistent to have one piece of the logic there, and one piece upstream on the jurisdiction scraper. OTOH, adding a larger backward window than the one specified feels a bit more unexpected than always scraping future events. What do you think? Where makes sense to you, given these considerations?

**Comment by hancush** [comment]
Related issue on the Legistar lib, here: https://github.com/opencivicdata/python-legistar-scraper/issues/107

**Comment by antidipyramid** [comment]
@hancush I think where the change should be made depends on whether we think this is behavior should be particular to LA Metro or something we'd want to automatically do for other municipalities' Legistar searches as well.

Regardless of municipality, audio recordings will always be uploaded some time after a meeting has finished so I'm leaning towards making the change in the Legistar scraper.

**Comment by hancush** [comment]
Great thinking, @antidipyramid! Want to draft that up?

**Comment by hancush** [comment]
Done in https://github.com/opencivicdata/python-legistar-scraper/pull/119.
