### ISSUE TITLE
Allow Metro to manage board member headshots and bios

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#909]

**Comment by hancush** [comment]
Supersedes #552, #885 

It seems like it's urgent to be able to handle this content. Let's talk about what this might look like.

**Comment by hancush** [comment]
Metro is accustomed to performing admin actions via entity detail pages, as opposed to the admin interface. 

Add a form to the person detail page that allows logged in users to upload a headshot and/or input a bio to the person detail page. 

If a headshot is provided, save the URL under the `image` attribute: https://github.com/opencivicdata/python-opencivicdata/blob/e74868c68a37334637a01a14bd23764e87c902d1/opencivicdata/core/models/people_orgs.py#L369

If a bio is provided, save it under the `biography` attribute: https://github.com/opencivicdata/python-opencivicdata/blob/e74868c68a37334637a01a14bd23764e87c902d1/opencivicdata/core/models/people_orgs.py#L383

**Comment by neilarellano** [comment]
Hi Team,

I just wanted to ask if this feature will include removing entries for members (assuming that the site does not automatically remove the member entry when the member is no longer part of the board/committee in Legistar).

**Comment by hancush** [comment]
Hey, @neilarellano – Memberships should fall off the site automatically after their end date, as set in Granicus.
