### ISSUE TITLE
Question about Board Report PDF

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#91]
The folks at LA Metro would like to have the PDF for Board Reports available on the Bill detail view.

Currently, we only display the plain text (under "Report Text"):

https://lametro.datamade.us/board-report/2016-0878-914bb1b5593a/

A PDF of the "Board Report" is often available on Legistar:

https://metro.legistar.com/LegislationDetail.aspx?ID=2882011&GUID=CD9EA9DF-C99F-420D-88D7-8F6F6F4A522E&Options=ID|Text|&Search=2016-0878

However, we do not have that document in the ocd api (assumed to be under "versions" with the other attachments):

http://ocd.datamade.us/ocd-bill/0e886916-deef-4f59-9e66-914bb1b5593a/

Is there a reason to omit the Board Report PDF in the api? Or am I overlooking something?

**Comment by fgregg** [comment]
Where can I find the "Board report" on 

https://metro.legistar.com/LegislationDetail.aspx?ID=2882011&GUID=CD9EA9DF-C99F-420D-88D7-8F6F6F4A522E&Options=ID|Text|&Search=2016-0878

I don't see a link to it.

**Comment by fgregg** [comment]
Nevermind, found it. I'll need to fix this in the scraper. Would you mind opening an issue.
