### ISSUE TITLE
Investigate reporting tools for GitHub project

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#912]
1. Number of issues opened and closed within a period of time.

**Comment by hancush** [comment]
@shrayshray The main reporting tab shows this! It's just not immediately obvious right now because this project only has three days of history. Let's take a look in January and see if it gives you the metric/s you need, otherwise we can play around together with the custom views.

**Comment by shrayshray** [comment]
@hancush woohoo! Sounds good, thank you!
