### ISSUE TITLE
Board Members: Update Karen Bass

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#915]
Please add the headshot below for Karen Bass, the new mayor of Los Angeles. I'll add her bio here as well once we have it. 
![Karen Bass](https://user-images.githubusercontent.com/28063988/207450899-fb195349-2e33-4443-83df-1362f6af304c.jpeg)

**Comment by shrayshray** [comment]
And here is her bio:
Karen Bass is the 43rd Mayor of Los Angeles and the first woman and second African American to be elected as the city's chief executive. With an agenda focused on bringing urgency, accountability, and a new direction to Los Angeles, she will start her term with a focus on housing people immediately and increasing safety and opportunity in every part of Los Angeles.

A daughter of our city, Mayor Bass was raised with her three brothers in the Venice/Fairfax neighborhood and is a proud graduate of Hamilton High School. After serving as a front-line healthcare provider as a nurse and as a Physician Assistant, Mayor Bass founded the Community Coalition to organize the predominantly Black and Latino residents of South L.A. against substance abuse, poverty and crime, and to pioneer strategies to address the root causes behind the challenges faced by underserved neighborhoods.

She then went on to represent Los Angeles in the State Assembly and was elected by her peers to serve as Speaker, making her the first African American woman to ever lead a state legislative body in the history of the United States. Her time in leadership intersected with the Great Recession, and she was honored with the John F. Kennedy Profile in Courage Award for reaching across party lines and making tough decisions to keep the state from bankruptcy while protecting vital services.

While representing Los Angeles and Culver City in Congress, Mayor Bass helped protect small businesses during the pandemic, created policy to drive local jobs from federal infrastructure funding, and led the passage of what the Los Angeles Times called “the most significant child welfare policy reform in decades.”

Mayor Bass earned her bachelor's degree in health sciences from CSU Dominguez Hills before graduating from the USC Keck School of Medicine Physician Assistant Program and earning her masters degree in social work from USC.

Mayor Bass’s oldest daughter Emilia planned to follow in her mother’s footsteps working for social change. The Mayor-elect continues to be inspired by Emilia and her son-in-law Michael’s passion for life. She has three other children, Scythia, Omar and Yvette, and two grandchildren, Michael and Henry, who live in the Los Angeles area.

**Comment by hancush** [comment]
@shrayshray Done!
