### ISSUE TITLE
Full reindex consumes all available memory on upgrade instances

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#929]

**Comment by hancush** [comment]
Failures occurred on both lametro.datamade.us (upgrade staging) and lametro-prod.datamade.us (upgrade production).

**Comment by fgregg** [comment]
mission log:

1. if i'm following the commit history for https://github.com/datamade/la-metro-dashboard then the staging database was pointing to upgrade staging. the solr instances stay the same, but let's check the index names

**Comment by fgregg** [comment]
2. okay, that's not quite right since the we use the settings deployment file for staging and production, so they have separate instances.

**Comment by fgregg** [comment]
3. okay on lametro.datamade.us, running `python manage.py rebuild_index` results in 0 bills indexed, but there are 63 bills in the database according to `python manage.py dbshell`

**Comment by fgregg** [comment]
4. finally, on lametro-prod.datamade.us i was able to get `python manage.py rebuild_index --batch-size=1` to run (though i killed it before completion). However `python manage.py rebuild_index --bath-size=100`, which what we do in airflow got into a bad loop where the memory was exhausted causing the communication with SOLR to timeout, which then would be retried.

@hancush, lametro-prod.datamade.us is a t3.small, while the server for current boardagenda is a t2.large. 

I think if you beef up the server for lametro-prod.datamade, everything will be well.

**Comment by fgregg** [comment]
assuming that the server could handle a larger batch size, then a larger
batch size will lead to a shorter overall job

**Comment by fgregg** [comment]
I'll try to index with batch-size=1 and make sure it completes.

**Comment by fgregg** [comment]
looks like it's stuck even with batch-size=1. i think you need to increase the server capacity

**Comment by fgregg** [comment]
i suspect the deeper thing is that one one the bills has a huge attachment.

**Comment by fgregg** [comment]
I upgrade lametro-prod.datamade.us to t2.large and lametro.datamade.us to t3 medium, and now indexing is working apace.
